### ISSUE TITLE
Prompt to export database even when backup monitoring file is not set up

### ISSUE THREAD

**Issue by MaplesThroughWindows** [mooltipass/moolticute#1003]
Every time I add a new credential to the Mini BLE from the Credentials tab, I am prompted with the following message:
```
Credentials on the device are more recent.
Do you want to export your database?
```
I read the manual.  On page 27, it says:

`You can also select a **backup monitoring file** to make sure your Mooltipass database is always in sync with it.  Once set up you will be prompted for import or export operations when changes to your Mooltipass database or the monitored file are detected.`

I haven't set up a **backup monitoring file**, so why do I keep receiving these prompts?

**Comment by limpkin** [comment]
hello,
please keep our bug report template, as we end up asking you the same questions.
What's your OS?

**Comment by MaplesThroughWindows** [comment]
I'm not always presented with a Bug Report Template to follow here on the Moolticute project, I think GitHub caches the prior state of the last time an issue was opened, and sometimes that means an issue I started and then aborted and deleted all the content from, so I get an empty issue with no template at all when I start.

macOS 10.13.6.
Moolticute 0.53.7
