### ISSUE TITLE
Is the backup database encrypted?

### ISSUE THREAD

**Issue by MaplesThroughWindows** [mooltipass/moolticute#1004]
There's no mention in the manual of the encryption method employed for protecting the backup database.  Is this just kept in clear text somewhere on the local computer?

**Comment by limpkin** [comment]
hello!  
passwords, data, notes in the backup file are encrypted using your unique AES key. The backup file is encrypted with a key readable from the smartcard.

**Comment by MaplesThroughWindows** [comment]
That's great, thanks for clearing that up.

I didn't see any mention of this in the manual, though.  Could you add 
it?  I'm sure I'm not the only one who will have doubts in this regard.

Mathieu:
