### ISSUE TITLE
[OSX] Moolticute doesn't respect Dock

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#1007]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior

It respects the Dock and is sized accordingly.

### Actual behavior

<img width="972" alt="Screenshot 2022-03-14 at 11 24 27" src="https://user-images.githubusercontent.com/24696606/158153568-b5fe3a4d-28d0-4dcf-86e9-73103efbcdc0.png">

It goes behind and I can't see stuff at the bottom.

Probably related to #997 

### Step by step guide to reproduce the problem
Open on a 13" MacBook Pro

### Moolticute Version

0.53.7

### Operating System
Mention if you are using either:
- MacOS  

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
could you try our testing release at https://betas.themooltipass.com/v0.53.13-testing/ ?

**Comment by KDederichs** [comment]
Yep fixed in there, thanks :)
