### ISSUE TITLE
To investigate: a possible situation where moolticute creates a duplicated service name

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#1011]
Following https://github.com/mooltipass/minible/issues/320 I wonder if there's not a situation where moolticute is going to create a duplicate service. 
I could imagine a case where one backup file contains 2 logins for a service, and the user DB having only one.... to be tested.
Perhaps we should check in moolticute (during the database check operations) for duplicated services? 
To check if a mini BLE has a duplicated service: go to the login menu, press and scroll up. If it reboots, then the DB has an issue.

**Comment by limpkin** [comment]
so I tried several operations to reproduce the issue and wasn't able to :/
@deXol maybe let's integrate in the final check when leaving MMM a check for same service names (using strncmp) with different addresses?

**Comment by barathrm** [comment]
I just experienced this issue when trying to import (without deleting) a database. It would be helpful to know which service is involved, maybe moolticute could show it as part of the warning dialog box?
