### ISSUE TITLE
[Visual] Icon for dark theme

### ISSUE THREAD

**Issue by awilkins** [mooltipass/moolticute#1029]
On a dark themed system bar, the Moolticute is hard to see, especially on a small hi-res screen.

![image](https://user-images.githubusercontent.com/368399/165254187-2e5c2cd9-9b7d-4d01-8fb3-c07aefc369f9.png)

**Comment by WebmasterTD** [comment]
Have you tried changing the Systray icon color?
Settings > Systray icon > White
![Screenshot 2022-04-26 at 15 54 56](https://user-images.githubusercontent.com/16672190/165316247-b8158e41-96c1-4168-ad4d-2822d8d95a01.png)

**Comment by awilkins** [comment]
Aha, yes - I just hadn't thought to look for a setting for it, most applications select the right icon automatically.

**Comment by limpkin** [comment]
@deXol can we detected the dark theme?
@awilkins how did you setup that dark bar?
