### ISSUE TITLE
Incessant Low Battery Warnings

### ISSUE THREAD

**Issue by rastagraffix** [mooltipass/moolticute#1034]
### Expected behavior

A warning when the battery is low, with occasional reminders thereafter.

### Actual behaviour

Incessant low battery warnings when the battery hits 30%.  I haven't had a chance to dig into the code yet, but what I *think* is happening is when the battery hits 30% a warning gets generated. At the next battery check, the voltage has recovered just enough to reset the "low battery" status. Then the check after that shows just below 30%, so we get another warning. The lack of hysteresis can mean I get spammed with alert popups every minute or two.

I think the easiest fix is to set a timer after the first alert that blocks any subsequent alerts until 1) the timer expires, or 2) the voltage drops by a further 10%, whichever hits first.

I would suggest 60 minutes for the timer as long as the remaining battery is above 5%, at which point it reduces to 10 minutes. And for the voltage thresholds, I would set the steps to 30 - 20 - 10 - 5% as the points where the alert fires regardless of the timer status (and then resetting the timer as described above).

I still don't quite have everything set up to get moolticute to build just yet, otherwise I would have included a diff :-(.

### Step by step guide to reproduce the problem

Charge your BLE, then wait.

### Moolticute Version

0.55.0
Bundle 8

### Operating System

MacOS 12.3.1
  
### Mooltipass Device

Mini BLE

**Comment by limpkin** [comment]
hmmm that's quite interesting.... I remember seeing a similar bug on MacOS only...

**Comment by limpkin** [comment]
hello @rastagraffix !
Is it a warning from moolticute or macOS?
If the latter, could you try our latest beta on beta-updates.themooltipass.com/ ?

**Comment by bwosborne2** [comment]
I have been seeing this issue first on Windows 10 and then on Windows 11. 
After it is unplugged from USB for a few hours, I get the below 30% warning. This has happened since new so I consider the battery & Bluetooth features useless, in my experience.

Moolticute v0.55.0
Aux MCU Version 0.70
Main MCU Version 0.80
Bundle 8

**Comment by KenjiTakahashi** [comment]
Still happening with 1.00.0. Overnight, I can get literally hundreds of these.

![Screenshot 2023-01-12 at 11 12 48](https://user-images.githubusercontent.com/431488/212559068-ce3cc523-6325-4ce6-92fb-240106dcbfbe.png)
