### ISSUE TITLE
Single domain, multiple logins

### ISSUE THREAD

**Issue by stonemirror** [mooltipass/moolticute#1035]
### Missing feature

I use a site which has one account for general use, and another to manage subscriptions I have with the site. When I log in with the subscription credentials (on a subdomain), it offers me only the option of UPDATING the existing (general) credentials (on the main domain), not creating the NEW set of credentials for the same site.

### Justification
Just for convenience and to avoid accidentally overwriting credentials accidentally.

### Workarounds
Make a new credential manually in MooltiCute, give it a unique name, update the device with it.

**Comment by limpkin** [comment]
Hello!

i'm guessing this is an extension related issue. Could you provide us with a step by step guide?

**Comment by stonemirror** [comment]
Sure.

Background: I'm a user on a site, counter.social, and log into that domain with a set of credentials already stored on the Mooltipass. There's a subdomain, proportal.counter.social which is used to manage paid subscriptions associated with "Pro" status on the main site — I believe it's doing a redirect without changing the URL, to a third-party payment provider.

1. I go to log in to proportal.counter.social, using the credentials appropriate for that specific subdomain.
2. The Mooltipass offers to update the existing credentials for counter.social, which is definitely not what I want to be doing here.

Workaround: Manually create a "proportal.counter.social" entry in MooltiCute, add the credentials for THAT login, update the MooltiPass.

**Comment by limpkin** [comment]
hello! it sounds like you'd simply need to enable subdomain support in moolticute's settings no? :)
