### ISSUE TITLE
Firmware upgrade file selection dialog doesn't allow opening bundle on MacOS Monterey

### ISSUE THREAD

**Issue by elonen** [mooltipass/moolticute#1039]
### Expected behavior

Selecting update-from-bundle file (a .dmg) in Moolticute would upgrade the device.

### Actual behavior

Operating system's file selection dialog that opens doesn't allow selecting the bundle file. Rather, it **stays grayed out** as if wrong file type.

### Step by step guide to reproduce the problem

Follow firmware upgrade instructions on Moolticute and try to open the downloaded .dmg file from disk.

### Moolticute Version

0.55.0

### Operating System

MacOS Monterey 12.3.1

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
Hello!

The downloaded update file is a .img and not a .dmg . it seems in some
cases safari will just decide to change the extension.
Could you rename the extension and try again?

**Comment by elonen** [comment]
Yes, renaming to .img worked. The browser that downloaded the file was in fact Chrome.
