### ISSUE TITLE
Release v0.55.5-testing is not working on MacOS

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/moolticute#1047]
Release v0.55.5-testing is not working on MacOS 12.4 on M1.
Rolled back to v0.55.4-testing it works fine.
The application is not starting up.

**Comment by limpkin** [comment]
I'm indeed aware :/... I'm desperately trying to find someone to fix that :/

**Comment by limpkin** [comment]
the latest beta now works :)
