### ISSUE TITLE
Pop-ups and drop-downs don't work in Sway (tiling Wayland compositor)

### ISSUE THREAD

**Issue by hijackeel** [mooltipass/moolticute#1057]
### Expected behavior
Pop-up menus (e.g. password generator) and drop-down menus should be usable.

### Actual behavior
They're glitchy and unusable.

### Step by step guide to reproduce the problem
Open Moolticute in a Sway session and try to use it.

### Moolticute Version
I _think_ it's this commit: https://github.com/mooltipass/moolticute/commit/228313387fcd80c974f779defa6bc6fa60dc618e
A while back I used the 9999 ebuild (Gentoo) to compile/install Moolticute from the latest Git commit at the time, since the package maintainer doesn't seem to keep up to date with releases: https://packages.gentoo.org/packages/app-crypt/moolticute

### Operating System
Gentoo Linux

**Comment by hijackeel** [comment]
FYI, I'm now on the latest commit ( https://github.com/mooltipass/moolticute/commit/0331c6d59098aa91fe9236ebbf85c1319c3b7ad7 ) and still having this issue.

**Comment by hijackeel** [comment]
I noticed that this problem is gone after a system update. I haven't updated Moolticute yet, so Moolticute wasn't the problem, but I don't know for sure what _was_ the problem (I'm guessing it was Sway). Moolticute also now appears as a floating pop-up instead of full-screen, so that might be related.

**Comment by limpkin** [comment]
it should indeed be a floating popup :)
