### ISSUE TITLE
Another way to enable the advanced/update tab

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#1061]
### Missing feature

It would be nice if there was another way (file menu for example) to enable the advanced and update tabs.

### Justification
I'm recently trying to enter the firmware update tab on mac but it's not opening (I assume due to some system hotkeys) so that's a bit frustrating....
It would be a lot better if you just had a menu point "Window" or something up there with options to display those...
![Screenshot 2022-07-09 at 08 38 59](https://user-images.githubusercontent.com/24696606/178094816-2a394981-bcba-4961-b634-af40ea754f72.png)

### Workarounds
Trying to disable all the system hotkeys I guess? Not very viable though

Edit: While I found it, it would be still nice to have an alternative to the hotkeys :)

**Comment by deXol** [comment]
Fixed in #1203
