### ISSUE TITLE
Can no longer update Mini BLE from Standard database

### ISSUE THREAD

**Issue by danjulio** [mooltipass/moolticute#1064]
### Expected behavior
Save database from Mooltipass Standard.  Update Mini BLE from that database to keep the two devices in sync.

I was using this process to keep the  Mini BLE up-to-date with the Mooltipass Standard (Standard is on my desktop computer where I create most passwords, BLE is used for travel).  I both moved to a new M1 Macbook pro and updated Moolticute and this process no longer works.

I saw some discussion of a new database format.  How can I keep both devices in sync but enter new passwords on the Mooltipass Standard?

### Actual behavior
Get a pop-up "Selected File is Another User's Backup"

### Step by step guide to reproduce the problem
1. Plug in Mooltipass Standard.  Export to File
2. Plug in Mooltipass BLE.  Attempt to Import From File (with original Card and with new Card)
3. 
### Moolticute Version
v0.55.0

### Operating System
OS X 12.2.1

### Mooltipass Device
Mooltipass Standard v1
Mooltipass Mini BLE Bundle version 8 (Aux 0.70, Main 0.80)

**Comment by danjulio** [comment]
*sigh* Never mind.  I found the instructions.  Sorry...

**Comment by limpkin** [comment]
it happens :)
