### ISSUE TITLE
Import of .csv backup files.

### ISSUE THREAD

**Issue by DalenVigil** [mooltipass/moolticute#1085]
Most password managers, especially browser-based password managers, allow plain-text .csv export. Moolticute doesn't allow for .csv importation forcing every entry to be manually re-added if you want to use Mooltipass. Currently Moolticute seems to only allow .bin files for importation of a credential backup. If ones credentials are strong passwords with high entropy, manual entry will be tedious at best.

Basic .csv files with some simple column header manipulation would allow for easy importation and organization into Moolticute, easing the transition from a traditional password manager to the hardware-based solution that is Mooltipass.

Manually entering every password as a new entry within Moolticute is a frustration workaround.

**Comment by limpkin** [comment]
we do offer this feature :)
Have a look at our user manual, section H) Advanced tab
