### ISSUE TITLE
Moolticute crashes on Credential Linking

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/moolticute#1088]
Trying to use the new credential linking feature. It's crashing every time I select the account I want to link against.

### Step by step guide to reproduce the problem
Select a credential I want to be linked eg.: messenger.com
Click in the linking icon next to the password field.
select the credential I want to link against eg.: facebook.com
Moolticute crashes immediately.

### Moolticute Version
0.55.19

### Operating System
- MacOS Ventura 13.0.1
  
### Mooltipass Device
- The Mooltipass Mini BLE - Aux MCU 0.72 Main MCU 0.83

Couldn't get logs, they disappear on app restart.

**Comment by limpkin** [comment]
@WebmasterTD is this still happening?

**Comment by limpkin** [comment]
pinging @WebmasterTD

**Comment by limpkin** [comment]
after chatting with @deXol, this is confirmed to be fixed.
