### ISSUE TITLE
Downloading files from moolticute ignores BLE confirmation request

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#1089]
### Expected behavior
In the Moolticute Files tab, downloading a file on Windows 10 by selecting the floppy icon of a file in the quick access list, the directory and name of the target file on the PC is displayed and the BLE requests me to confirm the download.
However, the download occurs without me confirming on the BLE, and the message disappears from the BLE after a few seconds.

**Either...** 
The confirmation message should not be displayed on the BLE

**Or...**
The file should not be transferred until after I confirm on the BLE.

### Actual behavior
The BLE confirmation dialog is ignored.

### Step by step guide to reproduce the problem
In Moolticute, download a file from the quick-access list.
Press save in the Windows file dialog box (ignoring the BLE confirmation request).
 
### Moolticute Version
v1.00.0

### Operating System
Mention if you are using either:
- Windows 10

  
Other operating systems are not supported.

### Mooltipass Device
Mention if you are using either:

- The Mooltipass Mini BLE version 12.

**Comment by limpkin** [comment]
Hello!

Are you in simple mode? If so, this behavior may be expected :)
