### ISSUE TITLE
Unable To View/Change Passwords In Moolticute Credential Manager

### ISSUE THREAD

**Issue by invertlook** [mooltipass/moolticute#1091]
**Expected behavior**
Select "Show password" in moolticute & password is then visible (for me to then edit)

**Actual behavior**
Many of the passwords I select at random simply flag "password query was denied"
The one which I wanted to initially change brings up "please approve on device" in Moolticute, but the device doesnt actually get any text prompt, but there is a small stall in the animation to the left of "Device Managment" on my device.

Worth noting most of these entries are imported by mass from a csv file, as my Mooltipass is realtivly new.
No issues using the device for logging in with these passwords, just issues editing in Credential Manager.

**Step by step guide to reproduce the problem**
Open credential manager
Confirm Manage database on device
Scroll down to various service or entry
Select "show password"
Either password query was denied will display or please approve on device will display (device only displays "Database Managment"

**Moolticute Version**
V1 (also tried rolling back to 0.55)

**Operating System**
Mention if you are using either:
Windows 10
  
**Mooltipass Device**
The Mooltipass Mini BLE
Bundle 12

**Comment by limpkin** [comment]
We're currently investigating that one... do you have by any chance used the credential linking feature we recently released?

**Comment by invertlook** [comment]
Hello, no I havnt tried any credential linking as yet.

**Comment by limpkin** [comment]
could you run an integrity check and let us know its result?

**Comment by invertlook** [comment]
![Integrity](https://user-images.githubusercontent.com/119418517/204562157-096ea615-97d2-4075-bf6b-2b1a7042942b.JPG)

**Comment by invertlook** [comment]
Unfortunatly not. Cant find rhyme nor reason to what I can view and what I cant.
Also now having issues inputting a new site mannualy via  moolticute, as per this error

**Comment by invertlook** [comment]
![MC](https://user-images.githubusercontent.com/119418517/204573519-df21b0ed-dd2a-4ed3-a444-846edead50ec.JPG)

**Comment by limpkin** [comment]
any special characters in the logins or services?

**Comment by invertlook** [comment]
I just created an new entry
Website - Site
Login - Name
Password - Password

When I hit save all changes in moolticute, I did ge ta prompt on my device.
But then get "couldnt change all passwords" on Moolticute
See attached test.

**Comment by invertlook** [comment]
[Moolti Test.docx](https://github.com/mooltipass/moolticute/files/10114729/Moolti.Test.docx)

**Comment by limpkin** [comment]
let's try to do some advanced debugging... would you be able to find a minimalist scenario (for example adding a credential, then trying to view it without success), possibly on a new user profile, then enable the debug logs, and send us the logs of that scenario to support(at)themooltipass(dot)com? 
my goal here is to see the log of the credential creation and recall :)

**Comment by invertlook** [comment]
Sure thing, will do that and reach out.

Cheers

**Comment by limpkin** [comment]
what's your language? on windows too?

**Comment by invertlook** [comment]
So bit of progress, I erased my profile and tried rebuilding my database again (manually)
Started with the sites I was unsuccessfull with earlier & all are working fine.
So will continue to rebuild in this controlled manner vs my mass import from a Chrome export csv that I orginally had done.

**Comment by invertlook** [comment]
> what's your language? on windows too?

English, Windows

**Comment by limpkin** [comment]
your regional settings are english too I suppose?

**Comment by invertlook** [comment]
> your regional settings are english too I suppose?

Yes they are, not sure if you saw my reply above, but the issue evaporated when I deleted my profile and started inputting info mannualy. Doesnt help with debugging, but that would have been the only way for me to test a new profile, as im away for work (with only the one card on me)

**Comment by limpkin** [comment]
so possibly the csv import part is at fault then.

**Comment by limpkin** [comment]
hmmm... let me know if you get the issue again... I'd still like to get to the bottom of this

**Comment by invertlook** [comment]
> hmmm... let me know if you get the issue again... I'd still like to get to the bottom of this

Yeah certainly will do. So far so good.
