### ISSUE TITLE
Mooltipass mini: credentials management no longer working with Moolticute 1.00.0

### ISSUE THREAD

**Issue by erdnamulb** [mooltipass/moolticute#1092]
### Expected behavior
When I open the credentials management in Moolticute, I want to change/ edit existing entries.

### Actual behavior
Mooltipass asks for permission/ code for credential management; Moolticute loads data from Mooltipass mini; the list being shown of my existing entries ist not editable, nor clearly readable; lots of special characters are showing up beside the credential data fragments; no editing can be done, only "leave credentils management"; problem occurs with 2 different databases on 2 different Mooltipass mini devices with 2 different cards.

### Step by step guide to reproduce the problem
1) use Mooltipass mini (NOT BLE)
2) insert card, enter code
3) open Moolticute -> Enter credentials management Mode -> confirm on device/ enter PIN
4) look at credentials in Moolticute: no entry can be edited (not clickable); entries contain strange special characters
5) occurs with 2 independent devices and 2 independent credential databases and 2 different cards

### Moolticute Version
1.00.0

### Operating System
Mention if you are using either:
- Windows 10

### Mooltipass Device
The Mooltipass Mini

EDIT: **Downgrading Moolticute from 1.00.0 to 0.55.0 solves the problem** and all entries can be edited on the devices. So definitely a problem with the Application.

**Comment by limpkin** [comment]
Anything special with you W10 install? I just tried on a W10 machine without any issue:
![image](https://user-images.githubusercontent.com/6170291/204606237-c13cc293-a1ea-4086-892f-9a5085476908.png)

**Comment by erdnamulb** [comment]
As mentioned: the problem exists on three different computers, all running Win10 pro with latest patches - nothing special (no dev environments or similar - just office PCs or Laptops)

All entries were generated with Moolticute versions <1.00.0. With 1.00.0 I cannot access a single one to edit it. If I try in credentials management, the App says that access was denied (although PIN was given and I'm in the credentials management mode). Also strange characters appear in credentials management entries. This only occurs with 1.00.0. Works all fine with 0.55.

Integrity check of one of the Mooltipass (I have 2 mini which all show same behavior with 1.00.0) for information:
![grafik](https://user-images.githubusercontent.com/98773894/204737230-6b4dc637-7836-4424-bcba-2dde39a237c3.png)

**Comment by limpkin** [comment]
could you enable the debug logs, and send us the logs for when you try to access a given credential? 
I'm guessing moolticute is querying the device and somehow you're not getting a prompt on it

**Comment by erdnamulb** [comment]
Now I did the following:
1) take fresh card, insert, create new user with Mooltipass connected to Win10 pro, Moolticute 0.55.0
2) generate 3 sample entries with moolticute Application
3) disconnect & move device to Win10 pro Laptop with Moolticute 1.00.0 running
4) enter credentials editing mode and there the strange characters appear and credentials can not be managed/ edited 
5) logged all in debug mode with the Moolticute 1.00.00
6) connecting back to Win10 pro machine with Moolticute 0.55 shows no problems - behavior as expected

![moolticute1](https://user-images.githubusercontent.com/98773894/204823122-534a59f3-a709-4c3e-9a60-fa6915509028.png)

...it does not matter on which machine I create the credentials. As long as I do this in 0.55 and want to access them in 1.00.0 it will fail. Even just showing the passphrases in credentials mode gives the error "access denied" (see screenshot below).

![moolticute2](https://user-images.githubusercontent.com/98773894/204823164-fad74f13-acdf-4f5f-9eea-3c8c7c53e6fb.png)

[2022-11-30_moolticute_log.txt](https://github.com/mooltipass/moolticute/files/10124126/2022-11-30_moolticute_log.txt)

Trying to access credentials on v1.00.0 has been logged in debug mode - see file below.
Can't believe that I'm the only one having this behavior...  :-o

**Comment by limpkin** [comment]
@deXol I think the terminating 0 detection isn't happening, and maybe credential querying is sending the wrong string as well

**Comment by limpkin** [comment]
@erdnamulb : we've just released 1.00.1 at https://github.com/mooltipass/moolticute/releases .. could you give it a quick go and let us know if things improved?

**Comment by erdnamulb** [comment]
Tested on all available Computers with all available devices -> works like a charm. All entries accessible and can be edited as expected.
Thanks for the lightspeed-solution!

**Comment by limpkin** [comment]
woot!
