### ISSUE TITLE
MMM: Discarding changes button is unintuitive

### ISSUE THREAD

**Issue by barathrm** [mooltipass/moolticute#1099]
### Expected behavior

In credentials management mode, clicking the discard changes button should show a popup or message saying that you need to **long-click/hold** the button which doesn't require you to long-click the button since you don't know yet that that's what you need to do :D 

### Actual behavior

I first started submitting a bug report because I thought the button was broken. When you press it quickly it looks like nothing happens.

### Step by step guide to reproduce the problem

- Connect minible, unlock it
- in moolticute, enter credentials management mode
- make a change
- fast-click the discard changes button. notice how it's almost impossible to see that there's a message shown to hold it to discard changes

**Comment by limpkin** [comment]
closing this one as we have a setting to disable this behavior:
![image](https://user-images.githubusercontent.com/6170291/224535251-20baa339-8858-4da8-a91f-34fadc82ad31.png)
