### ISSUE TITLE
Add option to not check TLDs again existing list when entering domain extensions for the "multiple domains" functionality.

### ISSUE THREAD

**Issue by bertvandepoel** [mooltipass/moolticute#1100]
Currently, if you enter a TLD/extension that's not on the list included in the Moolticute code, it's silently ignored. For example adding ".com.be" for Amazon, which is not an officially designated TLD but a company that bought com.be and is selling subdomains. But similarly sometimes companies have internal TLDs, same for developers using something like .local. In my opinion it should first of all error and not silently throw away certain items. As discussed on IRC, including an option to accept unknown extensions would be nice. I would suggest not making this a general option, but rather adding it to the small dialog, for example a checkbox underneath the text box with something like "allow non-standard extensions".

![Screenshot at 2022-12-04 04-29-45](https://user-images.githubusercontent.com/4948317/205473405-e21fa6db-59b5-4431-bc1c-e69b75a42a10.png)

**Comment by rsrdesarrollo** [comment]
Hi @limpkin, 

I'm happy to contribute with a PR on this one, but first I need to know something.

Do you have this limitation because on the device you are storing something like a bitmap instead of the full list of TLD as text? (because of the small amount of memory)

If that's so... I'm afraid this will be hard to solve for all cases :(

**Comment by bertvandepoel** [comment]
I was under the impression that this is a UX feature, to prevent mistakes (even though I'd expect an error/warning or live validation would then be better)

**Comment by limpkin** [comment]
@bertvandepoel is indeed correct. last we talked about this, we wanted to add an option to moolticute settings tab to disable TLD checks.

**Comment by rsrdesarrollo** [comment]
PR should fix this. To be hones, it's my 1st time programming for a QT app, so code is probably a 💩
