### ISSUE TITLE
App-Error after update to 1.0.1 on Win7

### ISSUE THREAD

**Issue by Jan-NiklasB** [mooltipass/moolticute#1101]
### Expected behavior
App starts correctly after update

### Actual behavior
Error message on Startup:

"The procedure entry point "CreateEventW" could not be found in the DLL "api-ms-win-core-synch-l1-2-0.dll".

### Step by step guide to reproduce the problem
Update to Ver. 1.0 on Win7

### Moolticute Version
1.0.1

### Operating System

Windows 7

  

### Mooltipass Extension
-

### Mooltipass Device

The Mooltipass Mini BLE

**Comment by limpkin** [comment]
I'm afraid this is due to the fact that qt6 doesn't support windows 7 anymore :(

**Comment by Jan-NiklasB** [comment]
Nah... didn't known that yet, seems like I have to switch back to Qt5 in my own programms -.-

Any intention to bring out a Qt5 version of 1.0.1?

**Comment by limpkin** [comment]
I think it should actually be fairly easy to do so as we're still compiling with QT5 for some linux distributions. This would however require some work on our build system...

**Comment by limpkin** [comment]
i'll close this issue as we won't support win7 anymore
