### ISSUE TITLE
Hang when displaying "Please Approve Request On Device"

### ISSUE THREAD

**Issue by MichaelPaddon** [mooltipass/moolticute#1106]
### Expected behavior

When exporting a database using Moolticute, I expect the  "Manage Database" dialog to pop up on Mooltipass Mini BLE device.

### Actual behavior

Moolticute v1.00.1 and v1.00.0 hangs with "Please Approve Request On Device" and an endless spinner. The Mooltipass Mini BLE device acts as if it never received a request.

Moolticute v0.55.0 works as expected on the same hardware and operating system.

### Step by step guide to reproduce the problem

Download Appimage of Moolticute v1.00.1 on Debian.
Try to export a database.

The same problem occurs when built from source.

### Moolticute Version

v1.00.1 and v1.00.0

### Operating System
Debian Bullseye and Sid. 

### Mooltipass Device
The Mooltipass Mini BLE

**Comment by deXol** [comment]
@MichaelPaddon:
Can you please enable debug log on Settings tab and attach the last few daemon messages when this happens?
Is the BLE device connect with bluetooth or usb?

**Comment by MichaelPaddon** [comment]
I have updated the firmware on my Mooltipass, and now everything works as expected. It looks like versions 1.00.0 and 1.00.1 broke backward compatibility with the originally shipped firmware (0.46.3).

**Comment by limpkin** [comment]
that's an odd one..... @deXol i'm guessing you send a get_credential message? this one hasn't changed for ages....

**Comment by MichaelPaddon** [comment]
Sorry I don't have  a record of the original firmware version. It was probably the earliest shipped as I supported the Kickstarter....

**Comment by deXol** [comment]
@limpkin The only thing is sent there START_MEMORYMGMT at the beggining of export. I cannot recall there were any change with it.
I suspect the message has not arrived to the device.
