### ISSUE TITLE
Can't get into BLE Dev mode

### ISSUE THREAD

**Issue by warrenc5** [mooltipass/moolticute#1108]
This issue has a resolution.

### Expected behavior

Show the BLE menu

### Actual behavior

Pressing CTRL+SHIFT+F3 did not show the BLE menu.
Even using 

xdotool key --window 174063622 ctrl+shift+F3

### Moolticute Version

1.00.1

### Operating System
Debian - Enlightenment

### Resolution 

Enlightenment window manager has default keybinding for CTRL+SHIFT+F3 - you need to go into input -> key bindings -> CTRL+SHIFT+F3 and delete it.

Pressing CTRL+SHIFT+F3 then shows the BLE menu.

**Comment by limpkin** [comment]
@deXol should we change all shortcuts to shift+f1/f2/f3 ? :)
