### ISSUE TITLE
Moolticute does not display bundleID clearly.

### ISSUE THREAD

**Issue by warrenc5** [mooltipass/moolticute#1109]
### Expected behavior

On the about screen - show bundle Id 

### Actual behavior

New bundle update available [here.](https://www.themooltipass.com/updates/index.php?sn=0&bundlev=0)

However the link query parameter is bundlev=0 is non obvious and not presented to the user. It is also not populated by the update page when you click on the link.

It is mentioned in the manual you have bundle 0 if you were on the kickstarter.

### Step by step guide to reproduce the problem

Click the about screen when you have new updates

![shot-2022-12-12_10-55-25](https://user-images.githubusercontent.com/3395365/206936674-4999dee6-4454-49cd-b89a-211176061005.jpg)

### Moolticute Version

0.5 and 1.00.1

### Operating System
Debian

### Mooltipass Device

- The Mooltipass Mini BLE

Ps I love my mooltipass so much - Ta!

**Comment by limpkin** [comment]
@deXol let's show the available bundle number in the notification
thanks @warrenc5 :)

**Comment by deXol** [comment]
> @deXol let's show the available bundle number in the notification thanks @warrenc5 :)

Implemented in https://github.com/mooltipass/moolticute/pull/1112
