### ISSUE TITLE
Field for additional information

### ISSUE THREAD

**Issue by EugeneRymarev** [mooltipass/moolticute#1111]
### Missing function
Additional field for account comment.

### Justification
Some sites require comments to be saved, such as account recovery codes, 2FA rescue codes, or something else.

### Workarounds
Creating Notes is inconvenient, since it is a different entity and needs to be looked for in a completely different place.

https://github.com/mooltipass/minible/issues/365

**Comment by limpkin** [comment]
hello there! we do have a "description" field that could maybe do the trick?

**Comment by EugeneRymarev** [comment]
> description

@limpkin, Unfortunately, this field is too short.

**Comment by limpkin** [comment]
I'll close that one as this really is a minible issue... could you create one on the other repo?

**Comment by EugeneRymarev** [comment]
@limpkin, you mean minible repo?

**Comment by limpkin** [comment]
yes

**Comment by EugeneRymarev** [comment]
@limpkin, already opened https://github.com/mooltipass/minible/issues/365
