### ISSUE TITLE
Incorrect operation of the notification about the discharge of the battery below 30%

### ISSUE THREAD

**Issue by EugeneRymarev** [mooltipass/moolticute#1114]
![image](https://user-images.githubusercontent.com/6260309/208726873-9a5155a9-e1ed-4cd4-9cb7-7bd60254307f.png)
### Expected behavior
Correct operation of the notification about the battery discharge below 30%

### Actual behavior
Incorrect operation of the notification about the discharge of the battery below 30%

### Step by step guide to reproduce the problem
?

### Moolticute Version
1.00.1

### Operating System
- Windows 11 Pro 22H2

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
@EugeneRymarev is this still happening on 1.01.0?

**Comment by EugeneRymarev** [comment]
@limpkin, It doesn't seem to happen anymore, but I'm not sure.
