### ISSUE TITLE
Increase of max. file size

### ISSUE THREAD

**Issue by Jan-NiklasB** [mooltipass/moolticute#1115]
### Missing feature
Increased file size for storage on the miniBLE

### Justification
I want to save different certificates for authentication on the miniBLE, for example the German tax office requires every person to have a certificate for authentication when sending tax data.
Since this certificate is very important and hard to get reissued if lost, the miniBLE would be a perfect place to store.
The problem is that the certificate is between 10 and 20 kB in size, while the miniBLE supports ~10kB max.
So it would be nice if the file size could be increased on the cost of max. files.

### Workarounds
Non known to me.

**Comment by rastagraffix** [comment]
Jan-NiklasB writes:

> The problem is that the certificate is between 10 and 20 kB in size,
> while the miniBLE supports ~10kB max.  So it would be nice if the
> file size could be increased on the cost of max. files.

I have a 65K text file full of auth info for work servers
that I would like to store.  The app and firmware shouldn't
be nannying us over the size of files we want to put on the
device. 100 1k files, 1 100K file, it's the same thing
as for how much space it uses.

These restrictions should be removed.  Let it error out
when it runs out of space, and not before.

--lyndon

**Comment by limpkin** [comment]
@rastagraffix : the reason why we don't allow large files is mainly because of novice users: we don't want to give the impression that our device is meant to be used as a Mass Storage Device, but rather as an authenticator with the "added bonus" of storing small files. When files start to be very large, the transfer speed starts to be an issue and novice users may complain that they can't store their credentials anymore...

**Comment by Jan-NiklasB** [comment]
This could maybe be a feature one can enable in the settings with an info message.

So per default filesize is limited but can be set 'unlimited' in the settings

Am 29. Dezember 2022 09:21:09 MEZ schrieb Mathieu ***@***.***>:
>@rastagraffix : the reason why we don't allow large files is mainly because of novice users: we don't want to give the impression that our device is meant to be used as a Mass Storage Device, but rather as an authenticator with the "added bonus" of storing small files. When files start to be very large, the transfer speed starts to be an issue and novice users may complain that they can't store their credentials anymore...
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mooltipass/moolticute/issues/1115#issuecomment-1367148629
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
