### ISSUE TITLE
Inquiry: Moolticute Keyboard Layout

### ISSUE THREAD

**Issue by meta-space** [mooltipass/moolticute#1119]
Hi all

The Moolticute user manual states the following about the keyboard output: "For the Mooltipass to operate properly, it is important that you use the Device Settings tab to select
the keyboard layout you are using. [...]"

It seems that my native layout (Swiss-German) is currently not yet supported. All of my passwords are auto generated and many contain special characters that are not output correctly when using the keyboard output. 

Is it possible to add more keymappings to the Moolticute?
If somebody points me to docs or relevant code section in the repo, I'd be glad to contribute the mapping.

If it is not possible to add keyboard layouts, the only alternative I see would be to avoid troublesome special characters in my passwords and pick a reasonably similar keyboard layout to mine (probably German).

**Comment by limpkin** [comment]
Hello! You may use the swiss-french one :)

**Comment by meta-space** [comment]
Thanks for the quick reply. I'll give it a try
