### ISSUE TITLE
BLE issue, export db/integrity check fails

### ISSUE THREAD

**Issue by raoulh** [mooltipass/moolticute#1120]
### Expected behavior
Exporting the db correctly and integrity check should end successfully

### Actual behavior
Both actions fails in the middle

### Moolticute Version
1.00.1 + latest bundle on mini ble

### Operating System
Not relevant

### Mooltipass Extension
Not relevant

### Mooltipass Device
- The Mooltipass Mini BLE

Both actions start correctly by asking to enter MMM. It starts load some nodes and then fails.

Attached the log files from both actions.
[mp_ble_export_failed.log](https://github.com/mooltipass/moolticute/files/10380133/mp_ble_export_failed.log)
[mp_ble_integrity_failed.log](https://github.com/mooltipass/moolticute/files/10380134/mp_ble_integrity_failed.log)

Both actions are failing after this:
```
"PLEASE_RETRY (0x0002)"  received, resending command  "READ_FLASH_NODE (0x0102)"
```

**Comment by limpkin** [comment]
@raoulh I now have a little BW... is this still happening on 1.01.0?

**Comment by limpkin** [comment]
pinging @raoulh

**Comment by raoulh** [comment]
It's working now with 1.01.0, thanks
