### ISSUE TITLE
Battery indicator doesn't go beyond 90%

### ISSUE THREAD

**Issue by smallouki** [mooltipass/moolticute#1122]
### Expected behavior
Battery gets fully charged, or the proper value is shown in moolticute

### Actual behavior
The battery indicator in the moolticute app only shows 90% no matter how long the device is plugged in. 

I did a battery reconditioning which crashed the device although it had finished successfully according to moolticute. After a reset the device is working again with this side effect. 

### Step by step guide to reproduce the problem
1. Open moolticute
2. Connect the device
3. Check the battery indicator on the top right

### Moolticute Version
1.0.0.1

### Operating System
Mention if you are using either:
- MacOS   Ventura 13.0.1 (22A400)
  
### Mooltipass Device

- The Mooltipass Mini BLE

![screenshot-2](https://user-images.githubusercontent.com/4653505/212060875-a4fadcca-0ed7-42f6-9cfb-259384db8447.jpg)

**Comment by limpkin** [comment]
that may actually happen due to our battery charging algorithm :). When the battery has discharged only little, we don't allow charging to 100% again.

**Comment by smallouki** [comment]
Ok cool. Thanks for clarifying. Then I guess I can close this.
