### ISSUE TITLE
Testing releases are not marked as pre-releases

### ISSUE THREAD

**Issue by VincentVanlaer** [mooltipass/moolticute#1126]
Github has the possibility to mark pre-releases, which I think would be ideal to use for the `-testing` releases. In this way the intent of the releases is communicated more clearly. This should be as easy as clicking the `This is a pre-release` when creating the release.

An example from another project: https://github.com/grpc/grpc/releases/tag/v1.52.0-pre1

**Comment by limpkin** [comment]
ohh thanks for the tip! will do from now on :)
