### ISSUE TITLE
Access refused for a note after import

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#1136]
### Expected behavior
After exporting a db from one BLE and importing it into another (as a backup)  I should be able to access the note that I created, but I cannot.

### Actual behavior
After importing onto the second BLE I can see the note in the list of notes (about 12 of them), but I cannot open it.
Message` Note Fetch Denied`
In fact, I can only access the first 6 notes (after confirming on my BLE) but none after that (sorted alphabetically). 

### Step by step guide to reproduce the problem
1. Export a db with more than 6 notes, and one freshly created note which is not on the 2nd BLE.
2. Import the db into the 2nd BLE
3. Try to access the 7th note. Instead of a popup asking for BLE confirmation, I receive an access denied message.

I can still access the note on the 1st BLE.

### Moolticute Version
MC 1.00.1
BLE Bundle 12

### Operating System

- Windows 10 64 bit

### Mooltipass Device

- The Mooltipass Mini BLE latest firmware - all connections USB not Bluetooth.
I switched on the developer log but don't know where to find it.

**Comment by alanrick** [comment]
I can't test right now without risking losing my data. Was this fixed with release 1.01.0 "[Fetch notes after import](https://github.com/mooltipass/moolticute/commit/2124019c616085fdb8a278f84df00216bb8eed36)" ?

**Comment by limpkin** [comment]
oh yes.. this should have been closed. sorry about that :/
