### ISSUE TITLE
Developer Tab (CTRL+SHIFT+F3) inaccessable on latest appimage

### ISSUE THREAD

**Issue by ryokimball** [mooltipass/moolticute#1142]
### Expected behavior
developer tab appears & navigated to after pressing CTRL+SHIFT+F3
### Actual behavior
Nothing after pressing chord
### Step by step guide to reproduce the problem
on latest appimage version, press CTRL+SHIFT+F3)
### Moolticute Version
v1.01.0
### Operating System
Tried on two machines
- Ubuntu 22.04.1
- "SteamOS" Linux steamdeck 5.13.0-valve36-1-neptune 

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
I should have pushed the updated user manual... the shortcut got changed to shift-f3 :)

**Comment by My1** [comment]
all the Ctrl+shift+Fx shortcuts seem shift only now too.
aka shift F1 for SSH (note that program texts are affected in the advanced tab)
and Shift F2 for Advanced

**Comment by My1** [comment]
https://github.com/mooltipass/moolticute/blob/master/src/MainWindow.ui#L4972
this might need changing

**Comment by limpkin** [comment]
good catch! tagging @deXol

**Comment by My1** [comment]
not sure if there are similar mentions in the program anywhere else currently
