### ISSUE TITLE
Moolticute doesn't recognize when the key card is inserted

### ISSUE THREAD

**Issue by smallouki** [mooltipass/moolticute#1144]
### Expected behavior
After inserting the key card into the mooltipass the moolticute tool should unlock the ux. 

### Actual behavior
It shows the message "Security card is missing" and the data cannot be accessed. Removing and re-inserting the security card has no effect. The hardware is properly unlocked and can be used.

After restarting the moolticute daemon it works again. 

### Step by step guide to reproduce the problem
Remove the key card and re-insert. Check the moolticute UX. 

### Moolticute Version
1.01.0

### Operating System
Mention if you are using either:
- MacOS  
  

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
Could you attach the daemon logs here when this happens?

**Comment by limpkin** [comment]
@smallouki ?

**Comment by smallouki** [comment]
I got an exchange for the hardware from Mathieu. This did not happen so far.
