### ISSUE TITLE
"Duplicate service detected during import" when importing backup

### ISSUE THREAD

**Issue by robbiebyrd** [mooltipass/moolticute#1148]
My Mooltipass Mini BLE began hanging when opening a credential. I deleted all credentials from the device, and attempted a restore from backup.

During the first restore from the latest backup, the Mooltipass and Moolticute hung. I restarted both the computer and the mootlipass device. I then attempted to import multiple versions of my Mootlipass.bin backup file.

I've used multiple local Time Machine backups of the Mooltipass.bin file, even back several months; however, none of the backups work; I get the same "duplicate service" error message.

### Expected behavior

Importing a Moolticute backup file should restore credentials to the device.

### Actual behavior

After selecting the Mooltipass.bin backup file again, Moolticute returns the following error: "Duplicate service detected during import, please contact support".

### Step by step guide to reproduce the problem

1. Open the Synchronization Tab
2. Select "Import from File" in "Import Database from File"
3. Select a Mooltipass.bin backup
4. Backup is not successfully restored to the mooltipass device.

### Moolticute Version

v 1.01.0

### Operating System

MacOS Ventura 13.2 (22D49)

### Mooltipass Device
- The Mooltipass Mini BLE, Bundle v. 12, Aux MCU 0.73, Main MCU 0.84

**Comment by limpkin** [comment]
@deXol could you update the code to remove that check, now that we've identified the root cause of that issue?

**Comment by limpkin** [comment]
@robbiebyrd could you give a go at https://betas.themooltipass.com/v1.01.3-testing/ ? :)
dmg should be uploaded any time now :)

**Comment by barathrm** [comment]
Is this related to https://github.com/mooltipass/moolticute/issues/1127?

> now that we've identified the root cause of that issue?
What is the root cause?

**Comment by robbiebyrd** [comment]
@limpkin That fixed it! Thank you so much!

**Comment by limpkin** [comment]
@barathrm I don't think it is
@robbiebyrd awesome!
