### ISSUE TITLE
Changing credentials in management mode - Wrong JSON formated credential list

### ISSUE THREAD

**Issue by warrenc5** [mooltipass/moolticute#1157]
### Expected behavior
Login Email address updated

### Actual behavior

Couldn't save credentials, please contact the support team with moolticute's log
{"data":{"error_message":"Wrong JSON formated credential list","failed":true},"msg":"set_credentials"} 
Device stuck in "Database Management" 
Have to unplug and replug to use.

### Step by step guide to reproduce the problem
Enter credentials management mode
Select 

### Operating System
Mention if you are using either:

Why can't I copy the details from the about screen as text? 
Debian base
Version 1.01.0 - but was also happening with the previous version.
Device Aux 0.73 Main 0.84

### Mooltipass Device
Mention if you are using either:

- The Mooltipass Mini BLE

Any assistance highly appreciated - ta.

**Comment by limpkin** [comment]
could you clarify that step by step guide? I'm really not sure what's happening there...

**Comment by warrenc5** [comment]
Sorry my mistake.

Plug the device with usb and unlock it.

1. On moolticute - "Enter Credentials Management Mode" ( confirm & enter pin on device ) 
2. All Services/Websites are loaded
3. Credentials Tab
4. Select Service or Website
5. Select password - press the eye option.
6. Approve on device 
7. Modify password (manually or with the generator doesn't matter)
8. Select confirm changes
9. Select "save all changes"
10. see error "Couldn't save credentials, please contact the support team with moolticute's log" 
11. Press OK
12. Moolticute returns back to Credentials Tab with option to "Enter Credentials Management Mode"
13. Device shows "Database Management"
14. Pressing button on device is ignored.
15. Unplug the device - screen goes blank/black/unpowered
16. Press button once on device to see pin screen.

If I hit confirm changes at step 8 and then 

1. navigate away to another service/website in the service/website list 
2. navigate back to the service/website I have changed
3. Select the password - press the eye option
4. Approve on the device 

The old/original password I supplied there remains - where I would expect the new password to show (in the edit session)

Hope this is clearer :)

**Comment by warrenc5** [comment]
It still occurs - it the newly built version of moolticute [v1.01.5-testing](https://github.com/mooltipass/moolticute/releases/tag/v1.01.5-testing) 

This is the log and this is the DATA json (I have removed anything thing I considered sensitive) 

But the structure is still there..

[moolticute-json.txt](https://github.com/mooltipass/moolticute/files/11308729/moolticute-json.txt)
[moolticute-log.txt](https://github.com/mooltipass/moolticute/files/11308730/moolticute-log.txt)

Is there anything that can be done? should I maybe backup and reset the device and restore?

**Comment by limpkin** [comment]
thanks for the debug information @warrenc5 ! sorry we're taking so long to get to the bottom of this.
I'm seeing very odd things in your logs... could you perform an integrity check?
what's the platform you're running? thanks

**Comment by warrenc5** [comment]
By integrity check do you mean "security challenge" email serial number/order number??

uname -a
Linux leet 6.1.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29) x86_64 GNU/Linux
cat /etc/issue.net
Debian GNU/Linux bookworm/sid

I'm a average power user, what's the oddness - I did take out the DATA json to a new file to format it for you.

**Comment by limpkin** [comment]
In the "synchronization tab" you have a "perform integrity check" button :)

**Comment by warrenc5** [comment]
Memory integrity check done successfully!
231 of 1988 credential slots used.

Then I did an export to file and an import from file.

Now I can update my passwords in "Credentials Management Mode" without the error occurring.

If there is no further troubleshooting required - I think you can close this issue. 

Thank you.

**Comment by limpkin** [comment]
Hmm, still odd that this happened... but glad it got resolved :)
