### ISSUE TITLE
Future Roadmap

### ISSUE THREAD

**Issue by gisturbance** [mooltipass/moolticute#1169]
### Missing feature
A roadmap to show the current state and where the project is leading to.

Does the project need more developers or funds? What are the future goals?

### Justification
It's been a while since the last update and there is zero information on what is going on with the project. We are creating issues for feature requests and asked to give thumbs-up but there's no indication on when or if they might be considered.

Of course, everything takes time, but it's important to keep the community informed.

**Comment by limpkin** [comment]
You're absolutely right. What open source project doesn't need more developers or funds :).
It's quite a shame that we can't add a wiki at the org level... that would be the perfect place to advertise this.

**Comment by gisturbance** [comment]
Even though organization-level wikis aren't available, public/private [readme](https://docs.github.com/de/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme) are.
There should be plenty of space and for more, there's still the projects website.

**Comment by limpkin** [comment]
agreed. thanks for flagging this to us.

**Comment by limpkin** [comment]
added here :) 
https://github.com/mooltipass
