### ISSUE TITLE
Password generator slider has maximum length of 31

### ISSUE THREAD

**Issue by hijackeel** [mooltipass/moolticute#1174]
### Expected behavior
Password length slider in random generator should go up to maximum of 64.

### Actual behavior
Password length slider in generator goes up to maximum of 31.

### Step by step guide to reproduce the problem
1. Open Moolticute.
2. Go to Credentials tab.
3. Click on Random Password icon in Password field.
4. Try to make length slider greater than 31.

### Moolticute Version
Latest commit at time of writing: c4939e599487749ad47d8d5afb1dc2862d73bc89

### Operating System
Gentoo Linux

**Comment by warrenc5** [comment]
Funnily I was just encountering the same edge case when adding an IKE pre shared key for IPSEC/L2TP

Seems the protocol maximum is 127 however some Cisco supports 64 and some routers only support 32 characters.

I kind of agree 127 would be a sensible limit to be supported on the Mool - after that point you would want probably want to use a different security mechanism like DH keys no?
