### ISSUE TITLE
Feature request: copy generated password in MMM

### ISSUE THREAD

**Issue by warrenc5** [mooltipass/moolticute#1176]
Copy new password to clipboard in management mode.

### Justification
When modifying a credential in management mode using the generator - the use case is typically
1. generate the password 
2. test the password in the website for all their stupid validation rules ( no Ms in passwords generated on Mondays :)
3. save the password to the device.

Unfortunately I can see the newly generated password but can't select it to copy it into the x buffer/clipboard.
Secondly if I have not pressed the "eye" show and then press fill to see the new password I only see ********* as I haven't pressed the eye and approved on the device to send the old password.

![moolticute](https://github.com/mooltipass/moolticute/assets/3395365/c2c5f543-3475-4700-b6e1-bddd2cd7b125)

### Workarounds

1. press the eye to see the old password
2. generate a new password
3. press fill
4. copy the password from the password text box
5. try the new password in the stupid website ( actually a router configuration page so can't really use the browser plugin here)
6. save the password if it works or generate a new one or discard by clicking cancel in the moolticute app.

I know it seems like a little thing here. But the problem is it requires the user to perform a mental chess game to get it in. Where the use case scenario could be more flowable here.

**Comment by limpkin** [comment]
hello!
stupid question: why don't you use the extension password generation? :)

**Comment by warrenc5** [comment]
Unfort - Limpkin in this situation - I can't - as it's on a routers web management console - that's not even a password text field. + it has stupid password validation rules - so not every generated password works. :(

At the minimum I would just want to select that new generated password text from moolticute to copy it into the mouse/xbuffer (before adding/changing it on the service account). 

Forgive my basic UI terms - At the moment it seems to be an 'unselectable label' - where as I really need it as an 'uneditable text field'.

Ps. There's no such thing as stupid questions - only stupid people :) :) :)
