### ISSUE TITLE
Can't export database, hangs in step "Please Approve Request On Device"

### ISSUE THREAD

**Issue by kalaksi** [mooltipass/moolticute#1181]
### Expected behavior
This is the same issue as described here: https://github.com/mooltipass/moolticute/issues/1106
I expected the approval request to appear on Mini BLE.

### Actual behavior
Nothing happens on Mini BLE's side and I can continue using it. Moolticute just sits waiting for approval.
Mini BLE doesn't seem to receive the approval request somehow (or maybe it's invalid).

Moolticute 0.55.0 AppImage seems to work fine.

### Step by step guide to reproduce the problem
1. start moolticute.
2. Connect mooltipass with USB. Moolticute seems to receive current device settings.
3. Try to export database.

### Moolticute Version
v1.01.0 (from PPA)

### Operating System
Ubuntu 22.04.2 LTS

### Mooltipass Device
The Mooltipass Mini BLE (bundle v0)

### Attachments
[moolticute-daemon.log.txt](https://github.com/mooltipass/moolticute/files/12064920/moolticute-daemon.log.txt)

**Comment by limpkin** [comment]
hello!
That's quite the old bundle you have there... could you update to v12 using www.themooltipass.com/updates ?

**Comment by kalaksi** [comment]
I actually tried that using 1.01, but it did something similar and never could get the firmware uploaded. Mooltipass didn't show anything being uploaded. I'll try 0.55 later.

**Comment by kalaksi** [comment]
How would I do the update with 0.55? Shift-F3 doesn't seem to be working

**Comment by kalaksi** [comment]
Ah, never mind, found from an older issue that it's shift-ctrl-F3 in moolticute 0.55. Updated successfully and now 1.01 seems to be working correctly.
