### ISSUE TITLE
Moolticute Hangs if Monitored Database Backup File Isn't Present

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#1184]
### Expected behavior
When Database Backup Monitoring is enabled, if a local Mooltipass database dump can't be found an error explaining the problem should appear.

### Actual behavior
If the configured database dump can't be found, Moolticute hangs as soon as the Mooltipass is connected and unlocks - entirely unresponsive, no errors in the log, can't be closed short of `kill moolticute`.

### Step by step guide to reproduce the problem

1. Dump the database.
2. Configure Database Backup Monitoring, point it to the database.
3. Disconnect your Mooltipass.
4. Make the backup database file inaccessible (in my case, it was in a Keybase directory - and I'd closed Keybase).
5. Reconnect and unlock your Mooltipass.
6. Watch as Moolticute hangs.

### Moolticute Version
1.01.5-testing (also tested on the 1.01.0 AppImage, same).

### Operating System
Ubuntu 20.04 64-bit.

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by deXol** [comment]
Hello @ghalfacree,
Unfortunately I was not able to reproduce the issue, can you please attach daemon log when this issue occurs?

**Comment by limpkin** [comment]
@ghalfacree ?

**Comment by ghalfacree** [comment]
Sorry, I've been super busy and this had dropped off my radar.

Testing with the current beta release - v1.02.19-testing - reveals the following:

- Renamed the synchronised dump: no error (but also no "credentials on device are newer" warning or prompt to create a fresh dump.
- Renamed the *directory* the dump is in: same, no error.
- Created a new tmpfs mount point, put the dump in there, unmounted it: same, no error.
- Opened Keybase, put the dump in /keybase/private/ghalfacree, closed Keybase: no error.

Given that last test-case is literally what was killing it before, I'd say either a Moolticute update or a Keybase update has fixed the problem - or it was Just One Of Those Things and has gone away on its own!
