### ISSUE TITLE
Can't start on Apple Silicon (Apple Silicon support status)

### ISSUE THREAD

**Issue by ai212983** [mooltipass/moolticute#1186]
### Expected behavior
Moolticute.app runs without problem on Apple Silicon chips

### Actual behavior
Moolticute.app fails with
```
❯ open /Applications/Moolticute.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10669 "(null)" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}
```

### Step by step guide to reproduce the problem
1. Download `.dmg` from https://www.themooltipass.com/setup/
2. Copy `Moolticute.app` to `Applications` folder.
3. Run `open /Applications/Moolticute.app`

### Moolticute Version
Not sure, can't start it

### Operating System
MacOS  Ventura 13.5.1, Apple Silicon M2 Max
  
### Mooltipass Device
The Mooltipass Mini BLE

I know there's an open ticket for [M1 support](https://github.com/mooltipass/moolticute/issues/929), but there are also comments implying Moolticute is [working](https://github.com/mooltipass/moolticute/issues/970#issue-1106119940) on [M1 chips](https://github.com/mooltipass/moolticute/issues/963#issuecomment-1013819858).

In case Apple Silicon is not supported, IMO it should be mentioned explicitly on Moolticute website and in the docs.

EDIT: It seems to work with Rosetta, but Rosetta is not installed/enabled on Mac OS by default. I still thinks it should be mentioned on the site and in the docs.

**Comment by limpkin** [comment]
You're right! I've updated our main website and documentation (section III A) to reflect that.
feel free to close this issue if you find this acceptable.

**Comment by ai212983** [comment]
I can't find mention of Rosetta nowhere near "Apple" or "MacOS" on the web site. "General" section for compatibility issues is not obvious. 

I would expect mentioning Rosetta on `/setup` page flow, not buried somewhere deep in docs pdf.

**Comment by ai212983** [comment]
Imagine someone (like me) downloading and installing Moolticute only to realize it doesn't work.
Searching in the page for "MacOS". Nothing. For "Apple" - nothing. Trying to re-download from `/setup` - nothing on Setup page either. Searching for "compatibility" - nothing. Opening PDF, searching for "MacOS" - nothing again.

The only option is either read every bit of lengthy documentation PDF or to suggest the problem is with the chip, not OS (this is not trivial for most users) and search documentation for "Apple Silicon".

Not really easy way imo.

**Comment by limpkin** [comment]
It was in the FAQ section, I now made the dedicated section's title clearer and should show up on ctrl-f... can you confirm?

**Comment by ai212983** [comment]
@limpkin Yes, it is way better now, I guess.
Still missing in `/setup` flow (sigh) but can be found more easily.

Thank you for all the effort, closing this ticket now.

**Comment by limpkin** [comment]
I need to think about it a bit more how to make it obvious in the setup flow without disturbing the layout...
