### ISSUE TITLE
Moolticut use tcp to lochost

### ISSUE THREAD

**Issue by Knoxi-Code** [mooltipass/moolticute#1192]
My moolticut use tcp protokoll over port 30035 to lochost 127.0.0.1,
is this normal ? 
I have never seen that before. 

### Operating System
Mention if you are using either:
Linux 11 KDE
  
### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

thanks :)

**Comment by limpkin** [comment]
that is indeed normal! that's what we use for communication between moolticute daemon and extensions :)
