### ISSUE TITLE
Synchronizing the same database to Mini and Mini BLE

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/moolticute#1195]
I believe this was closed as completed a while ago but the problem persists.

If I export a database from the BLE and attempt to import it into the Mini, I get  'Selected file is a BLE backup' error. If I have a computer with a mini, and another computer with a BLE sync with the same database, I get a similar problem. As a test, I create junk credentials on the BLE, have it save to the shared database. The computer with the Mini gets a pop up asking about synchronizing. I say yes, but no symchronization, or error pops up.

**Comment by limpkin** [comment]
Import from BLE to Mini is indeed not implemented. BLE to Mini should work.
It's a shame you didn't follow the github issue template. Could you give us a list of steps to reproduce the Mini to BLE issue?
