### ISSUE TITLE
Device Displays "#011 Contact Support"

### ISSUE THREAD

**Issue by zmcfate** [mooltipass/moolticute#1198]
### Expected behavior

No error messages for no clear reason.

### Actual behavior

Device Displays "#011 Contact Support".

This is me, contacting support. Hi!

### Step by step guide to reproduce the problem

Wait. Watch.

### Moolticute Version

1.00.1

### Operating System
Mention if you are using either:
- MacOS  (Ventura 13.6)
  
### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by zmcfate** [comment]
Also, the battery will no longer hold a charge for any length of time. I can still use it as a USB device. Any ideas?

**Comment by limpkin** [comment]
Hello!
Could you:
- hard reboot the device by unplugging the USB cable, pressing the wheel for 30 seconds, plugging back the USB cable
- update your device to bundle v13 using https://beta-updates.themooltipass.com/
- switch your moolticute to the latest beta version on https://betas.themooltipass.com/
- perform a battery reconditioning procedure with the "continue until..." option selected

**Comment by zmcfate** [comment]
Okay, I will try these things today, thanks.

**Comment by zmcfate** [comment]
Also, I'm not sure which file represents the latest beta of Moolticute at the URL provided. There's no .dmg or .img file, and I don't see anything that looks like a Mac OS installer file. Help?

**Comment by limpkin** [comment]
- you shouldn't click on the img file, you should follow this guide: https://mooltipass.github.io/minible/updating_your_device
- oh I didn't know you were on macOS... in that case, could you update to moolticute 1.02 on https://github.com/mooltipass/moolticute/releases/download/v1.02.0/Moolticute-v1.02.0.dmg ? you'll need to manually perform battery reconditioning procedures until you get an elapsed time of more than 1000 seconds...

**Comment by zmcfate** [comment]
Okay, I'll try that, then.

**Comment by zmcfate** [comment]
Oh, I forgot the secret key combo to bring up the tab to recondition the battery....

**Comment by zmcfate** [comment]
Okay, apparently good news: the reconditioning completed, displaying a figure of "0.817 seconds" (?), but it seems to be holding a charge now.

**Comment by limpkin** [comment]
you should let it run until you get 2500+ seconds (in theory it's what the keep reconditioning tick box should do)

**Comment by zmcfate** [comment]
It didn't provide the modal dialog with the checkbox checked. I could run an additional single reconditioning pass now to see what I get, if you think that makes sense.

**Comment by zmcfate** [comment]
Battery had gone down to 10% overnight without having done much with the unit that would drain it, so I'm doing a single reconditioning cycle now to see what it reports. If it's under 2500 seconds, I'll rerun it.

**Comment by zmcfate** [comment]
Okay, I've run three reconditioning cycles.

Run 1: 438.33 seconds
Run 2: 584.945 seconds
Run 3: 3378.51 seconds

Hopefully it'll hold a charge for longer now.

**Comment by limpkin** [comment]
oh that's actually perfect!
