### ISSUE TITLE
Buttons to switch on developer tab and advanced tab in moolticute

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#1200]
### Missing feature
Buttons in the _settings tab_ to enable the developer tab and the advanced tab. The UI should be similar to the _"Manage your password profiles"_ button.

### Justification
There are no buttons in the moolticute device settings to enable the developer tab and advanced tab in moolticute.
Instead, I have to download the instructions, scan the instructions, and finally google how to perform the keystroke on a MacBook. In fact even then I have to use trial-and-error.
_"If the shortcut doesn’t work on MacOS, you may go to system preferences -> keyboard and disable the special functionality..."_

This is very awkward and time-consuming.
Anyone can use google, so making these tabs so innacessable doesn't improve the security in any way. In fact, for security reasons you may want users to update the firmware without jumping through hoops to get there.

### Workarounds
The workaround as described above is clunky and primitive. It is also unnecessary because even understanding the basic settings in moolticute requires some techy background.

**Comment by limpkin** [comment]
hello,
for macOS I think this is not needed as we simplified the shortcut for shift-f2 no? :)

**Comment by alanrick** [comment]
sadly, not on my MacBook :(
Three keys. Impossible to press without taking my hand off the keyboard. And I have combinations of 4 keys (Shift/globe/control/option/command) to choose between. I rarely use this feature so I have to search every time, which is pointless.

**Comment by limpkin** [comment]
can you confirm you're running the latest moolticute? it should just be shift-f2 no?

**Comment by alanrick** [comment]
I'm using the latest version (v1.03.0)
The three keys
1. F2
2. Shift
3. fn/🌐

But irrespective of the number of keys. Why should anyone have to google or refer to the manual instead of just enabling the tab with a button in the UI? Especially as this is a function which is important but rarely used.
