### ISSUE TITLE
Deamon-Service

### ISSUE THREAD

**Issue by Knoxi-Code** [mooltipass/moolticute#1201]
Hello i have a problem with the Deamon-Service,

the service is no longer available because my firewall block it.
I can see that the demon communicate over lochost from ip ::1/30035 to ::1 /56132, but the destination port change ervery i restart the demon or the system. 
For people like me they only open few ports in / out, is the dynamic destination port a problem, can you change it to a static destination port  or ist this a bug ? 

Best regards:) 

- Debian 12
- Mooltipass Mini BLE

**Comment by limpkin** [comment]
@deXol could you have a look? :)

**Comment by Knoxi-Code** [comment]
Wireshark shows me a TCP Reset-Flag form lochost to lochost, i deactivate the firewall for testing, restart the service but nothing help. 

![Screenshot_20231124_160602](https://github.com/mooltipass/moolticute/assets/115695509/2e59c681-d109-426b-aafa-c0c24771f3e4)

**Comment by limpkin** [comment]
@Knoxi-Code I'm a little confused here, the daemon should have a fixed port, and the clients will connect to it from a random port no?

**Comment by Knoxi-Code** [comment]
Okey im confused too, also the daemon have a fix port "30035" and the client jump arround, is this normal behave ?

**Comment by Knoxi-Code** [comment]
Yea its work again :)
