### ISSUE TITLE
multiple password changes not reflected in the credential list

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#1217]
### Expected behavior
When I make a password change to two logins  I should be able to navigate between them and verify them before updating the BLE database. 

### Actual behavior
After changing the password for the 1st login, and then the password for the 2nd login, when I navigate back to the first login, I should see the changed first password not the original password.

### Step by step guide to reproduce the problem
E.g. 
Service  "_Router_". 
Login 1 "_user_", password "_1pass_"
Login 2 "admin", password "_2pass_"

1. Navigate to credentials, service _Router_ ,
2. Navigate to login, _user_
3.   Change the password to _1pass1_ and press -Confirm changes-
4. Navigate to login, _admin_
3.   Change the password to _2pass2_ and press -Confirm changes-
4. Now, Navigate back to the _user_ login and view the password. It is not _1pass1_ as expected but _1pass_ (the old password)

And the date modified date is not changed either.
If I now select <Save all changes> and reload in fact the password has been changed (to 1pass1). But this is misleading because when I checked it before pressing Save all changes this value is not the value that is saved in the database.

It also inconsistent with adding a service while in the credentials mode because this service DOES appear in the list of credentials even though it will be lost if I don't press <Save all changes>
E.g. 
1. Add the Service Router, Login User2, password 3pass.
2. This is appears in the list of services correctly (even though it has not been saved to the BLE)

It is also inconsistent with deleting a credential which likewise is immediately reflected in the list even though it has not been saved back to the BLE.

### Moolticute Version
v1.03.0

### Operating System
Mention if you are using either:
- MacOS   14.4.1
  
Other operating systems are not supported.

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

(updated as I'd inadvertently added formatting)

**Comment by limpkin** [comment]
ohhhh that's a very nice find! 
thanks @alanrick
