### ISSUE TITLE
Moolticute AppImage request root access

### ISSUE THREAD

**Issue by janemba** [mooltipass/moolticute#1228]
### Expected behavior

- Moolticute application open without asking for root password.

### Actual behavior

- When starting moolticute from terminal a root access is requested.

### Step by step guide to reproduce the problem

- Step 1: `$ chmod +x Moolticute-v1.03.0-x86_64.AppImage`
- Step 2: 
```
$ ./Moolticute-v1.03.0-x86_64.AppImage
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/env DISPLAY=:1 XAUTHORITY= sh' as the super user
Authenticating as: root
Password: 
```
### Moolticute Version

- 1.03.0

### Operating System
Mention if you are using either:
- Slackware 15
  
Other operating systems are not supported.

### Mooltipass Extension

- None

### Mooltipass Device

- Mooltipass Mini BLE

**Comment by limpkin** [comment]
Hello!
I'm fairly sure it's to install the udev rules :)

**Comment by janemba** [comment]
No no no, that's the first thing I did.

**Comment by limpkin** [comment]
then why did you close the issue? :)

**Comment by janemba** [comment]
Well, I remember having the same issue before but I don't know how did I solve it. So I will go with the source.

**Comment by limpkin** [comment]
@deXol would you remember why?
