### ISSUE TITLE
The Future of Mooltipass

### ISSUE THREAD

**Issue by gisturbance** [mooltipass/moolticute#1246]
It's been a while since the last updates for Mini BLE and Moolticute. I've heard the team is already working on a new device.

The community was asked to upvote feature requests - there's 8 requests with 10 or more thumbs up for the Mini BLE, though not as many for Moolticute. Will we ever get to use FIDO ed25519-sk resident keys?

Mini BLE upvotes: https://github.com/mooltipass/minible/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
Moolticute upvotes: https://github.com/mooltipass/moolticute/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

What's the status of the projects? What's next to expect?
Please keep us updated.

**Comment by limpkin** [comment]
Hello there!
It has been a while indeed :), we're indeed working on a newer device!
I personally do want to implement resident keys, and the new secure element on our newer device surely opens lots of doors... but there's still work I'm afraid.
I'm personally aiming for a call for beta testers for our newer device in perhaps 3 months!

**Comment by gisturbance** [comment]
> aiming for a call for beta testers for our newer device in perhaps 3 months!

Certainly hoping you're acknowledging the feature requests - besides security - especially in regards to the UI, since the current device is definitely lacking some usability.

I would even go as far to say, these requests [and the current features] to be the **base** of the new devices feature set.

A little bit more transparency wouldn't hurt.

**Comment by limpkin** [comment]
Our whole ecosystem is open source, I do hope we tick the transparency box.
Please correct me if I'm wrong, but I don't know many open source projects that publicly advertise their internal development team day-to-day work. We however do have an IRC channel were discussions happen.
Please also accept that some features (mostly UI-wise) may please some while displeasing others... after all, we're all different.
Finally, as previously mentioned the Mooltipass is open-source, and pull-requests are welcome :)

**Comment by gisturbance** [comment]
Being open source does not justify the lack of general project status updates though.
