### ISSUE TITLE
0.9.8 beta on mac does not allow you to save passwords only

### ISSUE THREAD

**Issue by j4jonathan** [mooltipass/moolticute#131]
In the case of encrypted hard drives where there is no username required, only an encryption passphrase, moolticute will not allow you to save until a password is entered whereas the original mooltipass app does.

**Comment by limpkin** [comment]
do you mean that MC won't allow you to save unless a *username *is entered,
right?

**Comment by j4jonathan** [comment]
Oh sorry, yes, correct. Requires username. Brain in neutral.

**Comment by limpkin** [comment]
right, we'll lift that limitation then!
