### ISSUE TITLE
0.9.8 beta mac - elements of the pull down menu disappear

### ISSUE THREAD

**Issue by j4jonathan** [mooltipass/moolticute#132]
Hard to explain but the tool bar item goes blank: https://cp.sync.com/dl/828d9ecf0#r75xqxs9-n4n924xv-ieq9ssd5-r4fh6wd8

Link has video showing what I mean.

**Comment by j4jonathan** [comment]
Here's a longer screen recording of the events leading up to the pull down item disappearing: https://cp.sync.com/dl/b911eee60#425vvr3t-xrfbkmsa-5gdxrmeh-59j4qqdv

**Comment by raoulh** [comment]
What was that small transparent window you have at the bottom left and after closing it, the menu disappear?

**Comment by j4jonathan** [comment]
Not sure, but it's related to the Moolticute process somehow. There is no header to it, no content in it but when I close it, that's when the daemon disappears out of the pull down.

**Comment by raoulh** [comment]
Oh!
Damn.... I think this is actually the part of the menu that get somehow detached from the menu and opened in its own window... :(

**Comment by j4jonathan** [comment]
I think so too, but I think it's cosmetic, because everything continues to work regardless.

**Comment by azubieta** [comment]
From the qt doc:
> macOS: If you add a widget to a menu in the application's menu bar on macOS, the widget will be added and it will function but with some limitations:
> 
>     The widget is reparented away from the QMenu to the native menu view. If you show the menu in some other place (e.g. as a popup menu), the widget will not be there.

The question, is the menu being shown somewhere else ?

**Comment by j4jonathan** [comment]
Yes, it pops up into the main area of the screen, completely transparent and without a title bar.

**Comment by raoulh** [comment]
@azubieta no, the qwidget for the button is not shown elsewhere. That seem to be a Qt bug...

If we do not find a solution, we need to disable this like on linux. Maybe add a normal QMenu entry item instead for linux/macos

**Comment by limpkin** [comment]
![unnamed](https://user-images.githubusercontent.com/6170291/32548636-a548c216-c486-11e7-9db3-c87b5ed932cb.png)

Should we finally disable it?

**Comment by limpkin** [comment]
wait... has this been checked? the screen capture I sent is from the latest build.

**Comment by raoulh** [comment]
It will be disabled in the next release the same way as in linux

**Comment by limpkin** [comment]
ok! thought it was already there since a couple of days ago.

**Comment by raoulh** [comment]
No i just commited the fix 20 minutes ago, which closed the issue automatically

**Comment by limpkin** [comment]
my bad!
