### ISSUE TITLE
Password filling doesn't work with devices on fw version 1.0

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#137]
Log: 
![image](https://user-images.githubusercontent.com/10224994/31855217-bf829fd2-b674-11e7-8dd2-41678cdea44a.png)

**Comment by limpkin** [comment]
Thanks for finding that!

**Comment by NoahAndrews** [comment]
Has this been looked into at all yet?

**Comment by limpkin** [comment]
I'll get to it asap....

**Comment by NoahAndrews** [comment]
niice, thanks!
