### ISSUE TITLE
AppImage not working

### ISSUE THREAD

**Issue by raoulh** [mooltipass/moolticute#149]
On Archlinux:

```
╭─raoul@raoul-laptop ~/Downloads  
╰─➤  ./Moolticute-v0.9.19-beta.glibc2.14-x86_64.AppImage                                                                                                         127 ↵
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_MooltibpsDfv/usr/bin//moolticute.sh.wrapper.
which: no kdesudo in (/tmp/.mount_MooltibpsDfv/usr/bin/:/tmp/.mount_MooltibpsDfv/usr/sbin/:/tmp/.mount_MooltibpsDfv/usr/games/:/tmp/.mount_MooltibpsDfv/bin/:/tmp/.mount_MooltibpsDfv/sbin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no gksudo in (/tmp/.mount_MooltibpsDfv/usr/bin/:/tmp/.mount_MooltibpsDfv/usr/sbin/:/tmp/.mount_MooltibpsDfv/usr/games/:/tmp/.mount_MooltibpsDfv/bin/:/tmp/.mount_MooltibpsDfv/sbin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Allow Mooltipass Udev rules to be applied in your system?
[sudo] password for raoul: 
SUBSYSTEMS==usb, ATTRS{idVendor}==16d0, ATTRS{idProduct}==09a0, SYMLINK+=mooltipass TAG+=uaccess, TAG+=udev-acl
moolticute: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

```

**Comment by azubieta** [comment]
That lib was marked as "dangerous" in the template script that I was using so I let is as it.
I'll take a more deep look at it.

**Comment by azubieta** [comment]
I found that only the oldest version are dangerous the new ones are actively maintained and supported by Google and Mozilla.
So I remove the exclusion.

**Comment by azubieta** [comment]
Is this fixed?

**Comment by raoulh** [comment]
It starts now correctly. But the udev rules seems wrong (at least for archlinux it's not the correct one), so the daemon cannot open the device usb. Also the autostart feature is not working (when enabled in the GUI).

**Comment by limpkin** [comment]
@azubieta your work for today, while @raoulh reviews your other PR.

**Comment by limpkin** [comment]
is this solved with the recent commit?

**Comment by raoulh** [comment]
it starts now, need to check if the udev rule is ok

**Comment by azubieta** [comment]
The commits should solve the autostart in Linux when packed as an Appimage
and the udev rule only for Ubuntu.
I still don't have clear which are the correct ones for the different
distributions.
