### ISSUE TITLE
Handle credentialchangenumber wrap-over

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#156]
@azubieta contact me for more details

**Comment by azubieta** [comment]
@limpkin I'm ready for it, would you mind to give more details.

**Comment by limpkin** [comment]
Hello @azubieta !

So the comparison may be falsely wrong one time: when the counter "wraps
over" from 0xFF to 0x00.
Your comparison must therefore be changed.
We should invite the user to import the monitored file when:
- the monitored file change number is higher than the one the device *and *the
difference between both numbers is less than 0x60
- the monitored file change number is < 0x20 and the change number on the
device is > 0xE0.

**Comment by limpkin** [comment]
@azubieta 

" the monitored file change number is < 0x20 and the change number on the
device is > 0xE0."
 
yet your call remains bool greaterThanWithWrapOver(int a, int b, int limit = 0xFF, int range = 0x60) 

which actually set a range limit of 0x60 for both cases :/

@raoulh
