### ISSUE TITLE
Automatically lower case service names during add and edition in MMM

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#165]
As the mooltipass device automatically lowers any service name going his way, we need to do the same when adding or editing service names in MMM

**Comment by limpkin** [comment]
for @azubieta

**Comment by limpkin** [comment]
when to trigger lowercasing operation:
- credentials tab, in MMM and not in MMM: when either "enter" is pressed or "save" is clicked in the "add or update a credential" panel
- in files tab, in MMM and not in MMM: when either "enter" is pressed or "save" is clicked in the "add or update a file" panel

**Comment by azubieta** [comment]
The idea here is to ensure to lower case every service name that is passed to the daemon ?

**Comment by limpkin** [comment]
yes, but do the conversion in the GUI at the moments specified above.

**Comment by raoulh** [comment]
Also all service names must be lowercased in the daemon when they comme from the Json API

**Comment by raoulh** [comment]
Yes, as all service names should be lowercase only, it's better to also enforce lowercase in the api
