### ISSUE TITLE
Backup sync, hundreds of popups

### ISSUE THREAD

**Issue by raoulh** [mooltipass/moolticute#166]
If I update the synced backup from one place, on the second computer after some times I have multiples qmessageboxes asking for import the db.

It keeps opening a new qmessagebox at regular interval.

![image](https://user-images.githubusercontent.com/1115950/34262882-e9e02f14-e66d-11e7-98a0-f2d9adfca02b.png)

**Comment by limpkin** [comment]
how is that even possible @azubieta ?

**Comment by azubieta** [comment]
@raoulh could you provide a step by step description of how reproduce this issue ?
