### ISSUE TITLE
On Windows, closing Moolticute from the system tray context menu causes a crash

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#169]

**Comment by NoahAndrews** [comment]
When I try to restart the daemon from that menu, I get this message 
![image](https://user-images.githubusercontent.com/10224994/34428905-6e36b18c-ec1f-11e7-977e-d021af75b285.png)

**Comment by NoahAndrews** [comment]
Killing the daemon and app and then relaunching the app caused the software to recognize that my Mooltipass is actually unlocked (it wouldn't do this before, that's why I was trying to restart), but it doesn't fix the crash caused by the Quit option.

**Comment by raoulh** [comment]
Fixed in master, fix will be in release v0.11.4-beta
