### ISSUE TITLE
Cannot download files from mooltipass while renaming 

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#171]
Use one of the two templates below and delete the rest. All issues not following a template will be directly closed.
We apologize in advance if we ever take too long to resolve your issue. This is due to the fact that Mooltipass mostly is a contributor based project.

8<------------------------ BUG REPORT -----------------------------------------

**Expected behavior**
Download a file from moolticute to Windows.

**Actual behavior**
Cannot download a file
Error message `Data Fetch Denied for 'dab'!`
This is followed by the app displaying "The Moolticute deamon is not running."

**Step by step guide to reproduce the problem**

1. Enter moolticute file management mode
2. Enter credentials on the mooltipass device
3. Select the file to download
4. Export file to download
5. Specify directory and filename of target   
6. **** New *** specify a different filename to the file in the list. i.e. `dab.txt` instead of` dab`.

Error message `Data Fetch Denied for 'dab'!`
This is followed by the app displaying "The Moolticute deamon is not running."
**Operating System**
Windows 10 Home
Version 1709
Other operating systems are not supported.

**Mooltipass Extension**
none

**Mooltipass Application**
Mention if you are using either:
Moolticute v0.11.4-beta

**Mooltipass Device**
Mention if you are using either:

The Mooltipass Mini
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello!
I can't seem to reproduce this issue after following your steps. I can export the file regardless of the name I specify. Are you sure you're approving the requests on your device?

**Comment by alanrick** [comment]
1. Start moolticute
2. Click on Files tab
3. Enter File Management Mode (confirming on Mooltipass and entering PIN twice)
4. Select a file called `dab` from the list and press `export file `(not the diskete icon)
5. The Windows explorer window (`save to file...` ) appears with the filename blank.
6. Select the directory that I want to export the file to.
7. Enter the file name `dab.txt`.
8. Press `Save`
Interesting, today there was no error popup. The file was  exported but moolticute displays the message: `The Moolticute deamon is not running (as before)

I.e. I don't see the `Data Fetch Denied `message, but I do still see the` Moolticute deamon not running ` message.
Give me a day, I'll try to reproduce this completely.


`

**Comment by alanrick** [comment]
The following steps work:

1. Start moolticute
2. Files Management
3. Export (confirm and enter PIN twice)
4. Select file (
5. Export file (no suggested file name is shown)
6. Select directory 
7. Add file name (`Topsecret` no extension)
8. Confirm

However, if I download a file first without entering File Management Mode, and then repeat steps 3 onwards (but I'm only asked for the PIN once) then after downloading the Mooltipass does download but shows the message 
`The Moolticute Deamon ist not running.`

I.e.

1. Export (confirm and enter PIN once)
2. Select file (
3. Export file (no suggested file name is shown)
4. Select directory 
5. Add file name (`Topsecret` no extension)
6. Confirm

`The Moolticute Deamon ist not running.`

**Comment by limpkin** [comment]
Hello,

can you try again with 11.7?

**Comment by alanrick** [comment]
I’ll try this evening.

**Comment by alanrick** [comment]
It works :) Thank you and Raoul.

**Comment by limpkin** [comment]
woohoo!
