### ISSUE TITLE
Downloading a file bypasses the credential entry

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#172]
8<------------------------ BUG REPORT -----------------------------------------

**Expected behavior**
Downloading a file from moolticute to Windows should request the mooltipass PIN because it may contain information that needs to be kept as secure as passwords.

**Actual behavior**
No PIN is requested. The file is downloaded without entering Files Management Mode

**Step by step guide to reproduce the problem**

1. Start moolticute
2. Select the `Files` tab.
3. Select one of the files in the list.
4. Click the download icon on the right of the list entry (a diskette symbol).

===> The file is exported to the PC without credentials (PIN) being requested.
**Note -** you will have already entered your credentials when sliding the card into the mooltipass - but I believe downloading the file should be as secure as viewing the passwords in the credentials tab, which requires PIN re-entry.

Also, in order to `export` the file, which is equivalent to downloading credential entry is required.

**Operating System**
Windows 10 Home
Version 1709
Other operating systems are not supported.

**Mooltipass Extension**
none

**Mooltipass Application**
Moolticute v0.11.4-beta

**Mooltipass Device**
The Mooltipass Mini
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
This is a design choice: as with approving credential sending, downloading a file is a one-click to approve process.

**Comment by alanrick** [comment]
Fair enough - in fact I prefer not having to enter my PIN again.
But it does beg the question, if without entering credential/file manage mode I can see all the passwords and file contents and update each one, why PIN re-entry is necessary to enter these modes.

I guess it's the mass operations that are protected. E.g. easier to delete several files/credentials in management mode than updating each to blank without entering that mode.
Again - fair enough :)
