### ISSUE TITLE
Navigation: Exiting Files should behave like exiting Credentials

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#173]
8<------------------------ BUG REPORT -----------------------------------------

**Expected behavior**
Exiting the Files Management Mode should behave identically to exiting the Credentials Management Mode.

**Actual behavior**
See issue   #109 

**Step by step guide to reproduce the problem**
In order to exit the Files Management mode, having  made _no_ changes, you have to press the "Discard deletions" button for a long time, even though there is no indication that this is necessary. I prefer the logic for exiting the Credentials mode.

BTW: In both cases, I'd prefer see an `Exit` button if there are no changes to discard (i.e. no changes have been made)

**Operating System**
Windows 10 Home
Version 1709
Other operating systems are not supported.

**Mooltipass Extension**
none

**Mooltipass Application**
Moolticute v0.11.4-beta

**Mooltipass Device**
The Mooltipass Mini
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
@azubieta : can you replicate the behavior as in credentials management mode?
