### ISSUE TITLE
Feature Request: Help popups

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#178]
In device settings:
- Add a text along the lines of "Hint: keep your mouse positioned over an option to get more details"
- then implement some help text for each option

In synchronization tab:
- Next to each title (Export Database to File....) add a "?" icon, clicking on it brings an overlay with an explanation of the feature

**Comment by azubieta** [comment]
Is a tooltip like the one in the picture OK for the synchronization help ? Or you want a larger dialog ?
![screenshot_20180112_113318](https://user-images.githubusercontent.com/1138094/34887508-636cbea4-f78c-11e7-94d6-0fe38bdd342f.png)

**Comment by azubieta** [comment]
@limpkin I'll need some help writing the "help" messages

**Comment by limpkin** [comment]
Put place holders I will put the text after

**Comment by azubieta** [comment]
Placeholders have been set.
