### ISSUE TITLE
exports different file contents depending on timing

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#187]
On Windows 10, the contents of the file downloaded are corrupted, depend on the extension.

- The original file is `ThisIsTopSecret.txt`
- The correct contents when I download to `TopSecret.asc`
- Incorrect contents when I download to `TopSecret.txt `(despite the original extension)
Files attached.

[ThisIsTopSecrect.txt](https://github.com/mooltipass/moolticute/files/1629151/ThisIsTopSecrect.txt)
[TopSecret.txt](https://github.com/mooltipass/moolticute/files/1629152/TopSecret.txt)

The next file was is TopSecret.asc but I had to rename it to upload here
[TopSecretASC.txt](https://github.com/mooltipass/moolticute/files/1629153/TopSecretASC.txt)

**Comment by alanrick** [comment]
BTW: Version: v0.11.4-beta assuming no typos ;)  It would be nice to be able to cut&paste the version from the `about `screen on Windows.

**Comment by limpkin** [comment]
Can't replicate it... and I don't see how it could be possible given that we just export the bytes as they come to us.
However, we recently fixed a bug related to import/export merges for small files... so could you try to replicate that on v0.11.5?

**Comment by alanrick** [comment]
in v0.11.5 the corruption still occurs but I haven't yet determined how to reproduce it.
It appears unrelated to the extension.
5/5 exports worked.
1/5 downloads worked (file icon outside file-management-mode)  - the rest were corrupted.

**Comment by limpkin** [comment]
ok... let me know when you can reliably reproduce it...
are you running windows?

**Comment by alanrick** [comment]
Yes - Windows 10 Home.
Also...
I didn't have to enter my PIN twice when entering file-management-mode. And the deamon wasn't lost after downloading or exporting. That's an improvement over the 04 version.

**Comment by limpkin** [comment]
are you sure you don't have mooltiapp running?

**Comment by alanrick** [comment]
Not 100% sure - no.
I'd checked the tasklist and there was no moolt* process running, just the multicute App.
I did notice that the chrome browser extensions had a checkmark for both the mooltipass app and the mooltipath extension but I thought that the app would only be started if I started it manually from the extension menu (which I didn't).
To be on the safe side I've deactivated the app in the extensions setting but the same problems occur.
File is sometimes corrupted when downloading and the
`Moolticute Daemon is Not Running.` message displayed in the moolticute body.

**Comment by limpkin** [comment]
I still can't reproduce it :/
Could you give us the daemon logs when this happens? (settings: view daemon logs)

**Comment by alanrick** [comment]
I can also reproduce it through the command line. See attached.
<img width="555" alt="moolticutecapture" src="https://user-images.githubusercontent.com/7034358/35163250-6471e7ba-fd46-11e7-98a5-760c056d52e8.PNG">

**Comment by limpkin** [comment]
Hey Alan!

I'm quite sure I fixed your bug in https://github.com/mooltipass/moolticute/commit/585119dec66a21ad3b5468ac3e5a6c6db38f51b3 .
v0.11.7 (released tonight) should fix your problem, please reopen this issue if not.

Thanks a lot for your time spent on this issue!
