### ISSUE TITLE
Segmentation fault on emulation mode

### ISSUE THREAD

**Issue by sbobykin** [mooltipass/moolticute#188]
After running `./moolticuted -e` I've got `Segmentation fault` error on my mac. To solve the problem I've made the following simple modification.

```
diff --git a/src/MPDevice.cpp b/src/MPDevice.cpp
index 8db0325..675d6c0 100644
--- a/src/MPDevice.cpp
+++ b/src/MPDevice.cpp
@@ -286,10 +286,10 @@ void MPDevice::sendDataDequeue()
     qDebug() << "Full packet: " << a;
 #endif

+    currentCmd.timerTimeout->start();
+
     // send data with platform code
     platformWrite(currentCmd.data);
-
-    currentCmd.timerTimeout->start();
 }

 void MPDevice::runAndDequeueJobs()
```

But I'm not sure. Is this modification correct or not? That would be great to have a discussion.

**Comment by limpkin** [comment]
@raoulh can correct me, but if I'm not mistaken, that won't work as you're trying to talk to a device taht doesn't exist.

**Comment by sbobykin** [comment]
Here is a log where I've got Segmentation fault

```
$ ./moolticuted -e

INFO: ../src/AppDaemon.cpp:47 - Moolticute Daemon version:  git
INFO: ../src/AppDaemon.cpp:48 - (c) 2016 Raoul Hecky
INFO: ../src/AppDaemon.cpp:49 - https://github.com/raoulh/moolticute
INFO: ../src/AppDaemon.cpp:50 - ------------------------------------
DEBUG: ../src/WSServer.cpp:34 - Moolticute daemon websocket server listening on port  30035
INFO: ../src/MPManager.cpp:37 - Starting MPManager
DEBUG: ../src/MPManager.cpp:130 - List usb devices...
DEBUG: ../src/MPDevice_emul.cpp:28 - Emulation Device
DEBUG: ../src/WSServer.cpp:113 - Mooltipass connected
INFO: ../src/AsyncJobs.cpp:98 - "Exiting MMM"
DEBUG: ../src/MPDevice_emul.cpp:229 - Unimplemented emulation command:  "\x00\xD3"
CRITICAL: ../src/MPDevice.cpp:3492 - Failed to exit MMM
Segmentation fault: 11
```

**Comment by sbobykin** [comment]
There is another kind of fix.
```
diff --git a/src/MPDevice.cpp b/src/MPDevice.cpp
index 8db0325..0a13915 100644
--- a/src/MPDevice.cpp
+++ b/src/MPDevice.cpp
@@ -289,6 +289,9 @@ void MPDevice::sendDataDequeue()
     // send data with platform code
     platformWrite(currentCmd.data);

+    if (commandQueue.isEmpty())
+        return;
+
     currentCmd.timerTimeout->start();
 }
```

It's seems for me, when the real device is plugged then there is no problems cause `platformWrite` sends data to a device and It has to wait for response.

Because of waiting for response we have a time to do `currentCmd.timerTimeout->start();` after `platformWrite(currentCmd.data);`.

But if we use emulation mode then we get response immediately. So we don't have a time to do `currentCmd.timerTimeout->start();` after `platformWrite(currentCmd.data);`. According to my exploration in one case we have `currentCmd.timerTimeout` as `nullptr` in the other case we lose `currentCmd` at all.

**Comment by limpkin** [comment]
@raoulh please take time to check that :(

**Comment by raoulh** [comment]
Hi,

@sbobykin your assumption are correct. Except the fix is not good as it could break at other place.
I did a better fix in master, where I delay the reply of the emulation device, just like a real device, by emitting the platformRead signal in the next loop of the event loop.

**Comment by sbobykin** [comment]
@raoulh thanks a lot for your fix

**Comment by limpkin** [comment]
@sbobykin do you feel comfortable implementing support for all moolticute features in emulation mode? :)

**Comment by sbobykin** [comment]
Yes I'd like to)
