### ISSUE TITLE
In management mode, it should be clear whether or not the current entry is a favorite

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#190]

**Comment by limpkin** [comment]
@azubieta : could you, when entering management mode, automatically expand credentials that are favorites?

Thanks

**Comment by NoahAndrews** [comment]
That's useful, but in my opinion it should be clear why that's happening too. Maybe put a star by those entries or something.

**Comment by limpkin** [comment]
there are stars ;)

**Comment by NoahAndrews** [comment]
Aaand we're back to the buggy favorites behavior for my MP. I probably should have guessed that this was already in place, and that it was the same root cause that was causing the not-disabled dropdown entries and unclarity about whether or not I'm looking at a favorite.

**Comment by limpkin** [comment]
I'll do some testing on my original mooltipass.

**Comment by limpkin** [comment]
feature is implemented and bug is solved :)
