### ISSUE TITLE
Already-claimed favorites aren't disabled in the relevant dropdown

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#191]
This feature was supposed to be added in #126.

This could be a fw v1.0 thing again, but I didn't see anything in the log indicating that nonexistent commands were used or anything. [Also, I see that it was able to load the list of favorites](https://user-images.githubusercontent.com/10224994/35067164-f9c4b15a-fba0-11e7-92a0-bcb12b8c58e1.png).

[As you can see, every single one of my favorite slots is used. Yet, none of the entries are disabled](https://user-images.githubusercontent.com/10224994/35066680-7745ba86-fb9f-11e7-8f9f-7a5d71f20481.png).

Edit: inline images in GH Issues seems to be broken, so I'm changing them to links.

**Comment by NoahAndrews** [comment]
Huh. So I did attempt to remove a few favorites, and I thought it didn't work (I was going to file a separate issue for that, but I guess I'll just put it here for now). But the last two entries in the favorites list that is loaded appear to be blank in that first screenshot. On the OG Mooltipass though, all 3 screens of favorites are still populated.

**Comment by limpkin** [comment]
works for me with the mini **and** the original

![image](https://user-images.githubusercontent.com/6170291/35089024-f77e71b6-fc35-11e7-8b27-0e0cf5233c0a.png)

could you run an integrity check and try again?
I think there's a bug somewhere for the favorites...

**Comment by NoahAndrews** [comment]
The integrity check said it completed successfully, and it behaved the same afterwards.

I suggest we start with the bug where it refuses to remove favorites.

**Comment by NoahAndrews** [comment]
In the logs, when it lists all of the entries in JSON format, I can see that every entry has "favorite" set to -1, regardless of whether or not it's actually a favorite. This is after the integrity check.

**Comment by limpkin** [comment]
did you do any file import to that mooltipass? I just found a bug.

**Comment by limpkin** [comment]
Ok I'm fairly sure of what happened... stay tuned

**Comment by NoahAndrews** [comment]
A while back, yes.

**Comment by limpkin** [comment]
I've just pushed to master the bug fix.
Once v0.11.6 is release (hopefully later today) you'll need to run an integrity check and then everything will be ok :)

**Comment by NoahAndrews** [comment]
Awesome! Great support as always :)

**Comment by limpkin** [comment]
11.6 finally released!

**Comment by limpkin** [comment]
That's expected, but now you won't have problems anymore!

**Comment by NoahAndrews** [comment]
Gotcha, good enough.
