### ISSUE TITLE
Display extra info for the "Generate MooltiApp Compatible" flag

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#194]
If the "Generate MooltiApp Compatible File" flag is selected when exporting the database the user IDs are not encrypted. This should display as extra info on the synchronization screen, preferably in red as is done for the enable-knock flag.

**Comment by limpkin** [comment]
solved with PR #217

**Comment by alanrick** [comment]
The text is not helpful. I prefer something like:
`MooltiApp compatible export files do NOT encrypt the login IDs.`
