### ISSUE TITLE
misleading info for export-compatibility 

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#237]
Not sure if you saw my comment #194 

The current text implies that passwords aren't encrypted (which they obviously are) so I prefer:

`MooltiApp compatible export files do NOT encrypt the login IDs. Only the passwords are encrypted.`

I also wonder if the moolticute files are added to the compatible export, and if these are encrypted.

**Comment by limpkin** [comment]
Hello Alan!

Thanks for bringing this to our attention again. We'll think of a way to phrase it in a way that do not make our users doubt the security of our device. I'm closing this issue as it effictively is a duplicate of #194

**Comment by alanrick** [comment]
not yet corrected in 12.7. Just sayin' :)
Alan

**Comment by limpkin** [comment]
![image](https://user-images.githubusercontent.com/6170291/37657910-8c3c61c8-2c4c-11e8-9231-60a5cba914aa.png)
isn't good enough?

**Comment by alanrick** [comment]
That's the original text I think. It implies that neither the login-id or
the login-password is encrypted. But I believe the password is encrypted
even in compatible-mode.

**Comment by NoahAndrews** [comment]
Maybe change the word "logins", which could imply the combination of username/password to the word "usernames".

**Comment by alanrick** [comment]
still not improved.
