### ISSUE TITLE
Cosmetic changes Request

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#239]
1) In MMM:  
- select one credential  
- click eye icon to show password  
- change password  
  
task: when clicking the "Discard changes" button, change the text to "Hold to Confirm" and make the complete button change color if possible  
similar task: do the same for the MMM discard changes button
    
2) in MMM, when using the password generator:
- when the password size is long, it is not completely displayed
  
3) when changing MC's language:
- the "I" next to the titles in the synchronization tab are changed to some strange "?"
   
4) in MMM, when a change in the credential has been detected:  
- disable all lists and buttons except the "accept changes" and "discard changes" to make the user understand that one of the two buttons needs to be approved.  
- same when clicking the eye icon

**Comment by azubieta** [comment]
Which color should I use for the discard changes button ?

**Comment by azubieta** [comment]
About the 4th change, should we add a timeout for the cases in which the users just don't accept or reject the changes ?

**Comment by azubieta** [comment]
Please test it.
