### ISSUE TITLE
Migrating to Appdata: Several Major Bugs

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#243]
I've just removed the 0.12.3 .exe due to these bugs:

Here's the explosive cocktail: 
- when installing 0.12.0 installer, MC is run as local admin. MC then detects 0.12.3 and will install it under the admin session app data. **There is no mitigation for that**
- when launching 0.12.3 installer, it won't close MC 0.12.0. When selecting "launch Moolticute", MC 0.12.0 window will be displayed. At computer reboot 0.12.3 is launched but 0.12.0 is still present under program files. There is no mitigation for that, even though it is not crucial given all new installs will use 0.12.3+
- **the uninstaller doesn't work**: after entering windows admin session credentials (uninstaller is not signed) we get a warning saying that some files couldn't be deleted. Looking at the installation directory under appdata/local, all files are still there **(except unins000.exe)** and moolticute is still launched at boot. The moolticute item is still present in "apps and features" but clicking uninstall leads to an error due to the removed unins000.exe. I'm therefore guessing this is due to MC not being closed by the uninstaller
- I'm guessing that due to the bug above any update that may happen on 0.12.3 will not work.
- bug on a non admin install: https://www.reddit.com/r/mooltipass/comments/84dm4m/our_setup_pages_have_been_updated_officially/dvqyrd5/
- I have a feeling that the registry keys that are used by https://github.com/mooltipass/moolticute/pull/222 won't work anymore no?

@raoulh this is critical and therefore 0.12.3 exe was removed from the latest release. Hopefully no user installed this exe during the one hour it was online.

edit: this issue seems to only be valid for work stations with users having separate credentials for admin access. Except the error message shown in that reddit thread, the uninstall process went fine for a non-admin user.

**Comment by mutvirak1990** [comment]
I am fully understood your requirements
Please feel free to contact me

**Comment by mutvirak1990** [comment]
I am c++(Qt) expert named Mut.:)
