### ISSUE TITLE
Moolticute opens ports externally

### ISSUE THREAD

**Issue by randomisresistance** [mooltipass/moolticute#244]
The moolticute app downloaded via https://github.com/mooltipass/moolticute/releases/download/v0.12.3/Moolticute-v0.12.3.glibc2.14-x86_64.AppImage

Opens Port 8484 and 30035 externally. These Ports should only be opened on localhost.

```$ sudo lsof -itcp -stcp:listen
[sudo] password for xxx: 
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
cupsd      975   root   10u  IPv6  24826      0t0  TCP ip6-localhost:ipp (LISTEN)
cupsd      975   root   11u  IPv4  24827      0t0  TCP localhost:ipp (LISTEN)
sshd      1168   root    3u  IPv4  24551      0t0  TCP *:ssh (LISTEN)
sshd      1168   root    4u  IPv6  24553      0t0  TCP *:ssh (LISTEN)
dnsmasq   1294 nobody    5u  IPv4  25658      0t0  TCP yyy:domain (LISTEN)
moolticut 5121   xxx    6u  IPv4  43999      0t0  TCP *:8484 (LISTEN)
moolticut 5121   xxx    7u  IPv6  44000      0t0  TCP *:30035 (LISTEN)
```

**Comment by randomisresistance** [comment]
seems to be fixed :)

**Comment by limpkin** [comment]
Hey there!
Your second post showed mooltiapp (our old app) and not moolticute (its replacement).
@raoulh  will be able to correct me on this, but the reasoning behind letting moolticute listen to outside packets was in the case where the daemon would run on a computer different than the computer where the extension is :).

**Comment by randomisresistance** [comment]
Hi!
Sorry I pasted the wrong output. I was playing around with MooltiApp as well as with moolticute, mixed something up.

They are still opened externally.
```
$ sudo lsof -itcp -stcp:listen
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sshd      1289   root    3u  IPv4  22437      0t0  TCP *:ssh (LISTEN)
sshd      1289   root    4u  IPv6  22439      0t0  TCP *:ssh (LISTEN)
dnsmasq   1390 nobody    5u  IPv4   2680      0t0  TCP yyy:domain (LISTEN)
g15daemon 2658 nobody    5u  IPv4  28082      0t0  TCP localhost:15550 (LISTEN)
mono      3856   xxx    8u  IPv4  30415      0t0  TCP localhost:8200 (LISTEN)
moolticut 4130   xxx    5u  IPv4  42471      0t0  TCP *:8484 (LISTEN)
moolticut 4130   xxx    6u  IPv6  42472      0t0  TCP *:30035 (LISTEN)
cupsd     5130   root   10u  IPv4  54756      0t0  TCP localhost:ipp (LISTEN
```
As far as I understood this the web server (port 8484) that can be optionally be activated is for this task. Port 30035 is as far as I understood for the websocket connection of the browser plugins.

If this is  really intentional, then this would be a feature request to let the user decide if the ports are opened externally or not.

**Comment by raoulh** [comment]
@limpkin is correct

**Comment by randomisresistance** [comment]
@limpkin @raoulh 
So then I will open up a feature request? Because I think for the most users it is not necessary to expose these ports externally, localhost should be fine for the most people. It only opens up a attack surface, when it is not needed. Especially because it is a password manager, this topic should be treated sensitively.

**Comment by limpkin** [comment]
closing due to your feature request :)
