### ISSUE TITLE
Moolticute app does not allow to type under Linux Mint

### ISSUE THREAD

**Issue by randomisresistance** [mooltipass/moolticute#245]
Moolticute downloaded via the link form the webpage: 
https://github.com/mooltipass/moolticute/releases/download/v0.12.3/Moolticute-v0.12.3.glibc2.14-x86_64.AppImage

Under the Linux Mint (sylvia) it is not possible to type in the moolticute app window.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
```

**Comment by limpkin** [comment]
Hello,


Thanks for the bug report!
Do you been that the moolticute text fields do not allow text input or
something else?

Thanks

**Comment by randomisresistance** [comment]
Right, if executed that way it is not possible to type in text field. Generally all keyboard commands are ignored.

**Comment by limpkin** [comment]
Hello,
I'm confused... do you mean that you can't use the mooltipass mini manual credential recall?

**Comment by randomisresistance** [comment]
That works, but if want to use the credential management mode for example the keyboard is not working in the moolticute GUI.

The workaround for this was kinda easy at it was for me to install the .deb packet on my system.

**Comment by Christian308** [comment]
Same under Ubuntu 16.04. The error message when starting the AppImage is:

    zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_MooltiCuDFvg/usr/bin//moolticute.sh.wrapper.
    xkbcommon: ERROR: failed to add default include path ././/share/X11/xkb
    Qt: Failed to create XKB context!
    Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .`

as a workaround I wrote a wrapper script which simply sets the environment variable before executing Moolticute

    #!/bin/sh
    export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
    /path/to/app/image/Moolticute-v0.12.7.glibc2.14-x86_64.AppImage

then keyboard entry is working.

Cheers
Christian

**Comment by suntorytimed** [comment]
This does apply to openSUSE Tumbleweed with Plasma as well.

**Comment by limpkin** [comment]
thanks everyone for your feedback! we'll tackle that very soon
