### ISSUE TITLE
Autostart feature for linux needs to be delayed

### ISSUE THREAD

**Issue by randomisresistance** [mooltipass/moolticute#246]
Because of problems (typing issue) with the AppImage I installed the .deb file from the repo here. 
The typing issue does not appear with this setup. 

But while playing around I noticed that, the autostart feature does not work. I was able to figure out what the problem is. The startup command executed by X must be delayed about 3 seconds otherwise the moolticute GUI wouldn't start properly

**Comment by limpkin** [comment]
thanks a lot for the debug!

**Comment by limpkin** [comment]
guessing @raoulh will tackle that one :)

**Comment by limpkin** [comment]
everyone: is this still needed?
