### ISSUE TITLE
moolticute GUI forgets does not read 'device settings' after reboot

### ISSUE THREAD

**Issue by randomisresistance** [mooltipass/moolticute#247]
The moolticute GUI seems to fail to read the 'device settings' from the mooltipass device properly. It just displays the default settings. The actual settings on the device seem not to be affected by this. 

![image](https://user-images.githubusercontent.com/8646929/37516718-5bb2f37c-290f-11e8-93c5-952a390b70c7.png)

**Comment by limpkin** [comment]
thanks for the bug report!
out of curiosity, are the udev rules correctly installed?

**Comment by randomisresistance** [comment]
Hi limpkin,

sorry for the delayed answer. I used the Mooltiapp before and therefore have the udev rules deployed for a while now. But I double checked and everything is set up correctly.

I also have to add that the problem disappears when I open up the Moltucute app and then restart the daemon via the tray icon while the GUI is open. So this seems to be a smaller glitch.

Hope this helps!

**Comment by limpkin** [comment]
I just had the very same bug on a slow windows machine.
Is it possible it is related to #246 ?
tagging @raoulh

**Comment by limpkin** [comment]
pinging @raoulh

**Comment by limpkin** [comment]
I recently got this issue... could you keep an eye for it @deXol ?

**Comment by limpkin** [comment]
solved with latest commit :)
