### ISSUE TITLE
Bitdefender Disinfection of Mootlicute

### ISSUE THREAD

**Issue by sonofapharmacist** [mooltipass/moolticute#250]
All files related to the download and install of moolticute_setup_v0.12.7.exe is being picked up by bit defender.  After install the whole thing got nuked.  I cannot go through the process to report bitdefender the (possible) false positive at the moment.

e.g.,
appdata\local\programs\moolticute\libeay32.dll is infected with Atc4.Detection and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

local\programs\moolticute\unins000.dat is infected with Atc4.Detection and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by limpkin** [comment]
Hello there!  
Bitdefender is indeed very picky because of the new way we now install moolticute (see https://www.reddit.com/r/mooltipass/comments/85aga8/new_moolticute_v0127_doesnt_need_admin_privileges/)
