### ISSUE TITLE
Lock Unlock Feature is missing "ctrl+alt+del + Pass / Win + L"

### ISSUE THREAD

**Issue by EidEchse** [mooltipass/moolticute#251]
![image](https://user-images.githubusercontent.com/3710207/37624251-d018a224-2bc7-11e8-8b22-3c5cec4ceded.png)

**Comment by limpkin** [comment]
you're right... it's there in the firmware but for some reason not implemented in moolticute...
https://github.com/limpkin/mooltipass/blob/master/source_code/src/LOGIC/logic_smartcard.c#L72

**Comment by limpkin** [comment]
value is 0x18
