### ISSUE TITLE
On GNU/Linux Debian: Error opening usb device:  Access denied

### ISSUE THREAD

**Issue by ajira86** [mooltipass/moolticute#256]
I'm using Debian/buster and never succeed to connect device with moolticute. It only works if I run moolticute with root (sudo). Is there any configuration that I have missed ?

```
INFO: :0 - Trying to set language:  ":/lang/mc_en.qm"
INFO: :0 - Running  "/usr/bin/moolticuted"   ()
INFO: :0 - Daemon started
DEBUG: :0 - Connection closed  WSServerCon(0x14ce160)
DEBUG: :0 - New connection
DEBUG: :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: :0 - JSON API recv: {
    "msg": "list_files_cache"
}

DEBUG: :0 - New connection
DEBUG: :0 - JSON API recv: {"msg":"get_application_id"}

[connecting device ...]

DEBUG: :0 - 0
DEBUG: :0 - Device removed:  0x16d0 - 0x9a0
DEBUG: :0 - List usb devices...
DEBUG: :0 - Device added:  0x16d0 - 0x9a0
DEBUG: :0 - List usb devices...
WARNING: :0 - Error opening usb device:  Access denied (insufficient permissions)
INFO: :0 - Checking software updates from  "https://api.github.com/repos/mooltipass/moolticute/releases"

[reconnecting device ...]

DEBUG: :0 - 0
DEBUG: :0 - Device removed:  0x16d0 - 0x9a0
DEBUG: :0 - List usb devices...
DEBUG: :0 - Device added:  0x16d0 - 0x9a0
DEBUG: :0 - List usb devices...
WARNING: :0 - Error opening usb device:  Access denied (insufficient permissions)
```

**Comment by limpkin** [comment]
Hello!

Can you install the udev rules here? 
https://github.com/mooltipass/mooltipass-udev

**Comment by ajira86** [comment]
Oh, sorry I forget to update this configuration, isn't it possible to add it in the deb file ?

**Comment by limpkin** [comment]
Hey @ajira86 ,

would you be able to check that it now works for you? https://github.com/mooltipass/moolticute/releases/tag/v0.12.9

Regards

**Comment by ajira86** [comment]
Hello @limpkin, I purged the package, removed the file in /etc/udev and restarted the computer to ensure a clean remove. Then installed the new version, restart again and check with mooltipass. Work like a charm ;)

**Comment by limpkin** [comment]
that's wonderful!
thanks for testing
