### ISSUE TITLE
The autofilling does not work reliably

### ISSUE THREAD

**Issue by cornelinux** [mooltipass/moolticute#260]
I am using the mooltipass mini with Ubuntu, chrome and the latest moolticute.
Autofill of websites does not work reliable.
Once in a while the websites are not detected and the logins are not filed.
I have to enter credentials manual with the wheel.

I am happy to provide any additional information!

**Comment by limpkin** [comment]
Hello,

Could you provide us with more details?
Is it a website related behavior? If not, that would be extremely odd.
Can you let us know your full computer configuration?

**Comment by cornelinux** [comment]
Hi,
this problem occurs in a few cases with websites that work fine otherways.

What do you need to know about the computer?
The question is: What do I need to do, grab, log in the case, when the problem occurs?

**Comment by limpkin** [comment]
Hardware configuration : memory, CPU, VM or native machine, ssd or HDD,
number of USB peripherals connected and what they are.

Moolticute logs (can be accessed through the settings tab of moolticute)
would be useful when this happens.

**Comment by limpkin** [comment]
Any news?

**Comment by limpkin** [comment]
closing this issue in a week if no news.

**Comment by cornelinux** [comment]
Thanks for your patience! I am sorry, I appologize for the long delay.

The computer looks like this:
* Ubuntu 16.04LTS
* RAM: 20GB
* Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
* native machine
* SSD 
I updated to moolticute v0.12.11. I will check the log in case of error and put it here.

**Comment by cornelinux** [comment]
I just experience the effect:

Moolticute is running (I see the desktop UI) and I try to login to a saved website. The mooltipass does not respond. Debug output is:

<pre>
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - Error sending data:  Input/Output Error
WARNING: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"  has failed too many times. Give up.
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - Error sending data:  Input/Output Error
WARNING: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"  has failed too many times. Give up.
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - JSON API recv: {"msg":"ask_password","client_id":5,"data":{"service":"xxxxxxxxxxx","fallback_service":"xxxxx","login":"","request_id":13}}
INFO: :0 - "Ask for password for service: xxxxxxx login:  fallback_service: xxxxxxx reqid: ws-xxxxxxxxxxxxxxxxxxxxxxx"
DEBUG: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - Error sending data:  Input/Output Error
WARNING: :0 - > Retry command:  "MOOLTIPASS_STATUS (0xb9)"  has failed too many times. Give up.
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "CONTEXT (0xa3)"
WARNING: :0 - Error sending data:  Input/Output Error
DEBUG: :0 - > Retry command:  "CONTEXT (0xa3)"
WARNING: :0 - Error sending data:  Input/Output Error
WARNING: :0 - > Retry command:  "CONTEXT (0xa3)"  has failed too many times. Give up.
CRITICAL: :0 - Failed getting password:  ""
WARNING: :0 - Error sending data:  Input/Output Error
</pre>

**Comment by cornelinux** [comment]
When I reconnect the device, moolticute still thinks the device is not connected:

<pre>
DEBUG: :0 - New message:  {"msg":"mp_disconnected"}
DEBUG: :0 - New message:  {"msg":"mp_disconnected"}
DEBUG: :0 - New message:  {"data":{"error_message":"No device connected","failed":true},"msg":"get_random_numbers"}
DEBUG: :0 - update seed:  QJsonArray()
DEBUG: :0 - New message:  {"data":{"error_message":"No device connected","failed":true},"msg":"list_files_cache"}
</pre>

Hm lsusb indeed said, the device was not found!

It looks like - as I complained eralier - that the usb connector in the mooltipass mini does not work reliably. The plug in the mooltipass is rather loose! Probably the two data lines in the usb plug are sometimes not connected?

**Comment by limpkin** [comment]
Hello,

Could you try other USB cable?

**Comment by cornelinux** [comment]
I tried several USB cables. I think the hardware design is simply bad. The connector on the PCB is to short. Every cable does not fit well into it. I already thought about soldering a cable on the board. But this is probalby not possible since this would break the metal housing of the mini.

Actually please take this as the hint for a design improvement of version 3.

I am wondering. Every smartphone uses the same USB connector and comes with a good tight cable plugged in. Why doesn't the mooltipass?

**Comment by limpkin** [comment]
If that's the case then you would be our first customer having a unit with
a defective USB connector. Can you confirm you have setup the udev rule?

Given that you mention that the cable doesn't go all the way into the
connector, could you inspect the connector?

Thanks for you suggestion for the next revision, however, if you were in
our place, would you take the risk of changing USB connectors when the one
we used so far only failed one in 10s of thousands of units?

In any case, we can offer you a full refund or replacement unit after you
send us a quick video showing the problem.

**Comment by cornelinux** [comment]
The USB cable plugs in like this. This way it is a bit unsteady.

![20180506_115448](https://user-images.githubusercontent.com/1908620/39672126-843c4428-5124-11e8-8101-5d8db426d60b.jpg)

Thanks a lot for the kind offer. Now that I understood the issue I will further investigate this. 
Anyways, I will close this issue here, since it is no moolticute issue!

**Comment by limpkin** [comment]
thanks, please let us know!
