### ISSUE TITLE
Device memory

### ISSUE THREAD

**Issue by ajira86** [mooltipass/moolticute#262]
Hello, FYI: I wanted to inform myself about memory capacity of the Mooltipass lend to me. It seams that the box specify a 4Mb version (perhaps for the old ones) but Moolticute announce a 8Mb one. As I can see on the Moolticute logs, the device was detected as a 8Mo one. Perhaps the package box is wrong, let me confirm it to you later, I will receive a newer Mootlipass soon.

**Comment by limpkin** [comment]
Hello!  
The package box is indeed wrong... nice catch!
