### ISSUE TITLE
Moolticute stays in the background

### ISSUE THREAD

**Issue by hbxu** [mooltipass/moolticute#269]
Not sure if it's by design or if it is a bug.

When closing using the x button right of the window, ut doesn't actually close the whole moolticute application.
The moolticute application (daemon?), stays running.

You can get strange behaviors:
1. Run moolticute
2. Close (x button) moolticute application
3. Run moolticute (doesn't show any GUI)
4. Run moolticute again, a GUI is presented

**Comment by limpkin** [comment]
This is indeed by design.
