### ISSUE TITLE
Inability to modify "Service or Website" from Moolticute "Credentials Management" mode

### ISSUE THREAD

**Issue by kbembedded** [mooltipass/moolticute#272]
**Issue:**
While rare, I sometimes find myself in a situation where I need to rename the Service/Website of an entry in my mooltipass.  I recently moved over to moolticute and found that the credentials management mode of the application is unable to rename the Service/Website.

Using v0.12.11 on both a Windows host and Debian host.

**Workarounds:**
Switch to using the old Mooltipass Chrome app to rename the required Service/Website names.
Create a new entry with the proper URL and delete the old and incorrect one.

**Comment by alanrick** [comment]
Just noticed the same today.  E.g. remove the http:// prefix from some entries to improve sort order.

**Comment by AtosNicoS** [comment]
I also noticed this bug today. It is really annoying and a big regression in the user experience. It would be nice if you can give the issue more focus, its been opened for over half a year now.

**Comment by limpkin** [comment]
Hello everyone,

This particular issue hasn't been forgotten... We have focused our efforts
on things that do not have workarounds.

**Comment by limpkin** [comment]
implemented.
