### ISSUE TITLE
buggy update notification

### ISSUE THREAD

**Issue by frankenstein91** [mooltipass/moolticute#277]
As I already described the problem in ArchLinux AUR, I get an update notification. I am already using the latest version of the software.

https://aur.archlinux.org/packages/moolticute/
https://ibb.co/iHmheS

I use a Mooltipass Mini and ArchLinux.
Please help me to fix it

**Comment by limpkin** [comment]
wow, that's quite strange.  
@raoulh do you have an idea?

**Comment by bobsaintcool** [comment]
@frankenstein91 maybe provinding the debug log will help to map what is happening with your problem.

**Comment by araab** [comment]
The problem is in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moolticute#n25 perhaps you can change it to `sed -i "s/#define APP_VERSION \"git\"/#define APP_VERSION \"v${pkgver}\"/" ./src/version.h` then the git tag matches.

**Comment by bobsaintcool** [comment]
Absolutely, @limpkin can close.

However, if I get time, I will try to found a way to run update/update checking in case of packaged apps.

**Comment by frankenstein91** [comment]
@bobsaintcool where do i get the debug log?

**Comment by raoulh** [comment]
@frankenstein91 in the gui, Settings tab, click View daemon logs
