### ISSUE TITLE
Standard Mooltipass: Rogue "i" element

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#280]
For the "keep in sync" feature that isn't available for the standard mooltipass

![image](https://user-images.githubusercontent.com/6170291/40224030-3d37e82e-5a85-11e8-8902-db37a8cafd0d.png)

**Comment by raoulh** [comment]
Also the "keep in sync" feature is not shown when you do that:

- Quit moolticute
- connect the device and unlock it
- start moolticute
- click directly (and without waiting, as soon as the main window is displayed) on the Sync tab

Result: when the device is detected by MC, the "keep in sync" is not displayed, only the remaining "i"
If you switch tab, it actualizes the layout and the "keep in sync" feature is shown correctly

**Comment by limpkin** [comment]
@raoulh keep in sync isn't available on the standard mooltipass has it doesn't support change numbers.

**Comment by raoulh** [comment]
@limpkin I totally understood that and know that.
By note is a related bug for the update of this part of the gui for the mini.

I wrote that here to not to forget to tackle this problem too when working on resolving this bug.

**Comment by limpkin** [comment]
ohhh, you meant for the mini and not the standard....  my bad!
