### ISSUE TITLE
Feature request: da_DK_MAC keyboard layout

### ISSUE THREAD

**Issue by netromdk** [mooltipass/moolticute#285]
First of all: Thanks for an awesome password manager solution!

I would like to request support for the `da_DK_MAC` keyboard layout such as there is the `de_MAC`, `de_CH_MAC`, `fr_MAC`, `fr_CH_MAC`, and `us_MAC`.

By looking through the code I found [keyboard LUTs](https://github.com/mooltipass/moolticute/blob/c0a0f0ea1d8c5436be2e37493a7e8d933f4b722d/src/Common.h#L94). But it seems these are saved into the firmware of the Mooltipass device itself? Is it possible to update this somehow?

Running firmware verison `v1.2_mini`.

Thanks!

**Comment by limpkin** [comment]
Are you sure you don't have it? I managed to get it on MC:

![image](https://user-images.githubusercontent.com/6170291/41093942-e44bc3de-6a4c-11e8-9dea-d9c9d4db17b3.png)

**Comment by netromdk** [comment]
I would say I'm pretty handy. Tell me what you need. :)

**Comment by limpkin** [comment]
actually most of the steps require specific firmware.... I'll try to do this asap but please send me a reminder if I take too long

**Comment by netromdk** [comment]
Thanks! Looking forward to it.

**Comment by limpkin** [comment]
fw support added to the mooltipass repository... I'm therefore closing this issue.
A new issue should be created around the lines of "support of non existing keyboard layouts"
