### ISSUE TITLE
Error on importing private ed25519 SSH key

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#306]
I just tried to take advantage of the SSH key functionality of my Mooltipass Mini, having not tried it before, but it doesn't appear to like my ed25519-format SSH key.

![screenshot from 2018-06-27 13-40-30](https://user-images.githubusercontent.com/1130041/41974495-0521356c-7a10-11e8-998e-b04b54e18a1d.png)

Transcription for those searching:

```
Some errors occured:
Failed to add key:
[/tmp/id_ed25519] Failed to parse, ssh: cannot decode encrypted private keys
No keys to add
```

The key in question is not passphrase protected. (Also, it didn't appear when I browsed to ~/.ssh/ - only the public-key version. I had to copy it into /tmp/ for Moolticute to see it.)

I'm assuming this error is caused because Moolticute doesn't yet support ed25519 keys - and if so, can I request support is added, please and thank you?

Oh, and while I'm here: "occured" is a typo; the message should read "occurred".

**Comment by limpkin** [comment]
Your support assumption is correct!
Out of curiosity how did you find that SSH tab?

**Comment by netromdk** [comment]
It should actually support it: https://github.com/raoulh/mc-agent/blob/master/ssh_parse.go#L116

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ghalfacree** [comment]
I got the email about Moolticute v0.18.7 (should have said what version I was running in the original post - whoops) and brought up the Advanced tab to see what the new CSV import feature looked like, then saw "SSH Key Tab" and went "ooooooh."

Now I see why it's hidden by default!

**Comment by netromdk** [comment]
Why?

**Comment by limpkin** [comment]
@ghalfacree yep... we're indeed ironing out its bugs!

**Comment by ghalfacree** [comment]
> Why?

Why do I see that it's hidden by default, you mean? I wrote that before I saw your post, and was referring to the fact that it didn't support all types of SSH key yet - but if it is _supposed_ to support all types of SSH key, then I _don't_ know why it's hidden. Other than being shiny and new and, as @limpkin says, still a little buggy!

**Comment by ghalfacree** [comment]
@raoulh: I didn't _think_ I had, but dropping to the terminal reveals that there's no bug after all: the key I was absolutely, 110% certain didn't have a passphrase on it... has a passphrase on it. Whoopsie!

Attempting to import the key at the terminal gives me a prompt to unlock the key (which is how I know I made a mistake), and I'm prompted to save it to the Mooltipass. Which seems to work just fine.

So... I'mma gonna go ahead and close this, bury my embarrassment deep, and try to forget it ever happened. Sorry, all - who could have guessed that the error message told me exactly what the problem was and how to fix it?(!)
