### ISSUE TITLE
UI element sizes are way off

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#311]
Version: probably the latest, but I can't tell because the problem is so bad. 
This is on Windows 10 (Spring 2018) with a 1080p screen and scaling set to 100%. 

![image](https://user-images.githubusercontent.com/10224994/42424554-06fdcb8c-82dc-11e8-9d15-55ea18814d08.png)

![image](https://user-images.githubusercontent.com/10224994/42424567-4464027a-82dc-11e8-85b5-0be6856671a1.png)

![image](https://user-images.githubusercontent.com/10224994/42424569-56325196-82dc-11e8-9b62-a33bdca8a241.png)

**Comment by limpkin** [comment]
I got this problem once on windows, then it disappeared...
I'd also like to get to the bottom of that one

**Comment by netromdk** [comment]
It looks like those labels have a fixed size and thus won't follow the font size.

**Comment by limpkin** [comment]
@NoahAndrews  could you try the following:
- go to C:\Users\YOURUSER\AppData\Local\Programs\Moolticute
- right click on moolticute.exe, properties
- click on compatibility tab
- click on change high dpi settings
- enable the "program DPI" > "use this setting to fix..."
- close and re-open moolticute
- if that doesn't work, head to the same tab and change the "Use the DPI that's set...." from "I signed in to windows" to "I open this program"

Please let us  know if it works :)

**Comment by raoulh** [comment]
@NoahAndrews Could you try to start `moolticute.exe` with the argument:
`moolticute.exe -platform windows:dpiawareness=0` and tell us if that works?

Thanks

**Comment by raoulh** [comment]
@NoahAndrews Could you also try this test build please:
https://mooltipass-tests.com/mc_betas/v0.18.9-testing/

**Comment by NoahAndrews** [comment]
The issue went away by itself, so I can't really verify whether the other things would fix it :/

**Comment by NoahAndrews** [comment]
I'm going to reinstall 0.18.1 to see if it shows itself again. If I can get it to consistently reproduce I'll try the other things.

**Comment by NoahAndrews** [comment]
Reinstalling did not re-introduce the problem, unfortunately.

**Comment by limpkin** [comment]
didn't see this problem appear again either... closign the issue
