### ISSUE TITLE
Default export folder

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#312]
should we change it to the user home folder?

**Comment by alanrick** [comment]
Don't mind where it is for the very first prompt as long as once used it sticks to that (last-used) folder.
I definitely don't want my mooltipass files or backups exported to the _download_ or _home_ directories which are automatically backed up to the Cloud. 

I use a dedicated directory for my mooltipass exports

**Comment by netromdk** [comment]
Agreed, I do the same thing. It doesn't currently remember the directories, and it should also for import etc.
