### ISSUE TITLE
Silently failing on too long password

### ISSUE THREAD

**Issue by NicoHood** [mooltipass/moolticute#313]
I am using moolticute 0.18.1 with my mooltipass mini.

I entered the credential management mode, changed a password of one of my logins, saved the entry and the whole thing to the mooltipass. 

The password was longer than 31 characters and NOT safed. There was no typing limit in the gui, nor any warning that the safing was not successful. This is critical, as I could have lost my password now (and in this case it was one that you cannot easily recover). Luckly I never trust the app, and did a backup in a texteditor, but that is not a good feeling, right?

**Comment by netromdk** [comment]
Thank you for reporting the issue, @NicoHood. I've pushed a fix so there's a maximum length on the password input field, just like there is in the add credential field.
