### ISSUE TITLE
Moolticute seems to claim non-MP devices that are USB HID

### ISSUE THREAD

**Issue by kbembedded** [mooltipass/moolticute#315]
Moolticute 0.18.7 on Windows 7 (have not tested other OSes) seems to claim a non-mooltipass device, not letting any other application use it.

I have a "Silicon Labs USB Debug Adapter" that was not being recognized by the Silicon Labs tools, until the moment I killed moolticute.exe and moolticuted.exe.  The daemon should only ever be attaching to MP devices.  Below is what the USB Debug Adapter identifies as:

Bus 002 Device 003: ID 10c4:8044 Cygnal Integrated Products, Inc. USB Debug Adapter

Let me know if there is any further information needed.

**Comment by raoulh** [comment]
Could you please test with this build and tell us if that works for you?
https://mooltipass-tests.com/mc_betas/v0.19.1-testing/
thanks

**Comment by kbembedded** [comment]
0.19.1-testing in Windows 7 does appear to have resolved the issue.  Thanks!
