### ISSUE TITLE
Updating/reinstalling in place no longer works for me

### ISSUE THREAD

**Issue by NoahAndrews** [mooltipass/moolticute#316]
It used to be that I could update Moolticute in-place without rebooting. I'd run the update installer and everything would just work.

Now, I get this error, which I can fix by rebooting my computer and deleting the moolticute.exe file:

![image](https://user-images.githubusercontent.com/10224994/42547449-2bfcd116-8490-11e8-8ad1-3fdfebde9394.png)

I've verified that the moolticute.exe and moolticuted.exe processes are not running at install time.

**Comment by NoahAndrews** [comment]
Here's all that comes up (but it's not actually the moolticute.exe file)

![image](https://user-images.githubusercontent.com/10224994/42727153-548b2eb6-876f-11e8-8009-bd13963dc567.png)

**Comment by limpkin** [comment]
waiting for @raoulh to answer that one

**Comment by raoulh** [comment]
Process hacker does not show something useful unfortunately

**Comment by limpkin** [comment]
maybe @NoahAndrews was not lucky and the process was used by his AV?

**Comment by NoahAndrews** [comment]
My AV is Windows Defender (Windows 10), and I've reproduced the issue several times in a row across reboots and significant amounts of time. 

---- On Thu, 02 Aug 2018 04:16:32 -0400 notifications@github.com wrote ----

maybe @NoahAndrews was not lucky and the process was used by his AV?

**Comment by limpkin** [comment]
could you try disabling it when updating maybe?

**Comment by NoahAndrews** [comment]
Just got the latest update, didn't disable anything, installed fine. Closing for now.

**Comment by limpkin** [comment]
don't hesitate to re-open if it happens again.
