### ISSUE TITLE
Text too small in high resolutions (1920x1200)

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#317]
it's barely readable....

**Comment by 7022Andre** [comment]
@limpkin Were you able to fix this?
I am running v0.30.8 on Lubuntu 18.04.1 LTS and the text in the app is barely readable. Resolution is set to 1920x1080.

![moolticute](https://user-images.githubusercontent.com/23385321/51089061-ce0c9e00-171b-11e9-95a4-396d173bc6ec.png)
