### ISSUE TITLE
Release 20.2 breaks the command line interpreter

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#327]
I'd reinstalled 18.1 moolticute in order to use the command line version (mc-cli) so that I could read files from my moolticute without storing them on my pc, but the latest install of moolticute broke this again.
Here's the output: #310

**Comment by asashnov** [comment]
mc-cli tool is exactly the same in 0.18.1 and 0.20.2

The difference in moolticuted: in 0.20.2 as an answer to

` {"msg":"get_data_node","data":{"service":"topsecret.txt"}}`

it sends:

`{ "msg" :"progress"}`

Previous version (0.18.1) was sending:

`{"data": {"service": "topsecret.txt"}, "msg": "progress"}`

Seems this is the result of fixing #none (no issue were created for this problem) "segfault on Import large database on a slow CPU" where we had "data" value coming back and forth with all the content of an imported database.

**Comment by raoulh** [comment]
@asashnov thanks for the digging.

I fixed mc-cli, it will be included in the next release of moolticute. In the mean time, @alanrick you can get the mc-cli binary from https://calaos.fr/mooltipass/tools/

**Comment by alanrick** [comment]
Thanks for fixing. I can wait until it’s on github,
Alan

**Comment by alanrick** [comment]
just confirming that 0.21 (Windows) solves the problem.
Many thanks.
