### ISSUE TITLE
Release 20.2 missing AppImage

### ISSUE THREAD

**Issue by hbxu** [mooltipass/moolticute#330]
Looks like since 20.2 release, the AppImage is not being released anymore.

**Comment by suntorytimed** [comment]
@hbxu I think they just forgot to add the AppImage to the release. At least the test version is available on https://mooltipass-tests.com/mc_betas/v0.20.2-testing/

**Comment by limpkin** [comment]
we're currently completely changing the way we do our releases, I'm expecting this one to be fixed within days.

**Comment by limpkin** [comment]
appimage are pushed now :)
