### ISSUE TITLE
MacOS, "The Moolticute Daemon is Not Running"

### ISSUE THREAD

**Issue by simtomas** [mooltipass/moolticute#331]
Hi,

with the moolticute versions Moolticute-v0.18.7.dmg and Moolticute-v0.20.2.dmg
there is message "A connection to the Moolticute daemon could not be established."
stays for about 1 minute, until standard page with "Devices settings" etc. shows up.

With a old version (Moolticute-v0.12.7.dmg) the startup is instantaneous (i.e. downgrading to 0.12.7 solves the issue).

macOS version: 10.13.6

Here are the logs output when Moolticute is started from terminal:

$ /Applications/Moolticute.app/Contents/MacOS/moolticute
DEBUG: :0 - System locale:  QLocale(Lithuanian, Latin, Lithuania)
INFO: :0 - Trying to set language:  ":/lang/mc_lt.qm"
DEBUG: :0 - Selection changed
DEBUG: :0 - Db tracking is not available for fw < 1.2
WARNING: :0 - Failed to hide dock icon: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list"
INFO: :0 - Running  "/Applications/Moolticute.app/Contents/MacOS/moolticuted"   ()
INFO: :0 - Daemon started
DEBUG: :0 - Card meta data changed  ""  -  0  -  0
INFO: :0 - Checking software updates from  "https://api.github.com/repos/mooltipass/moolticute/releases"
DEBUG: :0 - "https://github.com/mooltipass/moolticute/releases/download/v0.20.2/Moolticute-v0.20.2.dmg"
DEBUG: :0 - Websocket connected
DEBUG: :0 - Sending cache files request
DEBUG: :0 - New message:  {"msg":"mp_connected"}
DEBUG: :0 - New message:  {"msg":"mp_connected"}
DEBUG: :0 - New message:  {"data":"Locked","msg":"status_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"keyboard_layout","value":146},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"lock_timeout_enabled","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"lock_timeout","value":60},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"screensaver","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"user_request_cancel","value":true},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"user_interaction_timeout","value":15},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"flash_screen","value":true},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"offline_mode","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"tutorial_enabled","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":false,"msg":"memorymgmt_changed"}
DEBUG: :0 - Selection changed
DEBUG: :0 - New message:  {"data":{"data_nodes":[],"login_nodes":[]},"msg":"memorymgmt_data"}
DEBUG: :0 - Selection changed
DEBUG: :0 - New message:  {"data":{"flash_size":8,"hw_serial":990,"hw_version":"v1.2_mini"},"msg":"version_changed"}
DEBUG: :0 - Setup db tracking
DEBUG: :0 - New message:  {"data":{"parameter":"screen_brightness","value":128},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"knock_enabled","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"knock_sensitivity","value":1},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"random_starting_pin","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"hash_display","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"lock_unlock_mode","value":1},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"key_after_login_enabled","value":true},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"key_after_login","value":43},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"key_after_pass_enabled","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"key_after_pass","value":40},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"delay_after_key_enabled","value":false},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":{"parameter":"delay_after_key","value":5},"msg":"param_changed"}
DEBUG: :0 - New message:  {"data":[32,172,25,16,123,179,199,28,103,4,240,153,16,245,183,152,180,69,222,157,224,245,177,130,94,201,160,236,24,229,212,144],"msg":"get_random_numbers"}
DEBUG: :0 - update seed:  QJsonArray([32,172,25,16,123,179,199,28,103,4,240,153,16,245,183,152,180,69,222,157,224,245,177,130,94,201,160,236,24,229,212,144])
DEBUG: :0 - Websocket disconnect
WARNING: :0 - QProcess: Destroyed while process ("/Applications/Moolticute.app/Contents/MacOS/moolticuted") is still running.
WARNING: :0 - Daemon exits with error code  9  Exit Status :  QProcess::ExitStatus(CrashExit)

There is a short pause after "DEBUG: :0 - Card meta data changed  ""  -  0  -  0"
and then about one minute pause is after 
"DEBUG: :0 - "https://github.com/mooltipass/moolticute/releases/download/v0.20.2/Moolticute-v0.20.2.dmg" line (before 
DEBUG: :0 - Websocket connected)

**Comment by limpkin** [comment]
@asashnov : could you take care of this after the appimage task? thanks!

**Comment by raoulh** [comment]
fixed
