### ISSUE TITLE
Notification system next steps

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#343]
- @deXol to investigate if #339 & #342 can realistically be implemented using native OS notification APIs
- future "standard" notifications (device disconnected, please unlock device...) to be implemented using native OS notification APIs
- mc-cli to add a "mc_cli_version" key to the get credential message

**Comment by raoulh** [comment]
Keep in mind that we need:

- Windows notifications using toast api for windows >= 8
- Something else on windows 7? (that's a question to resolve)
- macOS notifications
- Linux freedesktop notifications

And with the following features:
- Text only
- Question
- Prompt with selectable items (subdomain thing)

**Comment by deXol** [comment]
**Windows**:

1. **Toast notifications api:**
https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/toast-notification-and-action-center-overview-for-windows-10/
According to this **ToastGeneric** contains the features which we need (editbox, combobox), but **only Windows 10 support**s them: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#handling-older-versions-of-windows
I couldn't find a lib for c++ which implemented these functions, the closest was WinToast, but even that only supports adding buttons to the notifications.
So we should implement the COM calls according to this page for the missing features: 
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl

2. **WinToast:**
https://github.com/mohabouje/WinToast
	- Using WinRT (WRL), the above mentioned Toast notifications api
	- Only works with MSVC2015 compiler
	- Implemented with win32 api COM calls
	- Can add buttons
	- No inputbox or combobox (but possible to extend it with these)
![wintoastexample](https://user-images.githubusercontent.com/11043249/45977251-4ce4aa80-c049-11e8-804f-83eb155e71b5.jpg)

	https://stackoverflow.com/questions/28609521/windows-10-toast-notifications-desktop-application
	
3. **SnoreToast**:
https://github.com/KDE/snoretoast
	- Binary file
	- Calling the binary with command line argument
	- Only for notifications
![domainsnoretoast](https://user-images.githubusercontent.com/11043249/45977517-2ffca700-c04a-11e8-854a-cd4f04d56dcc.jpg)


	
**Mac**:

1. **OS_X_Notification_Center**
https://wiki.qt.io/How_to_use_OS_X_Notification_Center
It is using NSUserNotification which is deprecated:
https://developer.apple.com/documentation/foundation/nsusernotification?language=objc
According to the following blog entry it is/was possible to add editBox (response) or combobox items (actions) for that.
https://blog.gaelfoppolo.com/user-notifications-in-macos-66c25ed5c692

I haven't found a C++ solution for **Linux** yet.

**Global solution**:
It is possible to use **QSystemTrayIcon** object for displaying a notification with showMessage function on every platform like this:
Windows:
![systraymessage](https://user-images.githubusercontent.com/11043249/45978325-5d4a5480-c04c-11e8-992e-92c61ee6147c.jpg)
Mac:
![systraymessagemac](https://user-images.githubusercontent.com/11043249/45978902-b8c91200-c04d-11e8-9eef-ea6b71dc729d.png)

**Comment by limpkin** [comment]
thanks for the great work!
Maybe @raoulh can let us know if he found anything else?

**Comment by raoulh** [comment]
Some thoughts:

**Windows 10:**

We need to fork https://github.com/KDE/snoretoast and add the required options for buttons and so. As the binary needs to be built using msvc (MC is built using mingw) we cannot put the code inside MC.

**Windows < 10:**

We need to develop a fallback for that. With a custom QDialog and such.

**macOS:**

It's ok the api allows us to do everything

**Linux:**

We need to follow the freedesktop specs: https://developer.gnome.org/notification-spec/
It uses DBus, so everything can be done using QDBus. Some example of how to do it here: https://github.com/KDE/snorenotify/tree/master/src/plugins/backends/freedesktop_backend

**Comment by limpkin** [comment]
so except win10... nothing with native multiple selection support then? (subdomain thingy)

**Comment by raoulh** [comment]
@limpkin linux and macos suports them too

**Comment by raoulh** [comment]
![image](https://user-images.githubusercontent.com/1115950/45998527-6ca8bc80-c0a3-11e8-8cc8-6e1873b2289e.png)

This is on Linux with latest chrome and our extension

**Comment by alanrick** [comment]
“Which” not “What” domain. 😎
Looking forward to this feature.

**Comment by deXol** [comment]
I forked SnoreToast and extended it with the textbox and buttons functionalities:
https://github.com/deXol/snoretoast
I added a new eventhandler from http://www.naughter.com/toastpp.html for the textbox. (it is not supported by MSVC, there is .net interface only for that).
Also added usage for the new options and currently I print to the standard output the user choices and planning to process this on MC GUI side.

### Examples:
**Buttons**:
SnoreToast.exe -t "Subdomain Detected!" -m "Which domain do you want to store?" -b "domain.tld;subdomain.domain.tld" -p AppIcon_32.png -w
![addbuttons](https://user-images.githubusercontent.com/11043249/46248045-52107380-c414-11e8-992d-b32ec3356a7d.jpg)

**TextBox**:
SnoreToast.exe -t "Empty Login is Detected!" -m "Please provide your username:" -tb -p AppIcon_32.png -w
![addtext](https://user-images.githubusercontent.com/11043249/46248118-5c7f3d00-c415-11e8-928a-05ad5ea039c8.jpg)

**Comment by raoulh** [comment]
Good job

**Comment by limpkin** [comment]
excellent job from @deXol !
