### ISSUE TITLE
Add moolticute install folder to windows path

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#345]
... in order to use mc-cli from the command line.

**Comment by raoulh** [comment]
nope a path is a path ;)

**Comment by limpkin** [comment]
so we're gently scr*wed?

**Comment by raoulh** [comment]
I have a lot of other programs on windows where you need to first cd to_the_path to execute commands... That's windows...

Also it's never a good idea to change the user PATH variable on windows. It has drawbacks and can break things...

Something that could be done maybe, is installing a .bat file and a shortcut in start menu to start a cmd.exe that has the PATH changed with inclusion of moolticute folder.

**Comment by limpkin** [comment]
or could we put mc-cli into a separate folder and add that folder to the PATH?

**Comment by raoulh** [comment]
Yes we could do that too

**Comment by limpkin** [comment]
seems a nice task for @asashnov then :)

**Comment by limpkin** [comment]
though to add to the windows path we need admin rights, right @raoulh ?

**Comment by raoulh** [comment]
I'm not sure, you can also set env var for the currrent user... so maybe not

**Comment by limpkin** [comment]
what's the current status of that one @deXol ? why was it reverted?

**Comment by deXol** [comment]
> 
> 
> what's the current status of that one @deXol ? why was it reverted?

hmm I think this was by mistake, the fix was on my master branch, and was reverted on a develop branch after a sync.
Will put it on a develop branch, and create a PR.

**Comment by limpkin** [comment]
right!
IIRC we still need to modify the installation process to put mc-cli inside that created forlder, right @raoulh ?

**Comment by raoulh** [comment]
Yes, I'll do that before the next prerelease

**Comment by limpkin** [comment]
gentle reminder for @raoulh
