### ISSUE TITLE
Moolticute spams update dialogs

### ISSUE THREAD

**Issue by uniacke1** [mooltipass/moolticute#350]
If moolticute has an update dialog open that is ignored or not acted on, (eg office computer left on over weekend) it will continue to spam prompts to update.

It should only ever show a single one at a time.

**Comment by raoulh** [comment]
@deXol Could you convert this dialog to use the new notification system please?

**Comment by deXol** [comment]
@raoulh Yes, should it be done before fixing and merging the system notifications or after?

**Comment by limpkin** [comment]
he won't merge before it's done :P

**Comment by raoulh** [comment]
You can include that into the same pr #348 
thanks
