### ISSUE TITLE
Feature Request: Search known compromised passwords / blacklist

### ISSUE THREAD

**Issue by listerr** [mooltipass/moolticute#357]
Recently I have received a number of spams telling me I am certainly doomed because my account has been "hacked" - these emails include a low security password I used a number of years ago - they've got this password from lists of known compromised sites.

I would like to search my passwords for everywhere this password might have been used, so I can changed these old passwords, and to prevent them being used in future.

Maybe this could be a one-off utility rather than a feature in the existing app, since anything that supports mass decrypting of the passwords in order to search for the password is probably bad, though I don't mind hitting the button for "approve on device" for each password or group of passwords.

**Comment by limpkin** [comment]
I would love to implement that feature.... but a few tricky points come to mind:
- bundling quite a large file within moolticute
- classifying passwords as "simple" or "compromised" or "both", in the case a user has "carots" as a password
- legal issues regarding how these password lists were obtained

**Comment by listerr** [comment]
Hi,I am not suggesting that the known compromised password lists be included. The spammer has sent emails with the plain text password included. "Haha! Your password is.... Pay me $800 in btc or we'll tell everyone about your porn, we 0wn j00!" (hint: it's not and never was my email password!) This is a genuine password I used a few years ago for "low security sites that insist on registration for some forum or other" so it must have come from a known compromised password list like Linux mint.I'd like to just search all the stored passwords for anywhere else I might have used the same password, so that I can change it. Currently this is not possible, and going through hundreds of them one at a time doesn't scale either. Rob On 24 Oct 2018 10:34, Mathieu <notifications@github.com> wrote:I would love to implement that feature.... but a few tricky points come to mind:
bundling quite a large file within moolticuteclassifying passwords as "simple" or "compromised" or "both", in the case a user has "carots" as a passwordlegal issues regarding how these password lists were obtained

**Comment by limpkin** [comment]
oh... checking the credential list to check if a given password is used definitely is something we could implement easily.

**Comment by limpkin** [comment]
duplicate with #402
