### ISSUE TITLE
Lock/Unlock Feature Ctrl + Alt + Del/ Win +L not working

### ISSUE THREAD

**Issue by jmoreton** [mooltipass/moolticute#363]
When using the the lock unlock feature with Ctrl + Alt + Del/ Win +L option
Removing the card doesn't issue a Win +L and lock the computer.
Inserting the card and entering the pin also doesn't issue Ctr l+ Alt+ Del.
This used to work with MooltiApp.

Moolticute Version: 0.21.0
Firmware: v1.2_mini
OS: Windows 10 Pro 1803

**Comment by limpkin** [comment]
Hello,

Could you double check you still gave the _unlock_ service?

Thanks

**Comment by jmoreton** [comment]
Yes I have the _unlock_ service as can be seen by the attachment
![_unlock_](https://user-images.githubusercontent.com/29331290/48073060-cbe70a00-e1d5-11e8-83fd-490fda005c39.png) otherwise i'm not sure what you mean.

**Comment by limpkin** [comment]
Right, does any other lock unlock option work or is it just this one?

**Comment by alanrick** [comment]
I also have this problem. Removing the card no longer sends a Win L command to my pc.
I tried changing the Windows "Dynamic Lock" setting to on, and selecting Mooltipass keyboard as the device, but Windows forgets the setting.
It's as if Windows only recognizes bluetooth devices for the Dynamic Lock, and ignores other devices despite being offered in the list of devices.

BTW: The reverse (inserting the card to unlock Windows) does work.

**Comment by alanrick** [comment]
Aha sorry.  I'd tested with `Enter + Password` which deliberately doesn't lock.
I retested with `Ctrl + Alt + Del/ Win +L` and it _did_ issue the command and _did_  lock my pc. Same for 
But `Enter + Pass /  Win + L`  _did not._

**Comment by alanrick** [comment]
Hmmm... maybe the settings aren't being saved. Now I can have:
`Ctrl + Alt + Del/ Win +L `and it _did not_ issue the command and _did not_ lock my pc. 

I also notice that when I select `Ctrl + Alt + Del/ Win +L ` then the `Reset` and `Save to device` buttons are _not_ displayed but for all other combo dropdowns both buttons _are_ displayed.
And pressing` Save to device` does not make the buttons disappear (which I'd expect).

**Comment by jmoreton** [comment]
I can use Password/ Win+L instead having to manually press CTRL+ALT+DEL. 
When using Ctrl + Alt + Del/ Win +L setting, CTRL+ALT+DEL doesn't seem to be issued on card insert after entering the pin but issues a WIN+L  on card remove.
Is this profile meant to issue the username or password, if  not can there be one that does CTRL+ALT+DEL+ Password+Enter/Win+L

**Comment by limpkin** [comment]
we found the bug!

**Comment by limpkin** [comment]
wiill be released in v0.30.2
