### ISSUE TITLE
Minor text improvement

### ISSUE THREAD

**Issue by alanrick** [mooltipass/moolticute#365]
While entering credential mode the following message is displayed:
` Loading credentials for eated`

I think it is meant to be
`Loading credentials for consumption`

or, IMHO
`Loading credentials `

**Comment by limpkin** [comment]
Hello!

In theory during that process it should display your services one after the
other right?

**Comment by alanrick** [comment]
not sure if addressed to me....
Normally it displays subliminally. But with bad wifi it is visible.
My issue is with the word **eated**

**Comment by alanrick** [comment]
😳 sorry - I failed to reproduce this. It doesn't get stuck anymore. Perhaps I had a bad cable.

But even though I don't have a credential called "eated" I strongly suspect the message is related to the name of one of my credentials and is not caused by moolticute.
E.g. `Loading credentials or github` is one message flashed momentarily while entering credential mode.
