### ISSUE TITLE
Selected File is Another User's Backup

### ISSUE THREAD

**Issue by AtosNicoS** [mooltipass/moolticute#375]
Hi,

I own two mooltipass, one at home, one at work, with two users: one for work, one for home. Last year I restored my home database onto the work mooltipass. Since the passwords are older now, I wanted to update them. I made a backup using moolticute and tried to restore it on the work mooltipass. I get the error `Selected File is Another User's Backup`.

The Smartcard used for decrypting the backup should be idential, so I dont understand the problem here. In case my mooltipass at home breaks/is lost for some reason, how can I restore the backup properly? I fully rely on both devices, so I hope you can help me.

**Comment by limpkin** [comment]
Hello,

Could you let us know which devices they are (original/mini)? 
There is an edge case with older devices where this would happen.
There are 2 workarounds:
- use a "MooltiApp compatible file"
- use the same card to generate the backup and import it

**Comment by AtosNicoS** [comment]
I m using two mooltipass mini.

**Comment by limpkin** [comment]
How are the two users setup? did you use the clone feature? Did you use to have a standard mooltipass?

**Comment by AtosNicoS** [comment]
I originally had a large mooltipass. Then I've imported the database on the home mini and later a backup of the home mini on the work mini. This was all done using the mooltipass app, not moolticute. Now I use moolticute.

If there are incompatiblilities, could you please explain me when they occur? Because if some day my device gets lost I need a working backup on a new device.

**Comment by limpkin** [comment]
In short, this is due to some IDs stored in your card.
With the standard Mooltipass, when cloning a card, a new ID was generated for the cloned card.
Since the mini came out, the original card ID is cloned into the new card.
Moolticute is therefore confused by this "unknown" ID. Simplest solution I guess is for you to send me your full address and we'll have new cards shipped to you. 
Simply then clone a given card with a mini, and throw all your other cards.

Alternatively, there's a more complex (and risky) procedure (which doesn't require new cards) which involves deleting your user on one of your mini with all your cards but one, then doing the cloning process again.

**Comment by AtosNicoS** [comment]
Okay I understand. Can't I just delete my card with the unknown id and clone it again?

**Comment by limpkin** [comment]
you can reset the unknown cards in the Advanced tab (ctrl-shift-f2).
Regarding loss of device, it's extremely clear in our user manual that backups are recommended.

**Comment by AtosNicoS** [comment]
I did backups! My cards were jusr useless because of this bug/design change. How should I know that?

The Advanced menu only has a ssh key tab setting and a csv file import/export function. No option to delete a card. I am using the latest version from the website: 0.21.0 https://www.themooltipass.com/setup/

**Comment by limpkin** [comment]
You're indeed right, my apologies... but as long as you have the card that was used to make this backup, nothing is lost (even thought it'd require some code on our side).  
the unknown card needs to be inserted for the option to appear

**Comment by AtosNicoS** [comment]
The card is inserted. I think the problem is, that the card is known by the mooltipass, but the "hidden id" you mentioned is still incorrect. So I need to delete a known card from the device.

**Comment by limpkin** [comment]
I'm not sure to follow you then.
If that's the case, you'll need to delete the user & card (through the erase item in the settings menu).
Make sure to make backups of your DB with your other card that you will not erase

**Comment by AtosNicoS** [comment]
Holy shit, what a struggle and risk. It should work now. I am not happy about this.

**Comment by limpkin** [comment]
Yep, we apologize for that...
This particular design decision was made 3 years ago because it was (and still is) the best choice. We knew this particular edge case could exist but were confident we could help users to solve this situation.
