### ISSUE TITLE
Service or Site name, sub-domain cut (lost)

### ISSUE THREAD

**Issue by simtomas** [mooltipass/moolticute#378]
Hi,

version 0.30 (also 0.30.1) cut subdomain from "Service or Site name" when saving new credentials.
![subdomain](https://user-images.githubusercontent.com/42533577/49002249-c1ca8280-f167-11e8-9ae3-449b089a4aaa.png)

subdomain.test.com would be saved on Mooltipass as a "test.com".
It works correctly with version 0.21.0

macOS version.

**Comment by limpkin** [comment]
wow, we didn't notice that one...
@deXol : could you replicate the extension behavior for this? in case of subdomain.domain.tld, store domain.tld when subdomain selection is disabled and store subdomain.domain.tld when it is enabled?

**Comment by limpkin** [comment]
fixed with #379
