### ISSUE TITLE
Support of PT keyboard layouts

### ISSUE THREAD

**Issue by aaubry** [mooltipass/moolticute#382]
I've just received my mooltipass, and was disapointed to find out that my keyboard layout (pt-PT) is not supported. Is it possible to add a new keyboard layout ? If so, what are the steps that are required ? I am willing to send a pull request but I need some guidance to get started.

**Comment by limpkin** [comment]
Hello,  
Do you mean portuguese? If so there's a quick fw update I can generate for you.

**Comment by aaubry** [comment]
Yes, I mean Portuguese, Portugal variant.

**Comment by limpkin** [comment]
that's fairly easy then... could you just send me an email to support[at]themooltipass dot com with your unit's serial number and order number?
I'll then have a firmware update sent to you.

**Comment by aaubry** [comment]
Ok, I have sent the email. Thanks
