### ISSUE TITLE
MCC#2 error on import

### ISSUE THREAD

**Issue by dirkx** [mooltipass/moolticute#396]
On importing a few 100 passwords - one gets a MCC#2 error without much extra information as to what the issue is.

**Comment by limpkin** [comment]
could you look at the daemon logs and let us know its output?

**Comment by dirkx** [comment]
In below - XXXX signals an actually sensible entry/valid value; while “” is really ‘empty’ — i.e \0/zero len.

…skipped about 300 repetitive entries:

DEBUG: :0 - Queing password change as well
DEBUG: :0 - MMM Save: tackling “XXX" for service “XXX" at address ""
DEBUG: :0 - New login “XXX" for service “XXX" at address ""
DEBUG: :0 - Creating new service "netgate" in DB
INFO: :0 - Adding parent node "netgate"
DEBUG: :0 - Adding parent node before “XXXX"
DEBUG: :0 - ... and after “XXXX"
INFO: :0 - Adding child “XXX" with parent “XXXX" to DB
DEBUG: :0 - Queing password change as well
INFO: :0 - Checking database...
WARNING: :0 - Orphan child found: "" at address: ""
WARNING: :0 - Orphan child found: “XXX" at address: ""
WARNING: :0 - Orphan child found: "" at address: ""
WARNING: :0 - Orphan child found: "" at address: ""
WARNING: :0 - Orphan child found: “XX" at address: ""
WARNING: :0 - Orphan child found: "" at address: ""
about 300 more of these
WARNING: :0 - Orphan child found: “XX" at address: ""
WARNING: :0 - Orphan child found: “XXX" at address: ""
WARNING: :0 - Orphan child found: "" at address: ""
DEBUG: :0 - Number of parent orphans: 0
DEBUG: :0 - Number of children orphans: 141
DEBUG: :0 - Number of data parent orphans: 0
DEBUG: :0 - Number of data children orphans: 0
INFO: :0 - Errors were found in the database
CRITICAL: :0 - Error in our local DB (algo PB?)
INFO: :0 - "Exiting MMM"
INFO: :0 - MMM exit ok
DEBUG: :0 - > Retry command: "MOOLTIPASS_STATUS (0xb9)"
DEBUG: :0 - JSON API recv: {
"msg": "get_random_numbers"
}

INFO: :0 - "Get random numbers from device"
DEBUG: :0 - > Retry command: "MOOLTIPASS_STATUS (0xb9)"
WARNING: :0 - > Retry command: "MOOLTIPASS_STATUS (0xb9)" has failed too many times. Give up.
DEBUG: :0 - > Retry command: "GET_RANDOM_NUMBER (0xac)"
WARNING: :0 - Wrong answer received: "MOOLTIPASS_STATUS (0xb9)" for command: "GET_RANDOM_NUMBER (0xac)"
WARNING: :0 - Wrong answer received: "MOOLTIPASS_STATUS (0xb9)" for command: "GET_RANDOM_NUMBER (0xac)"
WARNING: :0 - Wrong answer received: "MOOLTIPASS_STATUS (0xb9)" for command: "GET_RANDOM_NUMBER (0xac)"
INFO: :0 - Random numbers generated ok
WARNING: :0 - Command queue is empty!
WARNING: :0 - Packet data size: 32 data: “

**Comment by limpkin** [comment]
another user recently got this error... would you have a csv file we could use to reproduce the problem? 
Sorry it took us so long to get to that... as we're working on the next gen device

**Comment by limpkin** [comment]
any update?
