### ISSUE TITLE
Max length 31 -- unfortunate number

### ISSUE THREAD

**Issue by dirkx** [mooltipass/moolticute#397]
The current max-length for imported passwords is around 31? chars.

Which is a bit unfortunate - as a fair number of professional datarooms (virtual faults) used in finance set 32 and 36 char (US-ASCII typically; often not allowing any special chars 0,O,l and 1s) routinely.

Would be nice to make this significantly larger or a configurable setting.

**Comment by limpkin** [comment]
I'm afraid this is a device limitation (lifted on the next gen to 64 unicode bmp chars)...
I'll close this issue as this is related to the device and not the SW.
