### ISSUE TITLE
Text too small (related to #317)

### ISSUE THREAD

**Issue by 7022Andre** [mooltipass/moolticute#401]
@limpkin Were you able to fix this in #317 
I am running v0.30.8 on Lubuntu 18.04.1 LTS and the text in the app is barely readable. Resolution is set to 1920x1080.

![moolticute](https://user-images.githubusercontent.com/23385321/51089061-ce0c9e00-171b-11e9-95a4-396d173bc6ec.png)

**Comment by limpkin** [comment]
did you use the appimage or our repository to install moolticute?
We are supposed to have fixed this issue... did you set a custom font on Lubuntu?

**Comment by 7022Andre** [comment]
I am using the appimage. No custom font is set.

**Comment by limpkin** [comment]
Could you uninstall it and install it using our repository? If I'm not mistaken you should be able to :)

**Comment by 7022Andre** [comment]
After restart, the text in the app is now readable with external monitor and laptop lid closed. I'll close this issue.
Thanks for the quick reply!

**Comment by limpkin** [comment]
that's wonderful :)
