### ISSUE TITLE
Unicode BMP support for BLE

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#410]
**Implementing support for Unicode BMP on BLE**
With using the MessageProtocol class added in #383.

In message protocol I create two functions for QString to ByteArray and backward conversion.
For mini/classic it is using utf8 encoding to store and display strings (service, login, pwd... etc) on the device.
I am generalizing these conversions which are called in MPDevice and MPNode.
QChar is stored as Unicode BMP, so it is straightforward to get the Unicode BMP character code and add it to a ByteArray.

**Comment by limpkin** [comment]
is it done that one? :)

**Comment by deXol** [comment]
yes, it is done
