### ISSUE TITLE
Bluetooth detection, communication for BLE

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#414]
### Qt  Bluetooth
Global solution for Qt
Easy usage for monitoring/scanning the bluetooth connections. (bluetooth\btscanner Qt example project)
Usage: QT += bluetooth
![kep](https://user-images.githubusercontent.com/11043249/53365355-4aacb200-3941-11e9-91e6-2c5292bb0ef5.png)

These are the supported platforms: https://doc.qt.io/qt-5.9/qtbluetooth-index.html
On windows only WinRT is supported, so we could use it only with MSVC compiler. (https://forum.qt.io/topic/97148/qt-bluetooth-module-is-non-functional/7)

> Despite there not being a Win32 port yet, the WinRT backend is automatically used if the win32 target platform supports the required WinRT APIs. Minimal requirement is Windows 10 version 1507 with slightly improved service discovery since Windows 10 version 1607. Therefore Windows 7 and 8.x targets are excluded.

With MinGW only a dummy backend is started, and unable to use the features of Bluetooth module:
![kep](https://user-images.githubusercontent.com/11043249/53365417-7c257d80-3941-11e9-9f96-e2d4bd9bdfb1.png)

### HIDAPI:
https://github.com/signal11/hidapi
According to the description it can be used for USB and Bluetooth communication:

> HIDAPI is a multi-platform library which allows an application to interface
> with USB and Bluetooth HID-Class devices on Windows, Linux, FreeBSD, and Mac
> OS X.

This is currently used for USB communication.
Haven't seen any example codes for Bluetooth usage.
I will only be able to try the BLE with bluetooth connection, because do not have any HID device with BT.

### Windows:
For Bluetooth detection I checked bluetoothapis.h: https://docs.microsoft.com/en-us/windows/desktop/api/bluetoothapis/
With some modifications to the following code 
- https://github.com/joric/bluetooth-battery-monitor/blob/master/misc/bt_classic_test.cpp

I was able to monitor every bluetooth device connected to my PC:
![btmonitor](https://user-images.githubusercontent.com/11043249/53367836-73d04100-3947-11e9-8c01-a606e8529c54.png)

According to the [following thread](https://social.msdn.microsoft.com/Forums/ie/en-US/bad452cb-4fc2-4a86-9b60-070b43577cc9/is-there-a-simple-example-desktop-programming-c-for-bluetooth-low-energy-devices?forum=wdk) it is possible to subscribe to a bluetooth device events, for this it needs to use the device's uuid. (wasn't able to test, because could not retrieve this device uuid for my phone)

### Linux:
QtBluetooth is working, however there are some limitation.
When I tried the example btscanner I listed the connected device's MAC addresses, but during getting details it displayed the following error:
![kep](https://user-images.githubusercontent.com/11043249/53366514-11297600-3944-11e9-919f-44a1f7857528.png)

> On Linux, Qt Bluetooth uses a separate executable, sdpscanner, to integrate with the official Linux bluetooth protocol stack BlueZ. BlueZ is available under the GNU General Public License, version 2.

Regarding HIDAPI the daemon currently is using libusb, but according the [description](https://github.com/signal11/hidapi):

> Linux/FreeBSD/libusb (libusb/hid.c):
> This back-end uses libusb-1.0 to communicate directly to a USB device. This
back-end will of course not work with Bluetooth devices.

An alternative solution is hidraw:

> Linux/hidraw (linux/hid.c):
> This back-end uses the hidraw interface in the Linux kernel.  While this
> back-end will support both USB and Bluetooth, it has some limitations on
> kernels prior to 2.6.39, including the inability to send or receive feature
> reports.  In addition, it will only communicate with devices which have
> hidraw nodes associated with them.  Keyboards, mice, and some other devices
> which are blacklisted from having hidraw nodes will not work. Fortunately,
> for nearly all the uses of hidraw, this is not a problem.

### Mac:
Qt Bluetooth is supported on Mac. Tested with btscanner:
![screen shot 2019-02-26 at 10 45 13 pm](https://user-images.githubusercontent.com/11043249/53448770-7d75a980-3a18-11e9-9995-cb78692db661.png)

HIDAPI is using IOHidManager on Mac. (Currently used for USB communication)
There are supported Bluetooth related defines:

> #define kIOHIDTransportBluetoothValue           "Bluetooth"
> #define kIOHIDTransportBluetoothLowEnergyValue  "BluetoothLowEnergy"

**Comment by raoulh** [comment]
Hey @deXol 

Some comments regarding your research.

### HIDAPI
HIDAPI is small "glue" lib, we are doing pretty much the same but directly implemented in MC. There is no need for this lib as it adds a lot of code that is useless for us.

### Linux
On linux I used libusb because the hidraw api was not working at all for me. I had a local branch with some changes that I just pushed on github (https://github.com/mooltipass/moolticute/tree/dev/raoulh/linux_hidraw). It's a rewrite of the MPDevice_linux backend to use hidraw api instead of libusb. As I said it's not working, but it would be very nice if we could stay away from libusb... Maybe you could take a look at it...

### Qt Bluetooth
I don't think we would need that. if we stay with HID only, there is no need to directly use any bluetooth apis. Also for the pairing, we can rely on the OS for that. It's already done like that for mouses/keyboards right?

**Comment by deXol** [comment]
Hello @raoulh,

I am checking your hidraw implementation, I tried a **0xD9: Lock Device**, but the message wasn't received by the mini.
I found an example for hidraw: https://github.com/torvalds/linux/blob/master/samples/hidraw/hid-example.c
With some modifications I was able to send the Lock device message with the C code and read the response:
![kep](https://user-images.githubusercontent.com/11043249/53699844-c51b7d00-3dec-11e9-9a0e-fc19b3af6d5b.png)

Also checked **0xDA: Get Mooltipass Mini Serial**, which also got the response:
![kep](https://user-images.githubusercontent.com/11043249/53699875-03b13780-3ded-11e9-8cf3-4496dbceed2c.png)

I added a plus 0x00 byte before the messages in your code and it was also received by the mini. I found this in the [following documentation](https://www.kernel.org/doc/Documentation/hid/hidraw.txt):

> write()
> --------
> The write() function will write a report to the device. For USB devices, if
> the device has an INTERRUPT OUT endpoint, the report will be sent on that
> endpoint. If it does not, the report will be sent over the control endpoint,
> using a SET_REPORT transfer.
> 
> **The first byte of the buffer passed to write() should be set to the report
> number.**  If the device does not use numbered reports, the first byte should
> be set to 0. The report data itself should begin at the second byte.

So it is sending it now, but the activated signal still havent received by the readsocket, so I am investigating that.

> Qt Bluetooth
> I don't think we would need that. if we stay with HID only, there is no need to directly use any bluetooth apis. Also for the pairing, we can rely on the OS for that. It's already done like that for mouses/keyboards right?

Yes I think pair is handled by the OS, but still need a callback for detecting if a device is connected.

**Comment by raoulh** [comment]
Nice work @deXol ! Damn, I forgot about that 0x00 at the beginning to set the report number...

Could you try to port the current linux backend code to this then? So we can remove libusb entirely...

**Comment by deXol** [comment]
I'm working on it currently.
I ran into an issue during detecting MINI with hidraw, because it is finding two hidraw path for the it currently I trying to write the messages to both. (same issue here: https://forum.pjrc.com/threads/46214-Which-of-the-two-quot-hidraw-quot-devices-is-my-RawHID)
It looks like need to open both and check if it is the correct one.
If I'm using only the RawHID, then it is working fine just like with libusb before.

However for UsbMonitor_linux.h I'm not sure if we can eliminate libusb.

**Comment by limpkin** [comment]
what's the current status of that one? implemented? :)

**Comment by deXol** [comment]
@limpkin : Well, hidraw is implemented, so I think it is on hold until the bt antenna.
