### ISSUE TITLE
Display correct device informations for BLE

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#415]
Display correct device informations for BLE in About tab:
![kep](https://user-images.githubusercontent.com/11043249/53595450-95c30100-3b9d-11e9-9718-45889c9c0762.png)

With using the new [0x0003: Get Platform Info command](https://mooltipass.github.io/minible/protocol) the serial number is available and also add Main and Aux MCU version for BLE.

**Comment by limpkin** [comment]
why is this is an issue? :D

**Comment by deXol** [comment]
Just created for tracking changes and this way I can commit to this ticket.

**Comment by limpkin** [comment]
oh ok :)
