### ISSUE TITLE
Using 'localhost' in WSClient.cpp depends on host system settings

### ISSUE THREAD

**Issue by mmajoor** [mooltipass/moolticute#420]
I had to struggle to get Moolticute operational on my Linux system. The browser apps seem to work, but MooltiCute could not connect to the daemon for some reason.
After some investigating I found the problem to be in the definition of WS_URI, which uses 'localhost'. This only works when the host system has defined the name localhost (like in /etc/hosts), which is not always the case (like in mine). Changing it to using 127.0.0.1 seem to resolve my issue.

//#define WS_URI                      "ws://localhost"
#define WS_URI                      "ws://127.0.0.1"

**Comment by raoulh** [comment]
That's actually not moolticute's fault. `localhost` must be defined to 127.0.0.1 or ::1 for ipv6.

Your system is not configured correctly.
