### ISSUE TITLE
Unable to connect to device after hidraw patch

### ISSUE THREAD

**Issue by egalanos** [mooltipass/moolticute#423]
Using Fedora 29 with all updates applied.

Head 5a3fe905e64502d7897d391dca6e5d24176c387c  works.

Head ccd4216326effb14996ed9ea11d7c257c8ba95f1 does NOT work. moolticute can't see my mooltipass mini.

**Comment by asashnov** [comment]
Could you please attach strace log?

```
$ ./Moolticute-x86_64.AppImage --appimage-extract

$ strace -f -s 120 -o ~/strace.log ./squashfs-root/AppRun 
```

**Comment by raoulh** [comment]
@egalanos Most likely you have an outdated udev rules installed. Please replace the actual one with this one which contains the updated rule:
https://github.com/mooltipass/mooltipass-udev/blob/master/udev/69-mooltipass.rules

**Comment by asashnov** [comment]
Another probably cause of the issue on Fedora: SELinux.

What's its status? Have you tried to turn it off?

**Comment by egalanos** [comment]
It's working now. I've confirmed that the problem was with the udev rules. Updating to latest version:

https://github.com/mooltipass/mooltipass-udev/blob/master/udev/69-mooltipass.rules

works. I previously had an older version of the udev rules from that same repository and they didn't work.

The udev rules listed in the moolticute README don't work either.

**Comment by raoulh** [comment]
Thanks for the report, I fixed the readme
