### ISSUE TITLE
Feature Request: More feedback when checking for updates

### ISSUE THREAD

**Issue by Didericis** [mooltipass/moolticute#424]
I'm running version `0.30.4` of moolticute on OSX, and was looking forward to the feature merged in here -> https://github.com/mooltipass/moolticute/pull/412. I tried pressing the "Check For Updates" button within the moolticute app, but I didn't get any sort of popup or text letting me know whether I was currently up to date. I don't think there's anything wrong with my installation, as I used the DMG provided at https://www.themooltipass.com/setup/,  so I'm assuming there just isn't any sort of feedback when pressing that button and you're already up to date. It looks like the DMG available for downloads at https://www.themooltipass.com/setup/ is still `0.30.4`, so I'm guessing any of the newer builds aren't available on OSX yet without building from source.

If that all is true, some basic feedback RE the result of checking for updates would be much appreciated. If that feature already exists and my machine just isn't working properly, let me know. Thanks.

**Comment by raoulh** [comment]
Hi,
something seems to be wrong on your side (network, firewall?) as the latest release is 0.30.8 https://github.com/mooltipass/moolticute/releases
All updates are checked and downloaded from github, the website is just a link.

About the HIBP feature, it's not yet in the stable branch, but if you want to give it a try, you can test at least the v0.40.1-testing version from github.

@limpkin you need to update the https://www.themooltipass.com/setup/ page!

**Comment by limpkin** [comment]
will do.

**Comment by limpkin** [comment]
everything looks ok to me, latest stable version for OSX is 30.4. It isn't 30.8 as we were working on fixing the dmg release system. a newer release for osx isn't planned for several weeks, except on our beta channel: https://betas.themooltipass.com/

**Comment by Didericis** [comment]
Thanks for the info, makes sense to me RE HIBP feature and why the current download is 30.4.

Sounds like the lack of any user feedback I got when clicking the "check for updates" button was expected behavior. Any chance you can add some feedback? For example, this is what happens when I check for macOS updates:

<img width="452" alt="Screen Shot 2019-03-23 at 9 54 39 PM" src="https://user-images.githubusercontent.com/6478250/54873878-7727e280-4db6-11e9-9ea6-49f4b59f27bc.png">
<img width="444" alt="Screen Shot 2019-03-23 at 9 56 50 PM" src="https://user-images.githubusercontent.com/6478250/54873889-945cb100-4db6-11e9-8dd4-25237d623f6a.png">

Some sort of feedback like that would be nice (timestamps or no timestamps). The way the UI is currently, I wasn't sure if the update request had actually gone through and I was actually up to date, or if something there had failed behind the scenes.

**Comment by raoulh** [comment]
@limpkin You are right about the latest macOS release...

As for the update feedback, that was removed unintentionally and it's a bug. Needs to be fixed
