### ISSUE TITLE
Quick File Access shows size rounded to 128 byte chunks

### ISSUE THREAD

**Issue by egalanos** [mooltipass/moolticute#429]
I uploaded a 40 byte file my mooltipass mini (to work around password 31 character limit) and the moolticute UI (using GIT head 22185438dff253d6d14db2d1b3ac58451787bff4) shows the file as being 128 bytes (and all other files being multiples of 128 bytes).

**Comment by limpkin** [comment]
Thanks for the report!

@deXol : If I'm not mistaken, to populate that list we scan the complete DB? IIRC the actual file size is stored in the first 4 bytes of the **encrypted** payload. Therefore I don't think we can display the actual file size (only the file size in our file system) on the current mini. For the next device, I'll make that field unencrypted.

**Comment by raoulh** [comment]
Actually the only place where a filesize is displayed in the file cache in the File management tab. And it uses the size of the encrypted nodes, so yes it is rounded to the node used in the storage.

https://github.com/mooltipass/moolticute/blob/master/src/MPDevice.cpp#L7302

For me we could remove that info from the file cache, it does not make really sense to display that anyway, and it leads to confusion...

**Comment by limpkin** [comment]
closing due to resources being allocation for the foreseeable future on the mini ble
