### ISSUE TITLE
setup download links need update

### ISSUE THREAD

**Issue by jaxxzer** [mooltipass/moolticute#436]
The links in the product setup guide [here](https://www.themooltipass.com/setup/) do not point to the latest release. Additionally the, link for the linux appimage is broken, because the appimage for 4.1.4 are is not available in the [deployment](https://github.com/mooltipass/moolticute/releases/tag/v0.41.4) (maybe a separate issue).

I suggest making a `stable` tag or release that is updated with each deployment. Then you can have a static link to github.com/moolticute/releases/stable.

**Comment by limpkin** [comment]
Thanks a lot for the report! I just updated the website :)
