### ISSUE TITLE
 Couldn't save credentials, please contact the support with moolticute's log

### ISSUE THREAD

**Issue by cwaazywabbit** [mooltipass/moolticute#456]
### Expected behavior
Credentials are saved normally.

### Actual behavior
Credentials are not saved and lost. An error occurs "Couldn't save credentials, please contact the support with moolticute's log"

### Step by step guide to reproduce the problem
1. unlock device / use it to login to something and keep it unlocked
1. using Moolticute, open Credentials Management / confirm on device
1. start adding credentials / don't save to device
1. let the session timeout / Credential Management will auto lock the session
1. unlock the device again / Credentials Management will auto unlock in Moolticute
1. click to save credentials now / you receive the following error and new credentials are lost
"Couldn't save credentials, please contact the support with moolticute's log"

### Operating System
Windows 10

### Mooltipass Extension
None

### Mooltipass Application
Moolticute 0.42.1

### Mooltipass Device
The Mooltipass Mini

**Comment by limpkin** [comment]
Hello! That's quite a corner case... Could you let us know in your opinion
what justifies letting the session timeout? This is something we left as is
thinking this would rarely happen. As far as I know you are the first one
to bring it up.

**Comment by cwaazywabbit** [comment]
Hi, to my understanding, the session timeout settings can be controled in Moolticute under "Device Settings" > "Inactivity" > "Lock after X minutes of activity".
By default, that is set to 60 minutes (AFAIR), but I find that's quite too long and I have set it to 5 minutes.

What justifies 5-10 minutes period of time, beside added security?

The session will then auto timeout and it it could happen while I am busy / getting busy doing something else. Losing the credentials that I have so far added and not saved is quite annoying in that case.

**Comment by limpkin** [comment]
What behavior would make sense for you? when you unlock your device, a prompt to go back to MMM and find your unsaved changes again?

**Comment by cwaazywabbit** [comment]
Whatever floats the boat as long as one doesn't lose unsaved changes. Is it securely possible?

**Comment by limpkin** [comment]
I doubt so.... will therefore close this issue
