### ISSUE TITLE
Description field is limited to 22 chars

### ISSUE THREAD

**Issue by cwaazywabbit** [mooltipass/moolticute#457]
### Expected behavior
Description field isn't limited or at least not limited to this very small length

### Actual behavior
Description field is limited to 22 characters only!

### Step by step guide to reproduce the problem
Try to enter any description in Moolticute for a record

### Operating System
Windows 10

### Mooltipass Extension
None

### Mooltipass Application
Moolticute 0.42.1

### Mooltipass Device
The Mooltipass Mini

**Comment by limpkin** [comment]
This is per design, and the first time this is brought up... How many would
you like?

**Comment by cwaazywabbit** [comment]
Here is the thing.

I see a device with 8mb storage + I see a JSON object, therefore, I see no reason to set limites in the first place!
The same logic applies to length of passwords, why set a max length of 31 characters by design?
Those who use 20 characters passwords can enjoy "more storage / more records" and those who would like to use a 64 length password, will just have to sacrifice a little bit.. after all, who really would like to scroll in a list of a thousand password??

For the record, I wasn't really going to use the "Description" field, but then again, I would like to use the device to store passwords for services that might not be public or well-known, i.e. internal URLs, Webapplications accessible using IPs, ... etc.. so how would I really be able to access those without storing the information somewhere in the device? storing them in a file is a bit too much, so I thought about storing the URL/path/whatever in the description field, that's when I noticed that it was limited to 22 chars only!

**Comment by raoulh** [comment]
As @limpkin said, it's per design and the storage database on the device itself implements it this way. There is no way to change that.
To save random data, you could use the file storage function. There you can save small files (max 10Kb size) of your choice.

**Comment by limpkin** [comment]
We are getting into the topic of database design, and therefore technical
choices.... And there are many factors at play.
In the meantime, why not use logins for url storage?

**Comment by cwaazywabbit** [comment]
By logins I take it you mean the "username" field, correct?
if that's the case, then I would then lose the flexibility of auto-filling the username.

I actually wish that there was a URL field without this limitation (at least, limited by the 8K which almost all browsers force), but this is again not available at the moment and doesn't bring anything to this discussion.

**Comment by limpkin** [comment]
Actually we have redesigned our database for our next gen device and
therefore would love to hear about your current needs to see if we could
accommodate them.
Could you expand about why you'd need more than 8k chars for URL?

**Comment by cwaazywabbit** [comment]
Oh that's great news. 8k is more than enough. I might not actually even need that length and 2k would be just fine.

In this case the question is: would we really have a URL field (or field of some sort) that we can also auto-fill using a click with the Mooltipass?
The second question is: will we get a firmware update, or do we have to get the new device then?

**Comment by limpkin** [comment]
But why would you need 2k? Do you have a concrete example of a long URL you
need to be typed?
This will be an entirely new firmware and would therefore need the newer
device.

**Comment by cwaazywabbit** [comment]
2k just being the max that IE supports, then I have lots of ground covered for a "URL". At the moment I cannot give you a solid example.. my current URLs don't go beyond couple of hundreds.

**Comment by limpkin** [comment]
Could you give us examples of these long URLs? In 5 years, no one hit our
url storage limitations

**Comment by cwaazywabbit** [comment]
Hi Mathieu,

first of all, I would like to make sure that we are on the same page, since
the term "URL" is now being mentioned and we might have deviated a little.
I am not using Mooltipass with browser extensions, whatsoever, so far.
When you are talking about "URL" storage limitations, does it have
something to do with using the browser extensions?

In my case, I am using the device for personal and business purposes. One
of the business purposes require receiving URLs & credentials to services
that might be internal or external (but not publicly available). Later on
when a project starts, I need to access those services under certain
conditions. Hence, I was looking forward to using the device to store those
URLs and credentials and benefit from the auto-fill feature instead of
fetching files off the device.. you get the picture. In that case, how may
I save the URLs manually without extensions?

Cheers

**Comment by limpkin** [comment]
Unfortunately manual URL recall isn't implemented in the current mini, I
could enable that for the next gen.
In the next gen, url length is Max 126 Unicode chars.

**Comment by limpkin** [comment]
Anyway I'm going to close this issue as this is a hardware limitation...
