### ISSUE TITLE
Why would {"msg":"reset_card"} fail?

### ISSUE THREAD

**Issue by cwaazywabbit** [mooltipass/moolticute#458]
When sending a _reset_card_ msg, I receive the following:

```
{"data":{"failed":true},"msg":"reset_card"}
```

I am using Mooltipass mini and Moolticute 0.42.1

Any idea?

**Comment by limpkin** [comment]
It's only reserved for an edge case: when an unknown card is inserted.

**Comment by cwaazywabbit** [comment]
Ok, that explains it. Thanks.
