### ISSUE TITLE
Moolticute crashes on Windows on manual exit

### ISSUE THREAD

**Issue by cwaazywabbit** [mooltipass/moolticute#461]
On Windows, an attempt to exit Moolticute from System Tray by doing a Right click > Quit would case Moolticute to crash, as shown next.

![grafik](https://user-images.githubusercontent.com/6714156/60760922-46ef1180-a03e-11e9-9184-9bc6a981c072.png)

**Comment by limpkin** [comment]
that's going to be a hard one to reproduce....
I've been doing that at least twice a day for the last 2 months without any issues :/.
Could you give us more details about your configuration?

**Comment by cwaazywabbit** [comment]
MS Windows 10 Enterprise 2016 LTSB v10.0.14393 x64 bit
4 cores Intel processor. More than enough memory.
Not in a VM.

![grafik](https://user-images.githubusercontent.com/6714156/60796887-93396f00-a16e-11e9-9e54-7c8fe3b53da3.png)

According to the event logs, the culprit is Qt5Widgets.dll, Version: 5.9.6.0.

**Comment by limpkin** [comment]
hello!

does this issue still happen?

**Comment by cwaazywabbit** [comment]
Yes. Moolticute has not received a new version, has it?

**Comment by limpkin** [comment]
@cwaazywabbit could you try one of the latest betas in betas.themooltipass.com?

**Comment by cwaazywabbit** [comment]
I have tested it on v0.42.43-testing and the issue has been fixed.
Checking for updates seemed to be working again too (it doesn't in the latest non-beta version 0.41.5 which is published here https://www.themooltipass.com/setup/)
