### ISSUE TITLE
Moolticute 0.42.1 fails to recognise NewDay account login form

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#467]
Running Moolticute 0.42.1 on Linux 64-bit with Firefox, which works great... except it fails to recognise the login form for the NewDay Amazon-branded credit card portal.

https://portal.newdaycards.com/amazon/login

If I browse to the site, Moolticute doesn't trigger a login prompt on the Mooltipass. If I right-click and choose Fill User + Pass, Moolticute does trigger a login prompt on the Mooltipass but when I confirm I want to send the credentials it doesn't fill them in. The only way I can log in is by using the Mooltipass in USB keyboard mode, manually browsing for the credentials and sending them that way.

Not sure if it's something that could be worked around in a future Moolticute or if NewDay's just doing something entirely incompatible with the Mooltipass - and it's not urgent either way, as logging in using the Mooltipass as a keyboard works fine. Just wanted to flag it up!

**Comment by limpkin** [comment]
Hello!

Could you use the "report incompatibilities with this website" item in the extension menu to report this? Moolticute is the backend and doesn't do form detection.

Thanks for flagging it anyway! :)
Mathieu

**Comment by ghalfacree** [comment]
My bad - I *knew* there was a report button somewhere, but I was looking for it in the right-click menu and not the main extension menu. Properly reported now!

**Comment by limpkin** [comment]
thanks :)
