### ISSUE TITLE
Grammatical mistake "for a while" vs "in a while"

### ISSUE THREAD

**Issue by ali-raheem** [mooltipass/moolticute#471]
There is a little notification at the bottom of the Moolticute window with the warning

```
You haven't made a backup of your database for a while. 
Do you want to backup your credentials now?
```

Grammatically this should read `You haven't made a backup of your database in a while.`

It's easier to see the issue with a concrete time replacing while.

`You haven't slept for 5 minutes` vs `You haven't slept in 5 minutes`

Happy to put a pull requrest in for `src/DbExportsRegistryController.cpp` line 111, but would I need to also do it for every translation?

**Comment by limpkin** [comment]
Hello! thanks for bringing this to our attention.
@deXol how are the translations mapped?

**Comment by deXol** [comment]
@limpkin: English translation are written in code between `tr("")`.
From string between tr it is possible to generate **lang/*.ts** mapping xml files with `lupdate -verbose gui.pro`, which contains the corresponding translations for the source string from code.

Btw there are several new texts, so it would worth an update.
