### ISSUE TITLE
[Windows] Moolticute not detecting password input, nor login automatically at a known site.

### ISSUE THREAD

**Issue by Timandrias** [mooltipass/moolticute#481]
At @limpkin request, I'm testing the new mooltipass model, and I haven't been able to make it work at my home computer. 

The app detects the device, but it doesn't do anything when I reach a known login page or I input a new password. No prompts by the app or the mooltipass. If I force the device to enter a password as a keyboard, works.

Windows 10 Pro Build 18362.19h1_release.190317-1202
I have tried both Firefox and Chrome.
It works flawlessly in the computer at work, so there must be some weird interaction with my home OS, or various software.

I attach the logs of the daemon, during which I tried to enter a password, and login in a known site.
[moolticute_logs.txt](https://github.com/mooltipass/moolticute/files/3740436/moolticute_logs.txt)

**Comment by raoulh** [comment]
The issue is that moolticute is not detecting your device at all. How is the device connected?

**Comment by Timandrias** [comment]
It is certainly detecting something, as the usual device menu appears in the app (instead of the "connect your Mooltipass device" prompt. I didn't try to access the credentials MM, but the menu was there.

I connect it by USB, and it's not working through USB, but at some point I tried to connect it via bluetooth to see if there was a difference, so it might appear on the log.

**Comment by raoulh** [comment]
From the log file you provided, moolticute did not find any device...

**Comment by deXol** [comment]
It looks like for me the bt connection is continuously dropping. Also the browser is sending `show_status_notification_warning` message multiple times, so there should be a system notification displayed with the problem.
Can you please try disable bluetooth on the device, restart daemon and connect the device with usb. Is it working in this case?

**Comment by Timandrias** [comment]
I attach the logs for the following actions:
1. Connect the device.
2. Try to access a few websites through chrome and firefox
3. Try to enter the credential MM

That last action doesn't go through. It stops at "Waiting for device confirmation"
[moolticute_logs_2.txt](https://github.com/mooltipass/moolticute/files/3747631/moolticute_logs_2.txt)
.

**Comment by raoulh** [comment]
which version of moolticute do you run?

**Comment by limpkin** [comment]
latest beta :D

**Comment by deXol** [comment]
@raoulh can you please add the DEV_DEBUG define to beta (testing) builds? 
Because the messages between the device and some additional details are only printed with that one, which would be really useful in logs like this one.

**Comment by raoulh** [comment]
@limpkin that is not written anywhere in this bug report.

@deXol sure, i'll do it

**Comment by limpkin** [comment]
@raoulh agreed, i'll add an issue template for this repo like on mine :)

**Comment by limpkin** [comment]
@raoulh new issue template added. My plan here is to wait for @deXol upcoming PR with favorite categories handling, merge it, building a new beta with the DEV_DEBUG define to allow @Timandrias to give us more debug info.

**Comment by raoulh** [comment]
@deXol no more DEV_DEBUG define, but a global option in gui. Works in release mode too. See https://github.com/mooltipass/moolticute/commit/d6250068f7c72bcf36f6944819b30d4050f2d4c2

**Comment by limpkin** [comment]
issue traced back to a bug on aux mcu.
