### ISSUE TITLE
Moolticute doesn't seem to reset its state when the device disconnects during the initial message sends

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#492]
When a new device is connected, a set of message is sent to the device, such as GET_PLAT_INFO...
If the device disconnects at this moment, it seems moolticute wants to continue with the other messages instead of sending the GET_PLAT_INFO message again.

the log:

INFO: :0 - ------------------------------------
INFO: :0 - Trying to set language:  ":/lang/mc_en.qm"
INFO: :0 - Running  "C:/Users/mstephan/AppData/Local/Programs/Moolticute/moolticuted"   ("-l")
INFO: :0 - Daemon started
INFO: :0 - ------------------------------------
INFO: :0 - Moolticute Daemon version:  v0.42.6-testing
INFO: :0 - (c) The Mooltipass Team
INFO: :0 - https://github.com/mooltipass/moolticute
INFO: :0 - ------------------------------------
DEBUG: :0 - Moolticute daemon websocket server listening on port  30035
INFO: :0 - Starting MPManager
DEBUG: :0 - Registering device events
DEBUG: :0 - List usb devices...
DEBUG: :0 - BT HID connected
DEBUG: :0 - Found mooltipass:  "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&9e00851&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - Mooltipass Mini BLE is connected
DEBUG: :0 - Mooltipass connected
DEBUG: :0 - Resetting flip bit for BLE
INFO: :0 - "Get PlatInfo"
DEBUG: :0 - Platform send command:  "GET_PLAT_INFO (0x0003)"
DEBUG: :0 - Full packet# 0 :  "[0x04, 0x00, 0x03, 0x00, 0x00, 0x00]"
WARNING: :0 - Failed to write data to device!
WARNING: :0 - "The parameter is incorrect."
DEBUG: :0 - Send card db metadata
DEBUG: :0 - There is no card data to be send.
DEBUG: :0 - New connection
DEBUG: :0 - Send card db metadata
DEBUG: :0 - There is no card data to be send.
DEBUG: :0 - New connection
DEBUG: :0 - JSON API recv: {"msg":"get_application_id"}
DEBUG: :0 - QJsonValue(null)  message have not implemented yet for BLE
DEBUG: :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: :0 - JSON API recv: {
    "msg": "list_files_cache"
}

DEBUG: :0 - QJsonValue(string, "list_files_cache")  message have not implemented yet for BLE
DEBUG: :0 - JSON API recv: {
    "msg": "request_keyboard_layout"
}

DEBUG: :0 - JSON API recv: {
    "msg": "get_user_settings"
}

DEBUG: :0 - JSON API recv: {
    "msg": "request_keyboard_layout"
}

DEBUG: :0 - JSON API recv: {
    "msg": "get_user_settings"
}

DEBUG: :0 - Send card db metadata
DEBUG: :0 - There is no card data to be send.
DEBUG: :0 - New connection
DEBUG: :0 - JSON API recv: {"msg":"get_application_id"}
DEBUG: :0 - QJsonValue(null)  message have not implemented yet for BLE
INFO: :0 - Checking software updates from  "http://mooltipass-tests.com/mc_betas/updater.json"
INFO: :0 - Checking software updates from  "https://mooltipass-tests.com/mc_betas/updater.json"
WARNING: :0 - Failed to read data from device!
WARNING: :0 - "The device is not connected."
DEBUG: :0 - Device removed:  "{00001800-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0001#{00001800-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001800-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0001#{00001800-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0001#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001800-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0001#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{00001801-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001801-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0008#{00001801-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001801-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0008#{00001801-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001801-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0008#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001801-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0008#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{0000180f-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{0000180f-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&000c#{0000180f-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{0000180f-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&000c#{0000180f-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{0000180f-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&000c#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{0000180f-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&000c#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&1bd60e8c&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: :0 - "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&1bd60e8c&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  is not connected.
DEBUG: :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&1bd60e8c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\KBD"
DEBUG: :0 - "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&1bd60e8c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd"  is not connected.
DEBUG: :0 - Device removed:  "{00001812-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0010#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0010#{00001812-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0010#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0010#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&9e00851&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - Disconnecting:  "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&9e00851&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - Mooltipass disconnected
DEBUG: :0 - Device removed:  "{00001812-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0022#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0022#{00001812-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0022#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0022#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{0000180a-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{0000180a-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0030#{0000180a-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - "\\\\?\\bthledevice#{0000180a-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0030#{0000180a-0000-1000-8000-00805f9b34fb}"  is not connected.
DEBUG: :0 - Device removed:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{0000180a-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&13&0030#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - "\\\\?\\bthledevice#{0000180a-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&13&0030#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  is not connected.
DEBUG: :0 - Device removed:  "{80795c47-03f0-446d-b1f2-e424b30db4da}"  -  "\\\\?\\BTHLE#Dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{80795c47-03f0-446d-b1f2-e424b30db4da}"
DEBUG: :0 - "\\\\?\\bthle#dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{80795c47-03f0-446d-b1f2-e424b30db4da}"  is not connected.
DEBUG: :0 - Device removed:  "{781aee18-7733-4ce4-add0-91f41c67b592}"  -  "\\\\?\\BTHLE#Dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{781aee18-7733-4ce4-add0-91f41c67b592}"
DEBUG: :0 - "\\\\?\\bthle#dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{781aee18-7733-4ce4-add0-91f41c67b592}"  is not connected.
DEBUG: :0 - Device added:  "{781aee18-7733-4ce4-add0-91f41c67b592}"  -  "\\\\?\\BTHLE#Dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{781aee18-7733-4ce4-add0-91f41c67b592}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthle#dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{781aee18-7733-4ce4-add0-91f41c67b592}"
DEBUG: :0 - Device added:  "{80795c47-03f0-446d-b1f2-e424b30db4da}"  -  "\\\\?\\BTHLE#Dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{80795c47-03f0-446d-b1f2-e424b30db4da}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthle#dev_ab89674511ff#7&20fdde69&0&ab89674511ff#{80795c47-03f0-446d-b1f2-e424b30db4da}"
DEBUG: :0 - Device added:  "{00001800-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0001#{00001800-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001800-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0001#{00001800-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0001#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001800-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0001#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{00001801-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001801-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0008#{00001801-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001801-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0008#{00001801-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001801-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0008#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001801-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0008#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{00001812-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0010#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0010#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0010#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0010#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{00001812-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0022#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0022#{00001812-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0022#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0022#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{0000180f-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{0000180f-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&000c#{0000180f-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{0000180f-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&000c#{0000180f-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{0000180f-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&000c#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{0000180f-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&000c#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{0000180a-0000-1000-8000-00805f9b34fb}"  -  "\\\\?\\BTHLEDevice#{0000180a-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0030#{0000180a-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{0000180a-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0030#{0000180a-0000-1000-8000-00805f9b34fb}"
DEBUG: :0 - Device added:  "{6e3bb679-4372-40c8-9eaa-4509df260cd8}"  -  "\\\\?\\BTHLEDevice#{0000180a-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#8&2b8b416f&14&0030#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\bthledevice#{0000180a-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#8&2b8b416f&14&0030#{6e3bb679-4372-40c8-9eaa-4509df260cd8}"
DEBUG: :0 - Device added:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&34dfe8f1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - BT HID connected
DEBUG: :0 - Mooltipass Mini BLE is connected
DEBUG: :0 - Mooltipass connected
DEBUG: :0 - Device added:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&2e346c24&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\KBD"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&2e346c24&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd"
DEBUG: :0 - Device added:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&2e346c24&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: :0 - Not a mooltipass device:  "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&2e346c24&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: :0 - JSON API recv: {
    "msg": "request_keyboard_layout"
}

INFO: :0 - "Read languages"
DEBUG: :0 - Platform send command:  "GET_LANG_NUM (0x0019)"
DEBUG: :0 - Full packet# 0 :  "[0x04, 0x00, 0x19, 0x00, 0x00, 0x00]"
DEBUG: :0 - JSON API recv: {
    "msg": "get_user_settings"
}

WARNING: :0 - Failed to write data to device!
WARNING: :0 - "The parameter is incorrect."
DEBUG: :0 - Resetting flip bit for BLE
WARNING: :0 - Failed to read data from device!
WARNING: :0 - "The device is not connected."
DEBUG: :0 - Device removed:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&2e346c24&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: :0 - "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&2e346c24&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  is not connected.
DEBUG: :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&2e346c24&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\KBD"
DEBUG: :0 - "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&2e346c24&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd"  is not connected.
DEBUG: :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011209_PID&4321_REV&0001_ab89674511ff#9&34dfe8f1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - Disconnecting:  "\\\\?\\hid#{00001812-0000-1000-8000-00805f9b34fb}_dev_vid&011209_pid&4321_rev&0001_ab89674511ff#9&34dfe8f1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: :0 - Mooltipass disconnected

**Comment by limpkin** [comment]
@deXol i'm pretty sure this is fixed, right?

**Comment by deXol** [comment]
@limpkin Yes, I think it is fixed, cannot reproduce.
