### ISSUE TITLE
Lack of "Input pin" prompt when forgot to input pin.

### ISSUE THREAD

**Issue by Timandrias** [mooltipass/moolticute#496]
### Expected behavior

When connected to the computer, but forgot to input the pin, I expect it to prompt an message if I access a login webpage. (The software properly prompts a message if the device is not connected).
IDEALLY, I'd like the login prompt to appear on the device, and a message from moolticute.

### Actual behavior

Nothing happens. No message in the device nor Moolticute.

### Step by step guide to reproduce the problem

Turn Off mooltipass.
Turn On mooltipass.
Connect to computer. Do not input pin.
Go to a webpage with credentials stored.
No message whatsoever.

### Moolticute Version - If Involved

v0.42.5-testing

### Operating System
- Windows 10
  
Other operating systems are not supported.

**Comment by limpkin** [comment]
@deXol it seems notifications might be broken for win 1909....

**Comment by deXol** [comment]
@Timandrias Are you not receiving system notification at all or only this one?

**Comment by Timandrias** [comment]
@deXol I've been tracking it for the last days, and I'd say that the notifications work haphazardly. I sometimes (but not always) I see the "Please connect your device", but I've never seen the one for "Please login".

**Comment by limpkin** [comment]
@Timandrias to double check in case :)
