### ISSUE TITLE
When created from Moolticute, credencial category is not set

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/moolticute#501]
### Expected behavior

When a new credential is added from Moolticute, it should be saved in the selected category. Even if the selected category in Mooltipass is "All categories"

### Actual behavior

The credential is not saved in the selected category

### Step by step guide to reproduce the problem

1. Create a new credential in Moolticute
2. Set the category and confirm the change
3. Save the changes
4. The new credential is not in the selected category

Note : This bug affect only the new credential. If a credential's category is modified from Moolticute, it works

### Moolticute Version - If Involved

v0.42.8-testing

### Mooltipass Version

Aux MCU : 0.8
Main MCU : 0.8

### Operating System
- Windows 10

**Comment by deXol** [comment]
@limpkin 
When "All categories" category is selected on the device and I try to add a credential from MMM and a custom category, then after saving the category is not persisted. However it looks like in STORE_CATEGORY the category id is sent:
![notPersistedCategories](https://user-images.githubusercontent.com/11043249/69917877-3c109f80-146b-11ea-90c6-47fada905934.gif)
