### ISSUE TITLE
Check for Updates success/failure feedback

### ISSUE THREAD

**Issue by the-other-foot** [mooltipass/moolticute#507]
### Missing feature

Clicking on Check For Updates when there are no updates doesn't give any feedback in the UI. Looking at the logs, it reports "No any appropriate update was found". Feedback in the UI in the form of "Updates found", "No new updates found", or "Error checking for updates" would be ideal.

This is in 0.42.6-testing and 0.42.8-testing on macOS if that makes a difference. I'm not sure if the app is set up to check for newer versions of the testing branch, but 0.42.6-testing didn't detect 0.42.8-testing as a newer version.

### Justification
Makes it easier to know when you're up to day or not.

### Workarounds
Opening the logs to verify.

**Comment by limpkin** [comment]
This may be macos specific... We have messages on windows

**Comment by limpkin** [comment]
confirmed to be macos specific....

**Comment by deXol** [comment]
@raoulh I checked https://mooltipass-tests.com/mc_betas/updater_osx.json and for the assets `name` the extenstion is missing, hence it is not processed:
https://github.com/mooltipass/moolticute/blob/8a08b672c2c9c16e7d3e9f2ab379e9738ce89f42/src/QSimpleUpdater/src/Updater.cpp#L399
For the linux and windows link it contains: https://mooltipass-tests.com/mc_betas/updater.json
Should I handle it for Mac on MC side or can you add the dmg extension to the json?
