### ISSUE TITLE
App window won't re-open after being closed on macos

### ISSUE THREAD

**Issue by the-other-foot** [mooltipass/moolticute#508]
Closing just the moolticute window prevents the window from re-opening on macos until background moolticute processes are killed.

Strangely, quitting moolticute from the system tray icon [while the moolticute window is active] works as expected and correctly kills the app, allowing it to be re-opened.

### Expected behavior

The app either exits completely
or "hides" and leaves a system tray icon/daemon

### Actual behavior

The window disappears and leaves a system tray icon. Clicking on the system tray icon shows all menu options as grayed out. Launching the app again does nothing. `ps` shows a `moolticuted -l` process and another `moolticute -psn_0_19645115` process. killing both of these processes kills the tray icon and allows me to re-launch moolticute

### Step by step guide to reproduce the problem

- Open Moolticute
- Close Moolticute by clicking the x on the window
- Attempt to re-open Moolticute via the systray menu [now grayed out] or launching the app

### Moolticute Version - If Involved
0.42.6-testing
0.42.8-testing

### Operating System
macos 10.14.6

**Comment by deXol** [comment]
@limpkin this issue is the same as #479

**Comment by limpkin** [comment]
if it is, then i'll close it
