### ISSUE TITLE
storing credentials from Moolticute 0.42.9

### ISSUE THREAD

**Issue by mpble** [mooltipass/moolticute#514]
###Creating credentials within Moolticute.
- Connect Mooltipass BLE with USB
- Enter "Credentials" tab in Moolticute.
- Select the button "Enter Credentials Management Mode"
- Confirm on device Mooltipass BLE
- Service or Site name: testcreds
- Login: xxx.yyy@domain.com
- Password: qwertzÄ!
- Press button "Save all changes"

Message "Couldn't save credentials, please contact the support team with moolticute's log"

**Comment by limpkin** [comment]
could you give us:
- OS information
- moolticute version
- moolticute's log with developer's option enabled
- information about your device

**Comment by deXol** [comment]
@limpkin 
https://github.com/mooltipass/moolticute/issues/501#issuecomment-560136480
The only difference from the other issue, here a custom category is selected on the device.
When I try to add a credential from MMM and set a different category (from selected on device), then after saving STORE_CREDENTIAL fails:
![bleSaveCategoryFails](https://user-images.githubusercontent.com/11043249/69917940-23ed5000-146c-11ea-88a6-ccf6cf9bd18c.gif)
Category `ccc` was selected on the device.

**Comment by limpkin** [comment]
I've implemented a possible fix in https://github.com/mooltipass/minible/commit/b440eb03832845511bb427d6a1197c00ffdbdd89 ... to be confirmed
