### ISSUE TITLE
BLE: On entering MMM multiple "Favorite is pointing to incorrect node!" printed to debug log

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#523]
### Expected behavior
"Favorite is pointing to incorrect node!" critical message should not occur
### Actual behavior
Debug log:
```
CRITICAL: (2019-11-26T20:23:31.081) MPDevice.cpp:3025 - Favorite is pointing to incorrect node!
CRITICAL: (2019-11-26T20:23:31.081) MPDevice.cpp:3025 - Favorite is pointing to incorrect node!
CRITICAL: (2019-11-26T20:23:31.081) MPDevice.cpp:3025 - Favorite is pointing to incorrect node!
...
```
### Step by step guide to reproduce the problem
1. Connect mini ble with USB
2. Go to Credenitals Tab
3. Click "Enter Credentials Management Mode"
4. Accept on device
5. Check the debug log

### Moolticute Version
v0.42.13-testing

### Operating System
- Windows 10

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
what's your db made of? this is going to require some digging!

**Comment by deXol** [comment]
> 
> 
> what's your db made of? this is going to require some digging!

for me it occurs with an empty db too

**Comment by deXol** [comment]
GET_FAVORITES with the latest fw:
![kép](https://user-images.githubusercontent.com/11043249/69992162-6042ae00-1549-11ea-8f9a-f7cff7d7fd58.png)

GET_FAVORITES on developer board:
![kép](https://user-images.githubusercontent.com/11043249/69992076-325d6980-1549-11ea-8c2b-a4b346cfbf82.png)

**Comment by limpkin** [comment]
fixed by https://github.com/mooltipass/minible/commit/75af261e67276023c4a442730f8bbd18ec2f1f0d
