### ISSUE TITLE
MP BLE not handling Direct IP sites

### ISSUE THREAD

**Issue by techiem2** [mooltipass/moolticute#527]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
Using MP BLE under Windows 10 with Moolticute 0.42.1.

### Expected behavior
Site to be added to device properly.

### Actual behavior
Last period is stripped out of the site address, so the site is no longer recognized when re-visited.
I.E. connecting to 192.168.1.10 would be saved on MP BLE as 192.168.110

### Step by step guide to reproduce the problem
Connect to a site VIA IP address, login, save the site - you'll see it saved without the final period.
Log out and reload site - connection is not detected due to it being saved incorrectly.

Everything works as expected on the same PC using original MP device.

### Moolticute Version
0.42.1
### Operating System
Windows 10
### Mooltipass Device
- The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by deXol** [comment]
@limpkin Fixed with https://github.com/mooltipass/moolticute/pull/502/files
