### ISSUE TITLE
Mooltipass Mini: knock setting should be reloaded when user logged in

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#528]
### Expected behavior
Save to device button to disappear if the user didn't save knock settings and then logs in

### Step by step guide to reproduce the problem
- insert mini without card
- change knock setting, do not save
- insert card
- enter pin
- click save

### Moolticute Version
0.42.8

### Mooltipass Device
- The Mooltipass Mini

**Comment by deXol** [comment]
@limpkin: Created a simple fix for it here: https://github.com/mooltipass/moolticute/compare/master...deXol:develop528KnockSettingReloadOnLogin
It is reloading every settings, when user logs in.
Or should we only reload knock detection setting in this case? (thats could be more complicated)

**Comment by limpkin** [comment]
All of them is fine :)
