### ISSUE TITLE
[BLE] Unhandled status byte warning during enter MMM

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#530]
### Expected behavior
Do not print warning

### Actual behavior
WARNING: (2019-11-28T21:39:39.457) :0 - Unable to find value from enum for status ""

### Root cause
During MMM value 21 sent as status code, which is not handled.

### Step by step guide to reproduce the problem
Enter MMM

### Operating System
- Windows 10

**Comment by deXol** [comment]
@limpkin Still do not have any information about this new status code

**Comment by limpkin** [comment]
@deXol does this still happen? from a firmware point of view that should not happen :/

**Comment by deXol** [comment]
@limpkin Yes with the latest fw, when I enter MMM the following status message is received:
```
DEBUG: (2020-01-04T20:18:10.515) MPDevice.cpp:388 - "Received answer: MOOLTIPASS_STATUS (0x0011)"  Full packet: "0800110004001500c9ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-01-04T20:18:10.515) MPDevice.cpp:60 - received MPCmd::MOOLTIPASS_STATUS:  21
```

**Comment by deXol** [comment]
After checking https://mooltipass.github.io/minible/protocol, looks like **0x01 Smartcard presence** | **0x04 Smartcard unlocked** | **0x10 Device in management mode** is sent. (Which is 0x15 == 21)
But I guess only **0x10 Device in management mode** should be.

**Comment by limpkin** [comment]
@deXol actually it is technically correct... so not really a bug... oculd you consider 0x15 as 0x10 in this case? :)

**Comment by deXol** [comment]
@limpkin Here are the currently used status values: https://github.com/mooltipass/moolticute/blob/master/src/Common.h#L153
I think we should add a new one for MMM with 21 value. (There is not for MMM currently)
