### ISSUE TITLE
Screen Error (hardware problem)

### ISSUE THREAD

**Issue by kikieri** [mooltipass/moolticute#539]
Using this Device since 1 day on mac osx.
Since today it looks like this:
(how can I reset my device?)

![8EA87624-681B-4110-8242-DE02EF947653](https://user-images.githubusercontent.com/53120718/70265537-ee61a300-179a-11ea-951b-a355fcd66ecc.jpeg)
![E402164E-FEC2-4834-A369-67DA176F446F](https://user-images.githubusercontent.com/53120718/70265538-ee61a300-179a-11ea-85bc-fe7fb44f62cb.jpeg)

**Comment by limpkin** [comment]
send us an email to support[at]themooltipass dot com with your units serial number and we'll have a firmware update sent to you :)

**Comment by kikieri** [comment]
eMail send. Keep you updated!
Thanks for the fast reply
