### ISSUE TITLE
BLE: Adding a credential in MMM for an existing service: multiple bugs

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#541]
- default category not selected
- can't press discard changes
- can't select favorite

**Comment by deXol** [comment]
@limpkin:  Can you double check this? I was not able to reproduce the issue.
There was a few MMM related fixes which possibly handled it. (most likely #534)

**Comment by limpkin** [comment]
@deXol this bug is still valid on the latest beta release including your latest changes (v0.42.26-testing) on windows i'm affraid
