### ISSUE TITLE
Can't store uppercase characters in Service or Site Name

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/moolticute#548]
### Expected behavior
When I save for example: MPtestService it should store this name as is.
### Actual behavior
MPtestService is stored as mptestservice
### Step by step guide to reproduce the problem
In credential management mode save a service name with uppercase characters.
### Moolticute Version
v0.42.22-testing

**Comment by limpkin** [comment]
Hello,

To be honest I don't think I agree with this one... if we don't lowercase everything then we may start discussions about uniformization of the UI and credentials sorting...
