### ISSUE TITLE
[macOS] Minimum window size too big

### ISSUE THREAD

**Issue by arieljt** [mooltipass/moolticute#549]
### Expected behavior
After installing Moolticute on macOS user should be able to see the whole GUI window of Moolticute, either by the window having the right size from the get-go or by resizing it.

### Actual behavior
Under 13" macbook with default, native resolution (2560 x 1600) the Dock covers the bottom part of the window. User can't resize window height to make it smaller due to its minimum size settings.

### Step by step guide to reproduce the problem
Install Moolticute on macOS while using a small screen (13" or smaller) with resolution of 2560 x 1600.

### Moolticute Version
v0.42.20-testing 

### Operating System
MacOS Catalina, 10.15.1

### Mooltipass Device
Issue is no dependent of the type of Mooltipass device.

**Comment by limpkin** [comment]
@arieljt could you send us a screen capture of what it looks like?

**Comment by arieljt** [comment]
Sure, please see the first screenshot when moolticute is first installed. Second after closing and re-opening (still slightly overlapping with the dock).
![Screenshot 2019-12-08 at 20 03 39](https://user-images.githubusercontent.com/50654434/71770851-c94b8600-2f3a-11ea-81c6-04e2ce373a3e.png)
<img width="1065" alt="Screenshot 2020-01-04 at 21 40 55" src="https://user-images.githubusercontent.com/50654434/71770867-f39d4380-2f3a-11ea-8fb7-ce7620934cba.png">

**Comment by limpkin** [comment]
@deXol Could we set a smaller height for MacOS only? IIRC we had set this height so there wouldn't be any scrolling on any tab :)
