### ISSUE TITLE
[BLE] Bluetooth Keyboard Layout and USB Keyboard Layout settings reset

### ISSUE THREAD

**Issue by deXol** [mooltipass/moolticute#552]
###  Expected behavior
Keep the Bluetooth Keyboard Layout and USB Keyboard Layout settings

### Actual behavior
Resetting Bluetooth Keyboard Layout and USB Keyboard Layout settings to default.

### Step by step guide to reproduce the problem (order is important)

1. Set Bluetooth Keyboard Layout and USB Keyboard Layout
2. Disconnect USB
3. Remove smart card
4. Connect USB
5. Insert Smart Card again
6. Bluetooth Keyboard Layout and USB Keyboard Layout set to default `Belgium French` value

### Moolticute Version
v0.42.22-testing

### Operating System
- Windows 10

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
are you fetching the selected layout when the user logs in again?

**Comment by deXol** [comment]
> are you fetching the selected layout when the user logs in again?

looks like selected layout only fetched on usb connection
So I think it should be also fetched when user logged in.

Already started to implement "Only display Current User Language, Bluetooth Keyboard Layoud and USB Keyboard Layout, when user is logged in" task here: https://github.com/mooltipass/moolticute/compare/master...deXol:developBLEDeviceSettingsFix
I will also implement fetching with it.
