### ISSUE TITLE
Moolticute Crash in MMM

### ISSUE THREAD

**Issue by Arffeh** [mooltipass/moolticute#553]
### Expected behavior
Able to add specific credential with category.

### Actual behavior
Crashes Moolticute when adding credential and changing the category, or doesn't let me back out.

#### Crash immediately:

Have a set of pre-existing credentials:

![image](https://user-images.githubusercontent.com/2135196/70528064-6ec04380-1ba1-11ea-8d42-77f872a0d43f.png)

Attempt to add 10.10.10.1

Interesting visual glitch happens:

![image](https://user-images.githubusercontent.com/2135196/70528122-91525c80-1ba1-11ea-9dda-11f74a12158a.png)

It doesn't open the added credential immediately as it should, instead it creates the 10.10.10.1 credential, and adds a blank line in the 10.10.10.10 credential below it.

Attempt to change credential category:

![image](https://user-images.githubusercontent.com/2135196/70528257-e3937d80-1ba1-11ea-923e-897e75359f32.png)

On clicking Confirm Changes, moolticute immediately crashes.

#### Unable to back out of setting up a credential

Similar to above, but when adding a credential to 10.10.10.10 or 10.10.10.11 , I'm greeted with a blank category box, and on holding Discard Changes, after the bar reaches the end, it does nothing. I can repeatedly attempt to Discard Changes, nothing will ever happen:

![image](https://user-images.githubusercontent.com/2135196/70529039-b647cf00-1ba3-11ea-8137-7b5ee7cc1583.png)

Only way to stop is to completely exit MMM via Discard All Changes at the bottom of the dialog.

-----------
Something interesting is going on surrounding my 10.10.10.10 and 10.10.10.11 credentials.

Of note, anything that would sort string-wise under 10.10.10.10 will crash, including:
1
10.10.10
10.10.10.1

Any attempt to add to 10.10.10.10 or 10.10.10.11 will not allow me to back out of it, but will allow me to create the credential with category (even if category field is blank), without crashing.

Anything beyond this specific set of credentials, works 100% fine.

### Moolticute Version
Tested on v0.42.20-testing and v0.42.23-testing

### Operating System
Happens on both Windows 7 and 10.

Doesn't happen on Arch.

### Mooltipass Extension
1.8.0

### Mooltipass Device
The Mooltipass Mini BLE

**Comment by limpkin** [comment]
@Arffeh : this is a stellar bug report... thanks a lot for taking so much time to write such a detailed explanation. This makes @deXol 's work much easier.
