### ISSUE TITLE
Can't install Moolticute on MacOS

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#557]
### Expected behavior

To be able to install moolticute

### Actual behavior

that funky message:

![image](https://user-images.githubusercontent.com/6170291/71021996-bbef6880-20ff-11ea-8605-1ae5f923e522.png)

### Step by step guide to reproduce the problem

try to install moolticute

### Moolticute Version

v0,42,24

### Operating System

MacOS Catalina 10.15.2

**Comment by limpkin** [comment]
in english....

![image](https://user-images.githubusercontent.com/6170291/71022672-50a69600-2101-11ea-9f90-c5fc4d1429cb.png)

**Comment by arieljt** [comment]
It's common issue in Catalina. The Gatekeeper will alert when an app isn't "Notarized".

Please see https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Workaround:
Open "System Preferences"
Go to "Security and Privacy"
In the "General" tab, click on "Open Anyway"

The error won't repeat itself on the next app launch.

**Comment by limpkin** [comment]
yep! I'm leaving this open as a reminder to people.
In the future, we'll only notarize proper releases.

**Comment by limpkin** [comment]
duplicate of #476
