### ISSUE TITLE
Credentials Management Mode: populate category fields if they're empty

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#560]
When going into MMM and when the category strings aren't set, this leads to a weird list:

![image](https://user-images.githubusercontent.com/6170291/71156197-c749ad80-223f-11ea-91ad-d7a2613e0039.png)

maybe check for 0xFFFFF.... and .empty() and populate with something by default like <<category1>>, <<category2>> ?

**Comment by deXol** [comment]
@limpkin how about some default one?
![kép](https://user-images.githubusercontent.com/11043249/71310218-c5374880-2411-11ea-819a-402fb8044420.png)
E.g.: here category 2,3,4 is empty.

**Comment by limpkin** [comment]
Why not!
