### ISSUE TITLE
[macOS] Moolticute window is transparent when dragged to external monitor

### ISSUE THREAD

**Issue by arieljt** [mooltipass/moolticute#568]
### Expected behavior
Window stay visible when dragged to an external display.

### Actual behavior
Window becomes transparent until the focus changes to another window (from another app).

### Step by step guide to reproduce the problem
Open Moolticute on macOS with at least one external monitor.
Drag Moolticute to the external monitor.

### Moolticute Version
v0.42.25-testing

### Operating System
- MacOS Catalina

### Mooltipass Device
N/A

![Screenshot 2019-12-27 at 12 40 15](https://user-images.githubusercontent.com/50654434/71516000-bb489600-28a6-11ea-8f6a-7058de55e5b6.png)

**Comment by limpkin** [comment]
so we haven't been able to reproduce this one lately.... do you still have this?

**Comment by arieljt** [comment]
No, closing.
