### ISSUE TITLE
Feature Request: Make Database Backup Monitoring Multi-Device-Safe

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#569]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
While testing the BLE, I came across an edge-case issue in Moolticute: I use the Database Backup Monitoring option to save an encrypted copy of my credentials database, which works great. If I connect a spare Mooltipass Mini from storage, it'll correctly tell me the backup is newer and let me restore it; if I add new credentials, it'll correctly prompt me to update the backup.

There's no current way to restore a Mooltipass/Mooltipass Mini backup to a Mooltipass Mini BLE, however, which is where the edge-case comes up: my BLE has only a subset of the credentials of my Mini, but Moolticute doesn't realise that. When I connect the BLE, Mooltipass sees that the credentials are newer and prompts me to back up - and if I do, it'll silently and irreversibly overwrite the backup file containing my full credential set.

It would be nice if Moolticute had some kind of protection against this, especially while there's no way to keep a traditional USB Mooltipass and the BLE synchronised.

### Justification
While it does require the user to not be paying attention, and would only result in actual data loss if the original Mooltipass were lost before the overwritten backup was noticed, there's still a risk involved. Adding some kind of sanity check to see if the credentials list suddenly got a whole lot smaller, or simply having the automated monitoring refuse to do anything when switching between a USB Mooltipass and a BLE, would be a great safety feature.

### Workarounds
The only workaround at present is to pay really close attention to which device you've got plugged in before okaying a backup, or to make sure you've got a backup of the backup to hand!

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
@deXol this looks like a bug: why would we allow overwriting a file that is not associated with the user? Maybe when the user selects an existing file we should make sure that it is indeed a valid one... could you double check?

**Comment by deXol** [comment]
@limpkin I have checked the backup monitoring and there is a mapping between the backup file and cardid, so it should not be possible to override the file with an other card.
In #579 I enabled backup monitoring for BLE to and added some safety changes to make sure clearing cardid and backup path on device disconnection.

**Comment by limpkin** [comment]
@ghalfacree could you try to replicate this issue?

**Comment by ghalfacree** [comment]
@limpkin, @deXol: I can no longer replicate the issue using Moolticute v0.42.31-testing on Linux.

Now when I connect the BLE, the Synchronisation tab has nothing entered into Database Backup Monitoring, and therefore does not risk erasing an existing DB from a different device. There's also no automated "you haven't backed up in a while" message, again because backup monitoring isn't configured any more.

If I disconnect the BLE and reconnect my Mini, the Synchronisation tab springs back to life with my configured monitoring settings.

Looks like this is fixed - thanks!

**Comment by limpkin** [comment]
awesome!!!!
