### ISSUE TITLE
Feature request: Hide/disable settings which are only available when unlocked if Mooltipass is currently locked

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#577]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
At present, connecting a BLE to Moolticute *but not unlocking it* will bring up default settings for things like the keyboard input language. You can choose different settings in the drop-down, but as soon as you click "save to device" they'll return to default again. It's only when the BLE is unlocked that the settings update to display what they're actually set to, and allow you to make changes.

It'd be a lot nicer if instead of showing default settings and acting like you can change them when you can't, Moolticute greyed them out and prevented you from attempting to change them until the BLE is unlocked - preferably with a "Unlock the Mooltipass to change these settings" message.

### Justification
Simple justification: it doesn't matter how many times you say "unlock the Mooltipass to change these settings" in the documentation, if it's not in the app itself you're going to get people complaining they can't change the settings because they haven't unlocked the Mooltipass.

### Workarounds
Remember to unlock the Mooltipass first!

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
oh yep, that's in our todo :)
