### ISSUE TITLE
Feature request: (More) graceful handling of multiple devices

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#578]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
I've a MPM and a BLE here, and I'm juggling the two during the beta-test period. If I connect the MPM, Moolticute sees it fine; if I connect the BLE, Moolticute ignores it because it's already connected to the MPM - which is also fine.

If I disconnect the MPM, however, Moolticute will *not* connect to the BLE until I disconnect it and reconnect it again.

It'd be nice if Moolticute had a way to make it so I didn't have to do that. Perhaps issue a reset command to all connected Mooltipass devices upon the disconnection of one -  though if you've more than two (for some reason) it'd be a toss-up which resets and connects first, I guess.

Even better would be if Moolticute could hold a connection to multiple Mooltipass devices at once - perhaps with a tabbed interface that'd let me choose which of the connected devices I'm working with. Added bonus: that'd make transferring credentials from the MPM to the BLE easier (but, I appreciate, would likely be considerable work under the hood to make happen!)

### Justification
I'd imagine that a non-zero number of BLE buyers, especially early adopters, will already have a Mooltipass or MPM - so I'm not likely to be the only person connecting two devices to a single system!

### Workarounds
Either connect only a single device at a time, or put up with disconnecting and reconnecting the second device when you disconnect the first.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
@deXol is there anyway, once a device is disconnected, to recognize the other connected device without plugging and unplugging it again?

**Comment by deXol** [comment]
@limpkin I think on device disconnection we could do an enumeration for an other already connected MP device.

**Comment by limpkin** [comment]
@deXol good idea!

**Comment by limpkin** [comment]
I'll close this issue following this mitigation.

@ghalfacree feel free to create another issue to ask simultaneous mooltipass device support... but I doubt we'd implement it any time soon given the massive complexity
