### ISSUE TITLE
Infinite loop is circumstances to be determined

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#582]
Not sure how I managed to get there... but maybe knowing your internal logic you can have an idea :)

DEBUG: (2020-01-11T20:35:28.885) :0 - "Received answer: GET_CUR_CARD_CPZ (0x000b)"  Full packet: "05000b00010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
WARNING: (2020-01-11T20:35:28.885) :0 - Couldn't request card CPZ
CRITICAL: (2020-01-11T20:35:28.885) :0 - Loading card CPZ failed
INFO: (2020-01-11T20:35:28.885) :0 - "Loading device db change numbers"
DEBUG: (2020-01-11T20:35:28.885) :0 - Platform send command:  "GET_USER_CHANGE_NB (0x000a)"
DEBUG: (2020-01-11T20:35:28.885) :0 - Full packet# 0 :  "[0x04, 0x00, 0x0a, 0x00, 0x00, 0x00]"
DEBUG: (2020-01-11T20:35:28.945) :0 - Message payload length: 1
DEBUG: (2020-01-11T20:35:28.945) :0 - "Received answer: GET_USER_CHANGE_NB (0x000a)"  Full packet: "05000a00010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
WARNING: (2020-01-11T20:35:28.945) :0 - Couldn't request change numbers
CRITICAL: (2020-01-11T20:35:28.945) :0 - Loading change numbers failed
INFO: (2020-01-11T20:35:28.945) :0 - "Loading device card CPZ"
DEBUG: (2020-01-11T20:35:28.945) :0 - Platform send command:  "GET_CUR_CARD_CPZ (0x000b)"
DEBUG: (2020-01-11T20:35:28.945) :0 - Full packet# 0 :  "[0x84, 0x00, 0x0b, 0x00, 0x00, 0x00]"
DEBUG: (2020-01-11T20:35:28.990) :0 - Message payload length: 1
DEBUG: (2020-01-11T20:35:28.990) :0 - "Received answer: GET_CUR_CARD_CPZ (0x000b)"  Full packet: "05000b00010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
WARNING: (2020-01-11T20:35:28.990) :0 - Couldn't request card CPZ
CRITICAL: (2020-01-11T20:35:28.990) :0 - Loading card CPZ failed
INFO: (2020-01-11T20:35:28.990) :0 - "Loading device db change numbers"
DEBUG: (2020-01-11T20:35:28.990) :0 - Platform send command:  "GET_USER_CHANGE_NB (0x000a)"
DEBUG: (2020-01-11T20:35:28.990) :0 - Full packet# 0 :  "[0x04, 0x00, 0x0a, 0x00, 0x00, 0x00]"
DEBUG: (2020-01-11T20:35:29.050) :0 - Message payload length: 1
DEBUG: (2020-01-11T20:35:29.050) :0 - "Received answer: GET_USER_CHANGE_NB (0x000a)"  Full packet: "05000a00010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
WARNING: (2020-01-11T20:35:29.050) :0 - Couldn't request change numbers
CRITICAL: (2020-01-11T20:35:29.050) :0 - Loading change numbers failed
INFO: (2020-01-11T20:35:29.050) :0 - "Loading device card CPZ"
DEBUG: (2020-01-11T20:35:29.050) :0 - Platform send command:  "GET_CUR_CARD_CPZ (0x000b)"
DEBUG: (2020-01-11T20:35:29.051) :0 - Full packet# 0 :  "[0x84, 0x00, 0x0b, 0x00, 0x00, 0x00]"
DEBUG: (2020-01-11T20:35:29.110) :0 - Message payload length: 1
DEBUG: (2020-01-11T20:35:29.110) :0 - "Received answer: GET_CUR_CARD_CPZ (0x000b)"  Full packet: "05000b00010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

**Comment by deXol** [comment]
@limpkin: I was able to reproduce. If device is disconnected and lock from the menu in BLE, then connect with usb for some reason the GET_CUR_CARD_CPZ and GET_USER_CHANGE_NB fails. Cannot reproduce it if I lock the device with long press.
I will handle the infinite loop here, but I think there is also some difference between the two lock on fw side.

**Comment by Arffeh** [comment]
Ah yes, this just got me good. 

I left for lunch and came back to a 99c thermal throttling laptop from 100% battery to 22%.
moolticuted was having a fantastic time. :)
moolticuted was pegging a core with turboboost not letting up on the clockspeed (cheers intel). Interestingly in htop it seemed 2/3 of it was kernel time. Looking at the logs, it was spamming the above messages.

This was occurring whether device was plugged in locked or unlocked, using either a MP-BLE or MP-Mini.

OS: Arch Linux
Moolticute: git-0-9-8.r2.g2d985db / 0.42.27.testing.r8.gbe1a960-1
BLE: Main MCU: 0.18
BLE: Aux MCU: 0.13

**Comment by limpkin** [comment]
@deXol but in theory we're not supposed to ask card cpz is the status is locked though no?

**Comment by deXol** [comment]
Not with locked, but it fetched with unknown: https://github.com/mooltipass/moolticute/blob/master/src/MPDevice.cpp#L3472

**Comment by limpkin** [comment]
yep, that's normal behavior.

I think I will close this issue as this was tracked down to be a firmware issue where the device wouldn't push to moolticute its status... so the latter wouldn't know to stop sending that packet
