### ISSUE TITLE
Can not add ppa repository on (K)Ubuntu 19.10

### ISSUE THREAD

**Issue by BitPuffin** [mooltipass/moolticute#593]
### Expected behavior
Successfully add PPA repo on Kubuntu 19.10, using the add-apt-repository command as following the instructions on the website.

### Actual behavior
Adding repository fails  because it can not locate a Release file as shown in the following log:

```
 Packages for Moolticute.

This project aims to be an easy companion to your Mooltipass device and extend the power of the device to more platform/tools. With it you can manage your Mooltipass with a cross platform app, as well as provide a daemon service that handle all USB communication with the device.

For questions and bugs please contact https://github.com/mooltipass/moolticute/issues/new
 More info: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://jp.archive.ubuntu.com/ubuntu eoan InRelease
Hit:2 http://jp.archive.ubuntu.com/ubuntu eoan-updates InRelease                       
Hit:3 http://jp.archive.ubuntu.com/ubuntu eoan-backports InRelease                     
Hit:4 http://security.ubuntu.com/ubuntu eoan-security InRelease                                       
Ign:5 http://ppa.launchpad.net/mooltipass/moolticute/ubuntu eoan InRelease
Err:6 http://ppa.launchpad.net/mooltipass/moolticute/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mooltipass/moolticute/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

``` 

It seems like you could bypass the security requirements imposed here but it seems like it would not be a good idea to do so (or put users in the habit of doing it).

### Step by step guide to reproduce the problem

Install Kubuntu 19.10 and try to add the moolticute repository according to the instructions on themooltipass.com setup guide for ubuntu.

### Moolticute Version
Not relevant

### Operating System
Kubuntu 19.10
  
Other operating systems are not supported.

**Comment by ChrisCrewdson** [comment]
I have the same issue on Ubuntu 19.10

**Comment by limpkin** [comment]
eoan support added on the beta channel: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute-beta

release channel to follow :)
