### ISSUE TITLE
Feature request: "Don't check updates" option

### ISSUE THREAD

**Issue by SamantazFox** [mooltipass/moolticute#597]
### Missing feature
An option (checkbox) to enable/disable the "new version available" ping on startup

### Justification
I don't want any apps to auto-ping the internet without me asking it to do so.
Also I'd want to not have to press "No" every time I start the app.

### Workarounds
No

**Comment by limpkin** [comment]
Hello,
I'd be more on the side of firewall rules on the user's side. 
To be honest, I don't think we'll implement this any time soon given the extremely rare requests for it. However, feel free to make a PR for it.
