### ISSUE TITLE
(Missing)More details when mouse positioned over an option

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/moolticute#619]
### Expected behavior
If you position your mouse on the "General Settings" options there should be some more details like the other options provide. 
### Actual behavior
If you position your mose on the "Device Lock on USB Disconnection" option no more details are displayed. 
### Step by step guide to reproduce the problem
1) connect your Mooltipass Mini BLE with USB or Bluetooth
2) insert your smartcard and enter the pin
3) open Moolitcute and open the "Device Settings" tab.
4) position your mouse over the "Device Lock on USB Disconnection" option
5) no details are provided.

### Moolticute Version
v.0.42-41-testing

### Operating System
Mention if you are using either:
- Windows 10 Enterprise LTSB 2016

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
we're indeed missing a few helpers...

**Comment by limpkin** [comment]
@deXol 

Helpers for each item:
- Device Default Language: "Default language for your device"
- Current User Language: "Language used for your user profile"
- Bluetooth Keyboard Layout: "Keyboard layout used when typing characters over the Bluetooth interface"
- USB Keyboard Layout: "Keyboard layout used when typing characters over the USB interface"
- Knock detection sensitivity: "How sensitive to vibration your device should be"
- Display pin on back pressed: "Do not erase characters when going back in the pin entering screen"
- Prompt Animation: "Display an animation when an action is required
- Boot Animation: "Animation at device boot"
- Device Lock...: "Automatically lock the device when it is disconnected from USB"
