### ISSUE TITLE
Reset Clears Bundle but Card Becomes Unuseable

### ISSUE THREAD

**Issue by iaglet** [mooltipass/moolticute#627]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Ability to use card after device reset.

### Actual behavior
Card is invalid after reset and bundle install.

### Step by step guide to reproduce the problem
Reset BLE
Install bundle 19/13
Card is invalid. Cannot access it. No clear way even to wipe/reset it. Cannot restore credential file from backup to card.

### Moolticute Version - If Involved
v0.42.43-testing

### Firmware Version
AUX MCU version:  13
Main MCU version:  19

### Operating System
Mention if you are using either:
- Windows 10 Home build 19041.113
  
Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
But.... why did you reset your device? this is a debug menu that shouldn't be used...

**Comment by iaglet** [comment]
In hind-site? It was a mistake. I was trying to troubleshoot why the device wasn’t pairing as a keyboard with my iPhone and wanted to try and “reset” it so I could change the bluetooth pairing. Since pairing with only one device is currently implemented. I did not anticipate the side effects of the reset.

Regards, Stephen W
________________________________

**Comment by limpkin** [comment]
ahaha :). I'm not sure how we could handle pairing with multiple devices... I can imagine this would get complex fairly quickly

**Comment by iaglet** [comment]
For other bluetooth devices I have, I see two options.. one some things like headphones allow pairing to two devices. I rarely if ever have seen more than two. Others have a little plug you can insert into a port, like my mini mouse. I really have three devices with which I need it to work and the only one where bluetooth would really be necessary would be the phone so I can make it work.

Regards, Stephen W
________________________________

**Comment by limpkin** [comment]
we've just merged a PR that allows importing a backup file for an unknown card! i'm therefore closing this issue
