### ISSUE TITLE
100% CPU Usage after resume from suspend

### ISSUE THREAD

**Issue by NicoHood** [mooltipass/moolticute#640]
### Expected behavior
Normal CPU usage.

### Actual behavior
Moolticute uses 100% CPU after resume from suspend, and sometimes after a while, when the PC is running for days.

I've noticed this since a long time. I just never opened any bug report. It was not introduced in a recent version, I noticed this ~1 year ago already.

### Step by step guide to reproduce the problem
Run moolticute, suspend the pc, do not shutdown your pc for days.

### Moolticute Version
0.42.1

### Operating System
Archlinux
  
### Mooltipass Device
The Mooltipass Mini

**Comment by limpkin** [comment]
pinging @bobsaintcool to push the new release to arch

**Comment by bobsaintcool** [comment]
0.43.3-1 is live now

**Comment by limpkin** [comment]
@NicoHood is the issue still there?

**Comment by limpkin** [comment]
closing in a few days for inactivity

**Comment by NicoHood** [comment]
I had not issues so far, I will report once they occur again. It is somehow hard to test, but reproducible within a timespan of a few weeks. Could you maybe link the fix? I am curious what caused the issue. Thanks for fixing it so quick! :-)
