### ISSUE TITLE
Update does not work on macOS

### ISSUE THREAD

**Issue by k44me** [mooltipass/moolticute#650]
8<------------------------ BUG REPORT -----------------------------------------
### Actual behavior

My Moolticute (v0.41.5) tells me there is an update (v0.43.3). I download the update, push start, all from inside the moolticute application. And I get a window with a Warning: The following disk images couldn't be opened. And it lists Image: "Multicute-v0.43.3.dmg", Reason: "Image not recognized".

So I thought I should get the update manual, went to "https://www.themooltipass.com/" and followed the download instructions for macOS + Firefox. I expected of course to get v0.43.3 this way, but on the website the most current version seems to be v0.41.5. 

All of this does not exactly increase my trust in your software...

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello and thanks for your bug report ! 
v0.43.3 is relatively recent, we'll therefore investigate and fix this ASAP.
Our software is fully open source, we believe in trust through transparency.

**Comment by limpkin** [comment]
It seems we have identified the issue to come from github DNS....
On windows, denying the update prompt after file download and then restarting the file download solves the issue.
