### ISSUE TITLE
Breach of confidentiality

### ISSUE THREAD

**Issue by mpble** [mooltipass/moolticute#660]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
When pressing the eye button in the password field, the device asks for "Mgmg. access to", after acepting this on the BLE, the password is displayed

### Actual behavior
When pressing the eye button in the password field, the device asks for "Mgmg. access to", do not accept this on the BLE, the password is displayed after about 1 second

### Step by step guide to reproduce the problem
enter the database management
accept the permission on the BLE
select one set of credentials
press the eye button
ignore the request on the BLE
wait for about 1 second
password is displayed

### Moolticute Version
0.43.16

### Operating System
Mention if you are using either:
- MacOS (Catalina, 10.15.4) 
  
Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

**Comment by limpkin** [comment]
It is actually not a prompt! This is actually by design, as it is a parameter that can be changed in the settings menu: "login prompts".
It is the same parameter that allows you to login to website without approving the prompt
