### ISSUE TITLE
Update moolticute in macOS fails "image not recognised"

### ISSUE THREAD

**Issue by arieljt** [mooltipass/moolticute#661]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
When moolticute alerts that a newer version exists and you choose to update, it will install the newer version.
### Actual behavior
The update procedure fails. Please see attached screenshot.
### Step by step guide to reproduce the problem
Wasn't able to reproduce since I can't get the non latest macOS moolticute (I had v0.43.3), but looking at the updater .json at https://betas.themooltipass.com/updater_osx.json you can see the links point to a non-existing resource.
### Moolticute Version
v0.43.3
### Operating System
MacOS  
  
Other operating systems are not supported.
<img width="488" alt="Screenshot 2020-05-02 at 19 45 15" src="https://user-images.githubusercontent.com/50654434/80871879-c8d7b780-8cae-11ea-9850-4a5f867ab194.png">

**Comment by limpkin** [comment]
already fixed by 1dd4b3b3441d519700f7a450daa94b4c019da6b9
