### ISSUE TITLE
V0.43.16 won't open on OS X 10.15.4

### ISSUE THREAD

**Issue by danielbriggs** [mooltipass/moolticute#662]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
The app should open.

### Actual behavior
Apple appear to be blocking the latest 0.43.16 img.
“Moolticute” can’t be opened because Apple cannot check it for malicious software.

### Step by step guide to reproduce the problem
Try to open the app and it fails.

### Moolticute Version
0.43.16

### Operating System
- MacOS  10.15.4

### Mooltipass Device
- The Mooltipass Mini

8<------------------------ END BUG REPORT -------------------------------------

**Comment by danielbriggs** [comment]
<img width="532" alt="Screenshot 2020-05-10 at 15 05 40" src="https://user-images.githubusercontent.com/6650998/81501329-bae9ee00-92cf-11ea-80de-26fcd1cf791f.png">

**Comment by limpkin** [comment]
if i'm not mistaken, in the launcher, right click and click open. You'll then be offered the possibility to bypass that check.

**Comment by danielbriggs** [comment]
Thank you. I tried to downgrade to 0.43.3 (last Mac verison I could find in releases) and that also failed. So I have 0.43.16 another shot. Right clicking while holding "Alt/Option" give you the choice to overrride the security check. Thanks - so simple!

**Comment by limpkin** [comment]
awesome! hope you like our ecosystem :)
