### ISSUE TITLE
Support for batch importing: "LastPass CSV File"

### ISSUE THREAD

**Issue by xnike** [mooltipass/moolticute#663]
It'll be great to have a possibility to batch importing passwords. For example, from `LastPass CSV File` backup or other systems.

Maybe by reading any provided file line by line and applying some regexp to parse site/login/password/etc. Some pre-configured regexp for known file formats and possibility to choose custom one.

**Comment by limpkin** [comment]
we actually have a csv import feature!
bring up the advanced tab by pressing ctrl - shift - f2 :)
