### ISSUE TITLE
Moolticute ubuntu 20.04 focal fossa repository release file missing

### ISSUE THREAD

**Issue by hilakata** [mooltipass/moolticute#665]
When trying to install the moolticute extension on ubuntu 20.04 by adding the repo the following error message is displayed:

E: The repository 'http://ppa.launchpad.net/mooltipass/moolticute/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by limpkin** [comment]
Hello!

For the moment it is only in our beta release: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute-beta/+index?field.series_filter=focal

**Comment by hilakata** [comment]
Thanks for that!
It works. Any specific reason why it is on version 0.41.5 and not on 0.43.3?
Pushing my luck a little bit here... ;)
