### ISSUE TITLE
Moolticute losing connection to Mooltipass Mini

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/moolticute#666]
Unfortunately, I don't remember which version this started happening, but it was one of the newer ones with BLE support. I plug my Mini in, enter my password, and everything's fine. An hour or so later, Moolticute says to connect my Mooltipass, even though it is connected. I disconnect and reconnect my Mini, and things are working again. Before I upgraded a month or two ago, I had no issues.

**Comment by limpkin** [comment]
Hello,
Could you share with us your logs, that can be viewed in the settings tab?
Which OS are you using?

**Comment by RChadwick7** [comment]
I'm using Windows 8.1. Below is the log. I reset it last night, and found it had disconnected by this morning. I unplugged and replugged, and started looking for where the log was, Very soon after, I realized it had disconnected again, so this log should show two disconnections. I am marking the place where I know it disconnected the second time:



INFO: (2020-05-14T09:56:58.925) :0 - "Get random numbers from device"
INFO: (2020-05-14T09:56:58.943) :0 - Random numbers generated ok
DEBUG: (2020-05-14T10:06:58.927) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

INFO: (2020-05-14T10:06:58.927) :0 - "Get random numbers from device"
INFO: (2020-05-14T10:06:58.937) :0 - Random numbers generated ok
DEBUG: (2020-05-14T10:16:02.385) :0 - Device removed:  "{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  -  "\\\\?\\PCI#VEN_8086&DEV_0166&SUBSYS_14771043&REV_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-14T10:16:02.385) :0 - "\\\\?\\pci#ven_8086&dev_0166&subsys_14771043&rev_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  is not connected.
DEBUG: (2020-05-14T10:16:02.385) :0 - List usb devices...
DEBUG: (2020-05-14T10:16:02.386) :0 - Disconnecting devices
DEBUG: (2020-05-14T10:16:02.386) :0 - Mooltipass disconnected
DEBUG: (2020-05-14T10:16:02.386) :0 - Device added:  "{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  -  "\\\\?\\PCI#VEN_8086&DEV_0166&SUBSYS_14771043&REV_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-14T10:16:02.386) :0 - Not a mooltipass device:  "\\\\?\\pci#ven_8086&dev_0166&subsys_14771043&rev_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-14T10:16:58.925) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}
******************************* Here is where I realized Moolticute said device was disconnected, and I unplugged and replugged ***********************************

DEBUG: (2020-05-14T10:26:54.631) :0 - Device removed:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_01#7&12e54f8&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: (2020-05-14T10:26:54.632) :0 - "\\\\?\\hid#vid_16d0&pid_09a0&mi_01#7&12e54f8&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  is not connected.
DEBUG: (2020-05-14T10:26:54.638) :0 - List usb devices...
DEBUG: (2020-05-14T10:26:54.638) :0 - Disconnecting devices
DEBUG: (2020-05-14T10:26:54.643) :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_01#7&12e54f8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-05-14T10:26:54.643) :0 - "\\\\?\\hid#vid_16d0&pid_09a0&mi_01#7&12e54f8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"  is not connected.
DEBUG: (2020-05-14T10:26:54.643) :0 - List usb devices...
DEBUG: (2020-05-14T10:26:54.644) :0 - Disconnecting devices
DEBUG: (2020-05-14T10:26:54.645) :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_00#7&18f1e13d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-05-14T10:26:54.645) :0 - "\\\\?\\hid#vid_16d0&pid_09a0&mi_00#7&18f1e13d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"  is not connected.
DEBUG: (2020-05-14T10:26:54.645) :0 - List usb devices...
DEBUG: (2020-05-14T10:26:54.645) :0 - Disconnecting devices
DEBUG: (2020-05-14T10:26:54.646) :0 - Device removed:  "{a5dcbf10-6530-11d2-901f-00c04fb951ed}"  -  "\\\\?\\USB#VID_16D0&PID_09A0#5&7f73dfc&1&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"
DEBUG: (2020-05-14T10:26:54.646) :0 - "\\\\?\\usb#vid_16d0&pid_09a0#5&7f73dfc&1&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"  is not connected.
DEBUG: (2020-05-14T10:26:54.646) :0 - List usb devices...
DEBUG: (2020-05-14T10:26:54.646) :0 - Disconnecting devices
DEBUG: (2020-05-14T10:26:57.223) :0 - Device added:  "{a5dcbf10-6530-11d2-901f-00c04fb951ed}"  -  "\\\\?\\USB#VID_16D0&PID_09A0#5&7f73dfc&1&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"
DEBUG: (2020-05-14T10:26:57.223) :0 - Not a mooltipass device:  "\\\\?\\usb#vid_16d0&pid_09a0#5&7f73dfc&1&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"
DEBUG: (2020-05-14T10:26:57.238) :0 - Device added:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_00#7&18f1e13d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-05-14T10:26:57.238) :0 - Mooltipass Mini is connected
INFO: (2020-05-14T10:26:57.255) :0 - "Waiting job"
DEBUG: (2020-05-14T10:26:57.255) :0 - Mooltipass connected
DEBUG: (2020-05-14T10:26:57.256) :0 - Device added:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_01#7&12e54f8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-05-14T10:26:57.256) :0 - Device is already added:  "\\\\?\\hid#vid_16d0&pid_09a0&mi_01#7&12e54f8&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-05-14T10:26:57.256) :0 - Device added:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#VID_16D0&PID_09A0&MI_01#7&12e54f8&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: (2020-05-14T10:26:57.256) :0 - Device is already added:  "\\\\?\\hid#vid_16d0&pid_09a0&mi_01#7&12e54f8&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
INFO: (2020-05-14T10:26:57.704) :0 - "Exiting MMM"
DEBUG: (2020-05-14T10:26:58.087) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:58.393) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:58.705) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:58.928) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2020-05-14T10:26:59.019) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:59.330) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:59.642) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:26:59.954) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:00.266) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:00.580) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:00.893) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:01.204) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:01.518) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:01.831) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:02.142) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:02.456) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:02.769) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:03.079) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:03.393) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:03.706) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:04.017) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:04.330) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:04.642) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:04.956) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:05.269) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:05.579) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:05.893) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:06.203) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:06.518) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:06.830) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:07.143) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:07.455) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:07.766) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:08.081) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:08.393) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:08.705) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:09.018) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:09.332) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:09.643) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:09.954) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:10.268) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:10.579) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:10.895) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:11.205) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:11.518) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:11.829) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:12.142) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:12.455) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
DEBUG: (2020-05-14T10:27:12.767) :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"
CRITICAL: (2020-05-14T10:27:13.368) :0 - Failed to exit MMM
INFO: (2020-05-14T10:27:13.368) :0 - "Get random numbers from device"
INFO: (2020-05-14T10:27:13.370) :0 - Random numbers generated ok
DEBUG: (2020-05-14T10:27:13.503) :0 - received MPCmd::MOOLTIPASS_STATUS:  5
DEBUG: (2020-05-14T10:27:13.503) :0 - Update client status changed:  WSServerCon(0x40eacc0)
DEBUG: (2020-05-14T10:27:13.503) :0 - Update client status changed:  WSServerCon(0x40ebb80)
INFO: (2020-05-14T10:27:13.513) :0 - "Loading device parameters"
DEBUG: (2020-05-14T10:27:13.514) :0 - received MP version FLASH size:  8 Mb
DEBUG: (2020-05-14T10:27:13.515) :0 - received MP version hw:  "v1.2_mini"
DEBUG: (2020-05-14T10:27:13.516) :0 - received language:  146
DEBUG: (2020-05-14T10:27:13.518) :0 - received lock timeout enable:  0
DEBUG: (2020-05-14T10:27:13.520) :0 - received lock timeout:  60
DEBUG: (2020-05-14T10:27:13.522) :0 - received screensaver:  1
DEBUG: (2020-05-14T10:27:13.524) :0 - received userRequestCancel:  1
DEBUG: (2020-05-14T10:27:13.526) :0 - received userInteractionTimeout:  15
DEBUG: (2020-05-14T10:27:13.528) :0 - received flashScreen:  1
DEBUG: (2020-05-14T10:27:13.530) :0 - received offlineMode:  1
DEBUG: (2020-05-14T10:27:13.532) :0 - received tutorialEnabled:  0
DEBUG: (2020-05-14T10:27:13.534) :0 - received screenBrightness:  25
DEBUG: (2020-05-14T10:27:13.536) :0 - received set_knockEnabled:  1
DEBUG: (2020-05-14T10:27:13.538) :0 - received knock threshold:  15
DEBUG: (2020-05-14T10:27:13.540) :0 - received randomStartingPin:  0
DEBUG: (2020-05-14T10:27:13.542) :0 - received hashDisplay:  0
DEBUG: (2020-05-14T10:27:13.544) :0 - received lockUnlockMode:  1
DEBUG: (2020-05-14T10:27:13.546) :0 - received key after login send enabled:  1
DEBUG: (2020-05-14T10:27:13.548) :0 - received key after login send  43
DEBUG: (2020-05-14T10:27:13.550) :0 - received key after pass send enabled:  0
DEBUG: (2020-05-14T10:27:13.552) :0 - received key after pass send  40
INFO: (2020-05-14T10:27:13.553) :0 - Requesting change numbers
DEBUG: (2020-05-14T10:27:13.555) :0 - received delay after key entry enabled:  0
DEBUG: (2020-05-14T10:27:13.556) :0 - received delay after key entry  5
INFO: (2020-05-14T10:27:13.557) :0 - Finished loading device options
INFO: (2020-05-14T10:27:13.557) :0 - Mini firmware above v1.2, requesting serial number
INFO: (2020-05-14T10:27:13.557) :0 - "Send date to device"
DEBUG: (2020-05-14T10:27:13.557) :0 - Sending current date:  "148e"
INFO: (2020-05-14T10:27:13.558) :0 - Date set success
INFO: (2020-05-14T10:27:13.558) :0 - "Loading device card CPZ"
DEBUG: (2020-05-14T10:27:13.561) :0 - Card CPZ:  "b4b42f17d62f0506"
INFO: (2020-05-14T10:27:13.563) :0 - Finished loading card CPZ
INFO: (2020-05-14T10:27:13.563) :0 - "Loading device db change numbers"
DEBUG: (2020-05-14T10:27:13.566) :0 - dbChangeNumber set to file cache, emitting file cache changed
DEBUG: (2020-05-14T10:27:13.566) :0 - Sending files cache
DEBUG: (2020-05-14T10:27:13.566) :0 - dbChangeNumber match
DEBUG: (2020-05-14T10:27:13.567) :0 - Sending files cache
DEBUG: (2020-05-14T10:27:13.567) :0 - dbChangeNumber match
DEBUG: (2020-05-14T10:27:13.567) :0 - Send card db metadata
DEBUG: (2020-05-14T10:27:13.567) :0 - Sended card db metadata
DEBUG: (2020-05-14T10:27:13.567) :0 - Send card db metadata
DEBUG: (2020-05-14T10:27:13.567) :0 - Sended card db metadata
DEBUG: (2020-05-14T10:27:13.567) :0 - Credentials change number: 161
DEBUG: (2020-05-14T10:27:13.567) :0 - Data change number: 0
INFO: (2020-05-14T10:27:13.567) :0 - Finished loading change numbers
INFO: (2020-05-14T10:27:13.567) :0 - "Loading device serial number"
DEBUG: (2020-05-14T10:27:13.569) :0 - Mooltipass Mini serial number: 1125
INFO: (2020-05-14T10:27:13.569) :0 - Finished loading Mini serial number

**Comment by limpkin** [comment]
That's extremely odd... could you enable the debug logs, restart moolticute and try to give us the logs when this happens again? :)

**Comment by haadr** [comment]
Could you check if power saving for usb devices is enabled, and if so, disable it to see if it makes any difference? Would be strange if this was responsible, but it's all I can think of and might be worth a try.

https://superuser.com/questions/663511/windows-8-1-powering-off-usb-drives

**Comment by RChadwick7** [comment]
I had two hubs. One had Power Savings enabled, and the other was disabled. No idea if that was an issue, but I never had problems before upgrading Moolticute. I have noticed it went over 24 hours without disconnecting, and once it disconnected within 10 minutes. At least once, it reconnected on it's own. Would more logs help?

**Comment by RChadwick7** [comment]
Sorry, missed the message about debug logs. will do that now.

**Comment by RChadwick7** [comment]
Here's the log:

DEBUG: (2020-05-20T20:25:06.232) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:06.232) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:06.241) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:06.241) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:07.044) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:07.044) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:07.065) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:07.065) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:07.857) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:07.857) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:07.867) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:07.867) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:08.669) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:08.669) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:08.671) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:08.671) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:09.483) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:09.483) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:09.495) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:09.496) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:10.295) :0 - Platform send command:  "MOOLTIPASS_STATUS (0x00b9)"
DEBUG: (2020-05-20T20:25:10.295) :0 - Full packet# 0 :  "[0x00, 0xb9]"
DEBUG: (2020-05-20T20:25:10.303) :0 - Message payload length: 1
DEBUG: (2020-05-20T20:25:10.303) :0 - "Received answer: MOOLTIPASS_STATUS (0x00b9)"  Full packet: "01b90500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2020-05-20T20:25:10.365) :0 - Device removed:  "{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  -  "\\\\?\\PCI#VEN_8086&DEV_0166&SUBSYS_14771043&REV_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-20T20:25:10.365) :0 - "\\\\?\\pci#ven_8086&dev_0166&subsys_14771043&rev_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  is not connected.
DEBUG: (2020-05-20T20:25:10.365) :0 - List usb devices...
DEBUG: (2020-05-20T20:25:10.366) :0 - Disconnecting devices
DEBUG: (2020-05-20T20:25:10.366) :0 - Mooltipass disconnected
DEBUG: (2020-05-20T20:25:10.366) :0 - Device added:  "{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"  -  "\\\\?\\PCI#VEN_8086&DEV_0166&SUBSYS_14771043&REV_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-20T20:25:10.366) :0 - Not a mooltipass device:  "\\\\?\\pci#ven_8086&dev_0166&subsys_14771043&rev_09#3&11583659&0&10#{e6dfdc31-31d0-46ac-86af-da1eb05fc599}"
DEBUG: (2020-05-20T20:25:56.348) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2020-05-20T20:35:56.344) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2020-05-20T20:45:56.345) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2020-05-20T20:55:56.346) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2020-05-20T21:05:56.588) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

**Comment by limpkin** [comment]
this is baffling... could you try another usb cable?

**Comment by RChadwick7** [comment]
I've tried another one, with the same results. 
I've found that, when it loses connection, instead of unplugging and re-plugging the Mooltipass, I simply kill and restart Moolticute, and it recognizes it fine.

**Comment by RChadwick7** [comment]
I think I may have found the issue. Mooltcute was configured to back up it's database to a network share, and that share was temporarily down. This might explain why it affected multiple mooltipasses on multiple devices. Also, since I fixed the network share about a month ago, I have had zero issues.

**Comment by haadr** [comment]
Interesting! Ideally this should be visible I'm moolticute somehow maybe, with the caveat that I'm not sure how the db backups are handled 🤔

**Comment by limpkin** [comment]
holy molly... thanks for the information @RChadwick7 !!! 
@deXol : an easy fix in mind? :)

**Comment by limpkin** [comment]
@RChadwick7 which moolticute version do you have right now? :)

**Comment by RChadwick7** [comment]
I have version 0.44.0

**Comment by limpkin** [comment]
@RChadwick7 is this still happening?

**Comment by RChadwick7** [comment]
I don't recall having this issue in a long while, including on computers I use away from home and unable to backup or see the backup file. I think it's good. Thanks!

**Comment by limpkin** [comment]
awesome :D
