### ISSUE TITLE
Feature request "Cancel credentials request after"

### ISSUE THREAD

**Issue by rms5566** [mooltipass/moolticute#674]
### Missing feature
Cancel credential request after .. seconds option in Moolticute.
### Justification
The option is already present in the categorie "Inactivity" but it is not enabled. You can change the seconds but nothing happens on the Mooltipass Mini BLE. 

### Workarounds
There are no workarounds

**Comment by limpkin** [comment]
@deXol can you set the checkbox as enabled? :D
