### ISSUE TITLE
Credentials Synchronisation up to date message

### ISSUE THREAD

**Issue by rms5566** [mooltipass/moolticute#675]
### Expected behavior
If you allow Moolticute to update the exported credentials database it should stop asking to export the database again until there is a change inside the Mooltipass credential database
### Actual behavior
It still wants you to export the database even if you done it already
### Step by step guide to reproduce the problem
1) enter smartcard an pin
2) add a credential to the Mooltipass
3) you see a message in Moolticute that the database changed
4) accept to export the database and accept the prompt on the mooltipass
5) the message if you want to update your Database should dissapear but it is still there
### Moolticute Version
v0.43.17-testing

### Operating System
- Windows 10 Enterprise 2016 LTSB

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
that's surprising... we actually have automated tests to prevent this...

**Comment by ThunderKing54** [comment]
So you can't reproduce it?

**Comment by limpkin** [comment]
didn't try yet :)

**Comment by ThunderKing54** [comment]
Oh okay 😄

**Comment by ThunderKing54** [comment]
So I tried it again with two devices now! It seems that it won't export the backup file. I tried to import the database on the new Mooltipass and it indeed worked but it was a pretty old backup but I synchronised it before. It only worked when I exported the Database as the filename which Moolticute checks for database updates.

**Comment by limpkin** [comment]
fixed.
