### ISSUE TITLE
Credentials in Backup file are more recent when uploading a file to the Mooltipass

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/moolticute#678]
### Expected behavior
If you upload a file to the Mooltipass Moolticute should not display the messge: "Credentials in the backup file are more recent. Do you want to import credentials to the device?"
### Actual behavior
If you upload a file to the Mooltipass Moolticute display the messge: "Credentials in the backup file are more recent. Do you want to import credentials to the device?"
### Step by step guide to reproduce the problem
1) enable Credentials synchronisation
2) upload a file to the Mooltipass
3) Moolticute displays the messsage that the Credentials in the backup file are more recent
4) I have to click no for 10 times until the message dissapear.
### Moolticute Version
v0.43.17-testing
### Operating System
Mention if you are using either:
- Windows 10 Enterprise 2016 LTSB

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
i'm closing this old issue as we were not able to replicate it, therefore guessing we fixed it with our last updates :)
