### ISSUE TITLE
Failed to build app with msvc2015

### ISSUE THREAD

**Issue by medyakovvit** [mooltipass/moolticute#68]
Error:
D:\Projects\moolticute\repo\src\PasswordLineEdit.cpp:323: see reference to class template instantiation 'std::uniform_int_distribution<char>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\random:2387: error: C2338: invalid template argument for uniform_int_distribution

the reason is using char instead of int as template argument.

**Comment by raoulh** [comment]
This is not supported, we are building with mingw64 on windows not msvc
