### ISSUE TITLE
Screen dim when you press the "Save to device" button after device switching

### ISSUE THREAD

**Issue by rms5566** [mooltipass/moolticute#686]
### Expected behavior
When you switch devices the “Save to Device” should be disabled for 5 seconds until everything is imported and loaded from the attached device.
### Actual behavior
When you switch devices the “Save to Device” button is still there for about 1-2 second and you're able to damage the device database. Then the decives screen dim.
### Step by step guide to reproduce the problem
1. Connect your first Mooltipass and go to the Device Settings Menu
2. Change the setting “For slow computers: wait …”
3. Don’t press the “Save to device” button!
4. Disconnect your first Mooltipass and make yourself ready to connect the second one
5. The Device Settings window disappear. Move your mouse where the button “Save to device” should be.
6. Now connect the second Mooltipass and at the same time you’re able to see the “Save to device” button for 2 seconds until the settings of the new Mooltipass are loaded. Be fast and klick that button! Now the screen dim.

### Moolticute Version
v0.43.20-testing
### Operating System
- Windows 10

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

### Mooltipass Device
- The Mooltipass Mini BLE with SN and without

**Comment by limpkin** [comment]
that was fixed on the hw side of things
