### ISSUE TITLE
Management Mode: Favorite Conflict

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#688]
![image](https://user-images.githubusercontent.com/6170291/85435122-4f11cb00-b587-11ea-9f67-5a02fb0bf15f.png)

In MMM, when assigning a new category to a given credential, the favorite list doesn't update with the favorites associated to that category

**Comment by limpkin** [comment]
it also seems like you can't change the credential category and set the favorite at the same time.

**Comment by deXol** [comment]
@limpkin: Favorites and the credential informations are persisted on different logic. Until the category change is not confirmed the favorites are listed for the previous category. Thats why the first favorite is also taken.

**Comment by limpkin** [comment]
that's not really intuitive :(

**Comment by deXol** [comment]
> that's not really intuitive :(

Yes, I will investigate further if I can do something about it, but in worth case I was thinking about if category is changed until it is not confirmed or discarded disable favorite change.
