### ISSUE TITLE
Favorite is lost when a category is set

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/moolticute#690]
### Expected behavior

When a category is set on a credential with favorite set, favorite is set

### Actual behavior

When a category is set on a credential with favorite set, favorite is lost

### Step by step guide to reproduce the problem

1. Set a category on a credential that already has a favorite position
2. Confirm the change
3 . Category is set, but the credential has no more favorite 

### Moolticute Version
0.44.1-testing

### Operating System
- Windows 10

### Mooltipass Device

- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
So when operating a category change, you'd like a credential tagged as favorite to take any favorite slot of the other category, right?

**Comment by elendil-software** [comment]
Yes, that's what I was expecting.

Or maybe as an option by showing a dialog box asking if it has to be set as favorite.
