### ISSUE TITLE
[OSX]Moolticute UI randomly freezes

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#692]
### Expected behavior

When shutting down the Mac with Moolticute window running it should do so without locking up

### Actual behavior

It doesn't shut down properly. Only after force quitting the Moolticute window the Mac will continue its shutdown

### Step by step guide to reproduce the problem

Open Mooltiecute on a Mac and try to shut the system down
Mooltipass doesn't need to be connected for this

### Moolticute Version

0.44.0

### Operating System
Mention if you are using either:
- MacOS: 10.15.5

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
@deXol can you try to replicate? I wasn't able to :(

**Comment by KDederichs** [comment]
It doesn't seem to occur every time it seems...
Maybe it has something to do with how long it's been running?

**Comment by KDederichs** [comment]
Actually it might be more of a general unresponsiveness that happens sometimes.
I noticed the ui just hangs in those cases (with the spinning mouse cursor) and you have to force quit it anyways, regardless of shutting down or not.
Daemon still seems to work in that case just the UI is unresponsive

**Comment by KDederichs** [comment]
On that note @limpkin is there maybe some kind of log file for the UI/Daemon?
I know there's a log viewer but unfortunately that freezes as well when the UI freezes.
I'd like to find what's causing it but it's proving difficult.

**Comment by KDederichs** [comment]
On another note I just noticed:
Once the UI Freezes and you force quit it, you can not start it again it seems.
It will just continue to not respond at startup and not open the UI.

Tried it both with attatched multipass and detatched

**Comment by KDederichs** [comment]
Still a thing in 0.45.0 btw

**Comment by KDederichs** [comment]
Trying to get this to happen while debugging the UI and the daemon btw.
Doesn't seem to work though, either cause it's attatched to the debugger (race condition of some sort maybe?) or maybe cause it's compiled on my system...
Strange

**Comment by KDederichs** [comment]
Actually I noticed that when it does freeze you get this Message:
![Screenshot 2021-05-22 at 16 47 09](https://user-images.githubusercontent.com/24696606/119230627-6356a300-bb1d-11eb-85da-04830390dc3a.png)
Maybe it's hanging itself there

**Comment by limpkin** [comment]
@KDederichs to open a new one :)
