### ISSUE TITLE
SSH Key support missing

### ISSUE THREAD

**Issue by dnns01** [mooltipass/moolticute#694]
### Missing feature
Ability to store SSH Keys in minible
### Justification
The Mooltipass Mini had the opportunity to store private keay for SSH inside the device, and use the ssh agent to handle ssh connections. When I try to import SSH keys via moolticute and select the "Load keys" button, Moolticute tells me, that it is waiting for a confirmation on my device. But there is no prompt on the device to confirm.

### Workarounds
No workaround known

**Comment by bryanlyon** [comment]
I personally got SSH to store keys, but find that "Waiting for device confirmation" on almost all tasks when wireless.

**Comment by limpkin** [comment]
unless i'm mistaken, this is now working, no?

**Comment by limpkin** [comment]
@bryanlyon that's odd.... can you send a message to support[at]themooltipass[dot]com?
