### ISSUE TITLE
Moolticute installer on Windows 10 blocked by Edge and Windows defender

### ISSUE THREAD

**Issue by fc-projects** [mooltipass/moolticute#699]
# Expected behavior
No warning from the browser nor the firewall

### Actual behavior
The new Edge browser warn about potential security issue at the end of the download
It is still possible to bypass the warning, then Windows defender warn again when running the installer
There is no problem for one knowing what he is doing but these warnings can scare a newcommer and send a really bad signal for an application that claim to increase security.
When bypassing the warning from Edge there is a possibility to indicate the file is not harmful and an option to check if you are the owner of the application.

### Step by step guide to reproduce the problem
Download moolticute_setup_v0.44.0.exe installer with the new Edge browser (first warning at the end of the download)
![Moolticute edge download warning](https://user-images.githubusercontent.com/31821960/90620318-937db800-e212-11ea-90eb-bb1b471a718b.PNG)

Try to run the installer (2nd warning by Windows defender)
![Windows defender warning](https://user-images.githubusercontent.com/31821960/90620845-477f4300-e213-11ea-9404-49adff522437.png)

### Moolticute Version
0.44.0

### Operating System
Windows 10

### Mooltipass Device
N/A

**Comment by limpkin** [comment]
I'm afraid there isn't much we can do until our signing key gets more reputation...

**Comment by limpkin** [comment]
it's finally not happening anymore!!!! woohoo!

**Comment by fc-projects** [comment]
Nice to hear! This means your software has finally gained the required notoriety!
Great achievement!
