### ISSUE TITLE
[MacOS] Big Sur beta :: Moolticute.app hangs when opened 

### ISSUE THREAD

**Issue by kaysersoze** [mooltipass/moolticute#710]
### Expected behavior
Moolticute.app should open and icon should be displayed in menubar.

### Actual behavior
- Moolticute.app does not open and hangs, consuming ~99% CPU usage in Activity Monitor. 
- No icon is displayed in menubar. 
- Application must be Force Quit.
- `moolticuted` _does_ run (correctly) in background

### Step by step guide to reproduce the problem
- Download Moolticute v0.44.0 for MacOS
- Copy Moolticute.app from .DMG file to /Applications
- Right-click Moolticute.app and Open application
- Allow MacOS to run software from unknown developer
- Moolticute.app hangs

### Moolticute Version
v0.44.0

### Operating System
Mention if you are using either:
- MacOS (Big Sur) 11.0 Beta 20A5364e (beta 6, also present on beta 5)

### Mooltipass Extension
N/A

### Mooltipass Device
Mooltipass Mini

### Additional Comments
As mentioned above, it appears that only Moolticute.app is hanging on running and `multicuted` appears to be running correctly (can connect to device, etc).

I was able to build and run Moolticute.app (and `moolticuted`) from source on Big Sur, and it did in fact run correctly, so it's likely some change(s) in API from Catalina to Big Sur. Moolticute.app was connecting to the downloaded `moolticuted` - I have not yet tested running the compiled `moolticuted`.

Are there any instructions on creating the full application release bundle for MacOS? I'd like to include the `moolticuted`, `mc-agent`, and `mc-cli` as well as the Qt libraries in a self-compiled bundle if possible.

Please let me know if/how I can be of any assistance.

**Comment by KDederichs** [comment]
Can confirm that's still the case in the released version of Big Sur.

**Comment by Ebert-Hanke** [comment]
I can also confirm this. The app does not seem to work at all in Big Sur. I reinstalled the app but this did not fix it. 
Process "moolticute" crashes on startup with almost maxing out CPU. 
It was also running rather unstable in Catalina and crashed a lot.

**Comment by limpkin** [comment]
fixed from https://github.com/mooltipass/moolticute/releases/tag/v0.44.21
