### ISSUE TITLE
Credential management mode does not work on database imported from Mini 1.0.

### ISSUE THREAD

**Issue by GlitchOne** [mooltipass/moolticute#747]
### Expected behavior
A user can enter credential management mode for credentials imported from their Mooltipass Mini 1.0.

### Actual behavior
Credential management mode crashes and the moolticute daemon stops when enabling credential management mode while connected to Mini BLE.

### Step by step guide to reproduce the problem
Open Moolticute v0.44.11-testing.
Connect a Mooltipass Mini 1.0 (v1.2_mini) to the computer.
Export a database that has both normal and favorited credentials from the Mini 1.0.
Disconnect the Mini 1.0.
Connect a Mini BLE via a USB-C cable.
Import the database to the Mini BLE with a fresh card.
Go to the credentials tab and click Enter Credentials Management mode.

After this, the Daemon force closes and it needs to be restarted from the taskbar by right clicking on the Moolticute icon.

### Moolticute Version - If Involved
Moolticute v0.44.11-testing.

### Firmware Version
AUX MCU version:  41
Main MCU version:  48

### Operating System
Windows 10 Pro, Version 2004, Build 19041.508

**Comment by limpkin** [comment]
that's interesting... could you try again, removing said favorites?

**Comment by GlitchOne** [comment]
It would seem that my assumptions were not correct. Removing the favorites does not in fact fix the issue.

**Comment by limpkin** [comment]
could you try another usb cable? (sorry for the lag)

**Comment by GlitchOne** [comment]
The behavior is the same with another known-good cable.

**Comment by limpkin** [comment]
could you enable the dev logs, restart moolticute, reproduce the issue and give us the logs?
maybe in private to my email.

**Comment by GlitchOne** [comment]
I have sent you an e-mail with two log files.

**Comment by limpkin** [comment]
oh... it seems you need to update your firmware to the latest one :). I've fixed what I'm seeing here :)

**Comment by limpkin** [comment]
fixed
