### ISSUE TITLE
Exporting Credentials while in MGMT mode causes failure when saving MGMT mode

### ISSUE THREAD

**Issue by kbembedded** [mooltipass/moolticute#816]
### Expected behavior
Exporting credentials while in credential management mode, kicks the MP out of credential management mode, but moolticute stays in this mode and lets changes happen. Then, saving changes fails.

### Actual behavior
See above.

### Step by step guide to reproduce the problem
1) Create new credentials, "deleteme.com" "deleteme" "deleteme"
2) Verify notice at bottom of moolticute saying credentials are out of date, would you like to export
3) Enter credential management mode
4) Verify notice at bottom of moolticute saying credentials are out of date, would you like to export
5) Export credentials
6) Remove the "deleteme.com" account
7) Press save all changes
8) Observe failure

Log snippet:
DEBUG: (2021-03-01T19:33:56.210) :0 - MMM Save: tackling  "USER"  for service  "SERVICE"  at address  "IM_NOT_SURE_IF_THIS_NEEDS_TO_BE_OBFUSCATED"
CRITICAL: (2021-03-01T19:33:56.210) :0 - Error in our local DB (algo PB?)
INFO: (2021-03-01T19:33:56.210) :0 - "Exiting MMM"
CRITICAL: (2021-03-01T19:33:56.212) :0 - Failed to exit MMM

### Moolticute Version
0.45.2

### Operating System
Mention if you are using either:
- Windows 10

### Mooltipass Device
Mooltipass Mini

**Comment by limpkin** [comment]
thanks a lot for the report!
@deXol can we hide the notification in MMM in that case?
