### ISSUE TITLE
Moolticute hangs if you refuse database management during monitored sync export

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#828]
I fired up my Mooltipass Mini BLE today and Moolticute told me the device was newer than the monitored database export, so I told it to refresh the backup. As always, the Mooltipass popped up the "Manage Database?" prompt... but this time I accidentally knocked the wheel as I was pushing it in, hitting no instead of yes.

### Expected behavior
Moolticute cancels the export process.

### Actual behavior
Moolticute told me to retry, but then just sat at "Please Approve Request on Device" - no additional prompt appeared on the Mooltipass, and Moolticute does not respond to any interaction. Additionally, it's causing Xorg to eat up an entire CPU core at 100% load.

You can click the cross to close Moolticute, but if you bring it back up again it's still hung. Right-clicking on the tray icon and choosing Quit closes the program correctly, and the Xorg thread stops spinning.

### Step by step guide to reproduce the problem

1. Add a new credential.
2. Lock/disconnect the Mooltipass.
3. Unlock/connect and unlock the Mooltipass.
4. Answer yes to Moolticute's offer to update the backup.
5. Answer no to the Mooltipass's prompt to allow database management.
6. Try to do absolutely anything in Moolticute.

Note this *only* works if you're using the backup monitoring system and responding to the monitor prompt; if you manually export with Export To File in Synchronisation and cancel the database management prompt, Moolticute remains responsive and works normally.

### Moolticute Version
v0.45.6-testing

### Operating System
Ubuntu 20.04.2 LTS 64-bit

### Mooltipass Device
Mooltipass Mini MBLE, Main 0.58 Aux 0.69.

**Comment by deXol** [comment]
Hello @ghalfacree,

This issue was fixed in #826 and the next release will contain it.
