### ISSUE TITLE
Custom delay between enter key and password for _unlock_

### ISSUE THREAD

**Issue by uniacke1** [mooltipass/moolticute#829]
### Missing feature

Please extend (or add a configurable) delay between sending the "enter" key and the password for _unlock_. 

Sometimes Win10 will sit and do things for a few seconds before it presents the password prompt after pushing a key to get off the lock screen. This means the password entry is missed and you have to manually go in and select the credential, decline username entry, and send the password... defeating the purpose of this feature entirely. 

### Justification
Because Windows 10 is being annoying and trying to do things instead of just bring up the login prompt.

### Workarounds
Yes, see description. Or, you have to change to "password only" and then manually hit a key and wait for the password box to appear.

**Comment by limpkin** [comment]
oh that's a good one

**Comment by limpkin** [comment]
implemented
