### ISSUE TITLE
Avast claims Moolticuted.exe is infected with IPD.Generic

### ISSUE THREAD

**Issue by GeekAnnoyed** [mooltipass/moolticute#837]
### Expected behavior
open as normal 
### Actual behavior
Avast opens with a warning about  IPD.Generic after installaion and a reboot

### Step by step guide to reproduce the problem
install Moolticute from githhub
turn on sshd
reboot PC
login and start moolticute
avast gives warnings

### Moolticute Version
0.46.3

### Operating System
Mention if you are using either:
- Windows 10
-  Avast Free 21.4.2464 (build 21.4.6266.670)
-  AntiVirus defintions  210607-6
- 
  ### Mooltipass Device
I was just getting things ready for my Mooltipass Mini BLE to arrive

![avast](https://user-images.githubusercontent.com/822758/121137750-e589db80-c82e-11eb-8418-91a163320af2.jpg)

**Comment by limpkin** [comment]
Hello there!

It looks like a false positive... we'll get in touch with avast then.

**Comment by GeekAnnoyed** [comment]
I did assume so, but I thought it was worth mentioning to you

**Comment by limpkin** [comment]
reported, should be fixed now
