### ISSUE TITLE
[OSX] Advanced/SSH Tabs don't appear

### ISSUE THREAD

**Issue by GuillaumeHemmen** [mooltipass/moolticute#843]
### Expected behaviour
- Be able to Toggle Advanced and SSH tabs as instructed in the manual (Mooltipass Mini BLE User Manual – 2021/06/08, chapter H page 29).

### Actual behaviour
- The display of SSH and Advanced Tab is not working.

### Step by step guide to reproducing the problem
- Get the app for macOS.
- Run the app.
- Try the shortcut "CTRL+SHIFT+F1" and "CTRL+SHIFT+F2" (you might need to use the "FN" button to enable the functions keys).
- The corresponding tab(s) doesn't appear.

### Moolticute Version
- v0.46.4

### Operating System
- macOS  

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
could you try Shift+Fn+Cmd+F2 / F3 ? we will update the user manual :)

**Comment by GuillaumeHemmen** [comment]
This solved the issue; thanks a lot @limpkin! 

Should I mark the ticket as resolved and close it or let it open until the manual is updated and put online?

**Comment by limpkin** [comment]
i've updated the user manual :)
