### ISSUE TITLE
No option to delete notes?

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#846]
Apologies if this is in the queue, but I wanted to flag it up just in case: there doesn't appear to be a way to delete notes (or, if there is, I'm too stupid to find it.)

### Expected behavior
When you've created a new note and saved it to the Mooltipass, you should be able to delete the note as well as edit it.

### Actual behavior
You can edit the content of a previously-created note, but not the title - and you can't delete it. There's no 'delete' button in the edit screen or the note list screen, and right-clicking does nothing.

There's also a secondary, more minor bug: deleting the entire contents of a note doesn't make the 'save' button appear; there needs to be at least one character in the note (even a space or a carriage return) in order for Moolticute to register it as changes that need to be saved.

### Step by step guide to reproduce the problem

1. Create note
2. Save note
3. Attempt to delete note
4. Bonus bug: Open the note, select all, delete, attempt to save changes

### Moolticute Version
v0.46.6-testing

### Operating System
Ubuntu 20.04

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
Agreed, I'm going to implement on the mini ble side of things a command to delete files and notes so we don't need to enter file MMM.

**Comment by limpkin** [comment]
implemented on the mini ble in https://github.com/mooltipass/minible/commit/83c3d3198c60ef2e7c5e8c72d527b1472d72cd82

**Comment by limpkin** [comment]
implemented
