### ISSUE TITLE
United Kingdon keyboard on bluetooth connection sends wrong characters

### ISSUE THREAD

**Issue by GeekAnnoyed** [mooltipass/moolticute#848]
<------------------------ BUG REPORT -----------------------------------------
### Expected behaviour

Enter via Bluetooth password with # in the password.

### Actual behaviour
Enter Password via Bluetooth to a mobile phone and I get / in the place where # was meant to be 

### Step by step guide to reproduce the problem
Open mooltipass and manually enter a username /password (my case this was Spotify) 

### Moolticute Version
0.46.3

### Operating System
Mention if you are using either:
- Windows 10
- Andriod 11 (redmi note 10 5g)

### Mooltipass Device
These are the settings I'm using
![Untitled](https://user-images.githubusercontent.com/822758/121903559-55f99680-cd20-11eb-8d9a-717eed30ac9d.jpg)

- The Mooltipass Mini BLE
- also tried it with the United Kingdom layout and same results 
- when I type the same password to a notepad on Windows 10 it is correctly entered.
- 
<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
Hello there!
Could you double check that on your phone, the external keyboard is also set as UK? 
I'm asking as in my case it defaults to another layout.

**Comment by GeekAnnoyed** [comment]
Hi there,
Just double-checked, and it was set to UK (it was the google gboard keyboard)
I couldn't find a setting for bluetooth keyboard settings, just in case there was such a thing

**Comment by GeekAnnoyed** [comment]
Just checked on the mooltipass, and it shows the correct password.

**Comment by limpkin** [comment]
could you connect to your computer using bluetooth and try to type a password this way?
My goal here is to see if it's a phone related issue.

**Comment by GeekAnnoyed** [comment]
No worries, I understand. 
I don't have Bluetooth on my PC, but I've ordered a dongle, and will update tomorrow.
I do have a spare phone z2 Force that isn't in use and I tried it on that and the issue persist.

**Comment by GeekAnnoyed** [comment]
Sorry for delay, I had to buy a Bluetooth dongle.

Mooltipass BLE to windows 10 via Bluetooth works correctly

MP BLE to Android 11 running Gboard keyboard in English (United Kingdom) doesn't send the correct symbol
MP BLE to Android 11 running linageOS with the default keyboard doesn't send the correct symbol
MP BLE to GalaxyTab A (2018 10.5) running Android 10 on default keyboard doesn't send the correct symbol

sorry, I don't own any other devices to test this with

**Comment by GeekAnnoyed** [comment]
Okay, after much playing I think I've worked out the issue

My keyboard is a self build redox [ https://github.com/mattdibi/redox-keyboard]( https://github.com/mattdibi/redox-keyboard) and while it's cool in every aspect, it is a USA layout. And I use a UK layout on the board.

The Mooltipass device is using USA English on the display, so this is why I didn't spot this sooner.

I was using it as the  UK layout on the mootlipass virtual keyboard and on my phone and that must cause some issues as the passwords were all saved in the P/W manager manually with the keyboard in Windows 10 set to an English, British layout

I'm not sure if this is a bug in the Mooltipass, or Moolicute any more, or a feature request for a UK device layout on the mooltipass itself.

**Comment by limpkin** [comment]
Hello!
Sorry it took us so long to get back to you :/. that keyboard is slick :).
I may be mistaken... but in theory you should be able to select UK layout on the device itself no?

**Comment by GeekAnnoyed** [comment]
No worries, I totally understand you are busy. Thank you, it was a fun project to build (the keyboard)

I kinda fixed it by manually updating passwords again and they seem to work again.

I've got a UK layout, my PC keyboard, but I'm not 100% sure if I set it up right as I did it over a year ago now GeekFail
and setting the  as follows fixed it for me
![Screenshot from 2021-07-13 15-12-10](https://user-images.githubusercontent.com/822758/125467466-71aa8d19-7f4c-4d48-9acf-3f5a2d87dfc2.jpg)

I think it was a input/output miss match (writing in US and out on a UK keyboard layout) so all my error , sorry

**Comment by limpkin** [comment]
:)
