### ISSUE TITLE
Microsoft Defender Smartscreen Unrecognized App (with solution)

### ISSUE THREAD

**Issue by CubeCentral** [mooltipass/moolticute#857]
### Expected behavior
Expect downloaded Moolticute app to install 
### Actual behavior
Downloaded Moolticute app triggers Microsoft Defender Smartscreen, saying "Windows Protected Your PC".  
### Step by step guide to reproduce the problem
Download Moolticute app from website and save in usual place.
When run, the Microsoft Defender Smartscreen warning appears:
![moorunbl](https://user-images.githubusercontent.com/37314108/122625498-a21b4280-d062-11eb-9927-f981cf044e75.png)

You can proceed by selecting "More Info" and then "Run Anyway" on the following popup:
![moorunok](https://user-images.githubusercontent.com/37314108/122625520-bfe8a780-d062-11eb-9e7e-c546d3a19d9b.png)

### Moolticute Version
moolticute_setup_v0.46.3.exe

### Operating System
Windows 10

### Mooltipass Device
The Mooltipass Mini
The Mooltipass Mini BLE

### Solution
After downloading the Moolticute app to the usual place, explore there and then right-click on the downloaded file.
At the bottom of the properties screen, notice the warning "This file came from another computer and might be blocked to help protect this computer" followed by a checkbox.  Check this checkbox, click apply, click ok.
![dlprop](https://user-images.githubusercontent.com/37314108/122625526-cb3bd300-d062-11eb-8685-1cab3696767a.png)

Now run the downloaded Moolticute app as usual, and Microsoft Defender Smartscreen will not appear.

Images, screenshots:  https://imgur.com/a/SSNgjoY

**Comment by principis** [comment]
@CubeCentral You can just click "Run Anyway", which has the same effect as the Unblock checkbox.

"Run Anyway" should also increase the reputation of the certificate with which the installer is signed, so that the warning shouldn't popup anymore in the future.

**Comment by CubeCentral** [comment]
Oh that’s interesting, I wasn’t aware that warning would “phone home” to check the hash and reputation.  Neat!

**Comment by limpkin** [comment]
can't believe it's taking so long for our reputation ton increase...

**Comment by CubeCentral** [comment]
Is there a way to check it or monitor it?  Would one person setting it up again and again help?

**Comment by limpkin** [comment]
i've installed moolticute a few days ago on a newly formatted computer, we don't have this issue anymore :)
