### ISSUE TITLE
Bug: Can't change\modify TOTP

### ISSUE THREAD

**Issue by Properrr** [mooltipass/moolticute#858]
### Expected behavior
Edit\remove\change TOTP is possible

### Actual behavior
No way to change TOTP for an account

### Step by step guide to reproduce the problem
1)Activate the Management mode
2)Add TOTP for credentials
3)Disable the Management mode
4)Activate the Management mode
5)Find credential with TOTP

### Moolticute Version
0.46.3

### Operating System
Mention if you are using either:
- Windows 7/10
  
Other operating systems are not supported.

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
@deXol next task :)

**Comment by limpkin** [comment]
implemented :)
