### ISSUE TITLE
How to transfer passwords from mini to mini BLE

### ISSUE THREAD

**Issue by ajira86** [mooltipass/moolticute#859]
### Expected behavior

Export data from Mooltipass mini.
Import data in Mooltipass mini BLE.

### Actual behavior

Import fails because user is not the same.
But cards from mini cannot be used in miniBLE.
I don't know if some documentation exists :/

### Step by step guide to reproduce the problem

1. Export data from mini and disconnect it
2. Connect mini BLE and try to import data
3. An error message says that you cannot import data from another user

### Moolticute Version

0.46.3

### Operating System
Mention if you are using either:
- Debian testing

### Mooltipass Device

- The Mooltipass Mini
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
Hello!

Please check IV.Importing Existing Profiles IntoNew Mooltipass Devices of our user manual here: https://raw.githubusercontent.com/mooltipass/minible/master/MooltipassMiniBLEUserManual.pdf

thanks!
