### ISSUE TITLE
updating duplicate credentials = fail 

### ISSUE THREAD

**Issue by limpkin** [mooltipass/moolticute#866]
from a backer: 

When in credential management via the Moolticute App [pc]
-I had wanted to re-order a few credentials for one particular domain;
-I removed the credential entry with the apps' delete function and then proceeded
to re-enter the same credential in hopes of the items being listed in a slightly
different order.
-This was fine until exiting credential management and the app sending/syncing details back to the
mooltipass whereby I would normally encounter a request for the credentials to be approved on the
device as any new credentials/domains were detected
-However, the result was the detection of the duplicate credential (not yet deleted on the mooltipass device)
and the program halting with an error and nothing being updated to the device.

As I suspected the source of the error, I was able to manually delete the credential in question THEN exit,
allowing everything to be updated on the device THEN re-entering credential management to enter the new credential

**Comment by kbembedded** [comment]
Duplicate of #706 ?

**Comment by limpkin** [comment]
agreed
