### ISSUE TITLE
Crash on credentials editing

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#867]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Trying to edit the site/service name should not crash.

### Actual behavior
It does crash

### Step by step guide to reproduce the problem

Connect a BLE to moolticute (I did so on Mac)
Enter credentials management mode
Try to edit a service name (I tried removing a http:// from http://xxx.xxx.xxx.xxx/admin)
Hit apply changes
Crash

### Moolticute Version
0.46.3

### Operating System
Mention if you are using either:
- MacOS  

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
@KDederichs does this still happen on 50.0?

**Comment by KDederichs** [comment]
Looks like that's fixed in 0.50 👍
