### ISSUE TITLE
Moolticute stopped responding "forever"

### ISSUE THREAD

**Issue by roolo** [mooltipass/moolticute#869]
### Expected behavior

Application should just start and work.

### Actual behavior

When I try to start the application, it just sits there in the Dock and doesn't respond to secondary click nor app switch. The only way to quit the app is to Force quit it from the Activity monitor.

Logs seems to be ok (barath on IRC helped me to gather them) — https://gitlab.com/-/snippets/2139053

 I've tried
- to disconnect my mini BLE
- delete preferences file
- delete support files

I've tried to to start Moolticute after each of the steps.

### Step by step guide to reproduce the problem

I think last thing I wanted to do was to edit this password `X2HUrCrg9kAa42T27dByU6zcb34-PQ` (not used anywhere anymore). Strange thing is, when my mini BLE types it, it comes out like this `X2HUrCrg9kAa42T27dByU6zcb34- PQ`

Not sure if it connected, but app did not respond well to my system's dark more (white text on white background).

### Moolticute Version

- v0.46.3

### Operating System

- MacOS  

### Mooltipass Device

- The Mooltipass Mini BLE

**Comment by roolo** [comment]
Restarting computer did solve my issue 😒

**Comment by roolo** [comment]
After hour or so it is happening again. With the difference that now it won't even show up in the Dock.

**Comment by limpkin** [comment]
could you try our latest build and get back to us?
https://github.com/mooltipass/moolticute/releases/tag/v0.50.0

**Comment by roolo** [comment]
I am using v0.5.0 for a few days and it seems it stopped.
