### ISSUE TITLE
Make Multicute compatible with dark mode

### ISSUE THREAD

**Issue by Yzord** [mooltipass/moolticute#870]
------------------------ FEATURE REQUEST ------------------------------------
### Missing feature

Multicute is not really compatible with dark mode on macOS

### Justification

The fields where you can type your stuff are black as also the font is black. You can't see what you type into it

### Workarounds

Yeah, go into light mode, but i don't want that, because i want dark mode :)

------------------------ END FEATURE REQUEST --------------------------------

**Comment by LukeyBrown** [comment]
Had the same issue, screenshot attached[](url)
![Screen Shot 2021-06-28 at 7 52 37 pm](https://user-images.githubusercontent.com/32407563/123717795-f3c49800-d8c0-11eb-86c1-0fe208fabc4f.png)

**Comment by limpkin** [comment]
@Yzord @LukeyBrown i've just released v0.50.0, could you test it and get back to me?
https://github.com/mooltipass/moolticute/releases/tag/v0.50.0

**Comment by Yzord** [comment]
That looks way better, thank you
