### ISSUE TITLE
Mooticute Internal Error (SMMC#2) - Mooltipass BLE

### ISSUE THREAD

**Issue by phantompants** [mooltipass/moolticute#875]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Import CSV file that was created in 1Password 

### Actual behavior
Moolticute displays spinning wheel, Shows words 'Importing and Merging File to Device' and 'Please wait.' and bar at 100% with 'Favorite are loaded' in italics. I am in the advanced menu.

This is the first time I am using the device.

### Step by step guide to reproduce the problem
I get the export from 1Password, delete out the extra columns and extra long usernames. I have 646 usernames/passwords to import, but every time I get the SMMC#2 error.

### Moolticute Version
v0.46.3

### Operating System
Mention if you are using either:
- Windows 10

### Mooltipass Device
- The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
This was fixed but not released in our main channel.
Could you install the beta moolticute here? https://betas.themooltipass.com/
