### ISSUE TITLE
Password generator in Moolticute

### ISSUE THREAD

**Issue by Yzord** [mooltipass/moolticute#878]
------------------------ FEATURE REQUEST ------------------------------------
### Missing feature

Password generator in Moolticute

### Justification

Would love to have the ability to create passwords when i need one with this tool. Lastpass offers this in theirs and i used it very often.

------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello!

Do you mean this one?

![image](https://user-images.githubusercontent.com/6170291/124071356-7c694280-da3f-11eb-9859-6d77dfc5bb58.png)

**Comment by Yzord** [comment]
Hmm yes, that is the one. Didn't know it was there already, sorry.
