### ISSUE TITLE
[OSX] Application/Daemon randomly freezes

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#883]
### Expected behavior
Moolticute starts and runs propperly till the time you close it or shut down the device.

### Actual behavior
As per our email conversation I'll open a new ticket:

My Moolticute regularly and as far as I can tell randomly does freeze and/or doesn't connect to the daemon making it really difficult to use the device.
Once the application freezes only a complete system reboot can fix it (terminating the process does not work, it just won't start again).
There's no firewall or antivirus that might interfer with the application.
That issue has been around for many versions of Moolticute for me so it's not something recent.

### Step by step guide to reproduce the problem

Unknown it just stops working during normal use of the Mac

### Moolticute Version
0.40 to 0.46.3 (didn't happen with 0.5 yet I'll update this if it does)

### Operating System
Mention if you are using either:
- MacOS  11.4 (iMac 27" 2019, i-9, 64GB Ram, eGPU Razer Core X with Radeon RX 580)
  
### Mooltipass Device
- The Mooltipass Mini
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
is this still happening on the latest MC on OSX?

**Comment by KDederichs** [comment]
yeah the UI still randomly stopps responding and gives me the mouse Spinner (I usually notice it when I wanna shut down the system then Moolticute keeps blocking it and I have to force quit)

**Comment by limpkin** [comment]
could you have the logs window opened so when it freezes you can let us know what it was doing?

**Comment by KDederichs** [comment]
Will do I'll try to keep it open and see what it says (might take a while since those crashes don't always happen)

**Comment by KDederichs** [comment]
![Screenshot 2021-09-05 at 20 44 45](https://user-images.githubusercontent.com/24696606/132137973-39f2df0f-f3cf-4033-b8c7-bf330124dfe7.png)

Here you go, I do not know when it froze, since the log window is also non responsive, but when we assume it updated before that's the last entry.

**Comment by KDederichs** [comment]
I also just noticed that if you move the mouse over the icon in the menu bar (at the top) it'll also turn into the spinning wheel, only for the Moolticute one though.

**Comment by KDederichs** [comment]
![Screenshot 2021-09-07 at 19 00 52](https://user-images.githubusercontent.com/24696606/132383365-a030d61d-4339-48ac-b8eb-a51c9786026b.png)
Here's another freeze

**Comment by KDederichs** [comment]
Oh and one interesting fact about this:
If you force quit the app and the daemon the daeomon absolutely refuses to start up again.
I literally can not get it to start again till the whole system reboots.

**Comment by KDederichs** [comment]
Ok it gave me a crash log this time, I did upload it to pastebin cause it's MASSIVE
https://pastebin.com/5K09ZL7S

@limpkin

**Comment by limpkin** [comment]
@KDederichs is this still hapening?

**Comment by KDederichs** [comment]
Honestly?
I've stopped using it cause there were so many little things that are just inconvenient in daily live.

I'll give it a try again later and tell you if it's still doing that.

**Comment by limpkin** [comment]
Thanks for your time @KDederichs . I'd like to get to the bottom of this as no one else reported this to us :/

**Comment by KDederichs** [comment]
yeah it's a strange issue for sure...
I'd also love to know what causes it cause that's one of the main reasons I stopped using it tbh.
Cause I really like the hardware and the idea but it's no fun if the software is 'fighting' you daily.

It's also annoying that literally ALL of it freezes including the log window so I'm not even sure if the cause actually gets logged or is lost.

I wonder if it's some kind of software incompatibility or something but I don't know what I'd have installed what might cause this.

**Comment by KDederichs** [comment]
Just asking just to be sure but could it be related to connected screens?
I do have an eGPU connected with like 4 screens attatched to that and the moolticute logo in the task bar at the top always gets 'squished' when clicking on other screens

**Comment by limpkin** [comment]
@KDederichs is this still happening?

**Comment by KDederichs** [comment]
@limpkin yup, installed today still doing that. as usual nothing unusual in logs
![Screenshot 2022-01-29 at 23 49 16](https://user-images.githubusercontent.com/24696606/151680067-d708bf4b-44d1-4c66-8ec7-f004be37e859.png)
that's the last one it got before freezing I think since the log freezes with it.

**Comment by KDederichs** [comment]
Here's a crash log again https://pastebin.com/F0v7BuxC (massive)

**Comment by KDederichs** [comment]
It just did that during an integrity check btw... Can I just... unplug the mooltipass or do I have a problem now @limpkin ?

**Comment by limpkin** [comment]
you can unplug :)

**Comment by limpkin** [comment]
Hello there! 
We've just released our latest moolticute beta for macOS, compiled with the QT6 framework (it took us a while...). Would you be able to download and install it at https://betas.themooltipass.com/v0.55.10-testing/Moolticute-v0.55.10-testing.dmg and let us know if you still experience this issue?

**Comment by KDederichs** [comment]
I'll let it run for a while and see if it starts hanging again. Might take a while cause it's not really fixed when it happens but I'll get back to you :)

**Comment by limpkin** [comment]
i think i'll close it, feel free to reopen it if it happens again :)

**Comment by KDederichs** [comment]
Yeah I think the QT6 rework actually fixed it (so it was probably a QT thing in the first place) cause since then it's been running well :)
