### ISSUE TITLE
miniBLE can't export file(or enter file managment menu)[solved]

### ISSUE THREAD

**Issue by p3t33** [mooltipass/moolticute#888]
### Expected behavior
Scenarios:
1. When exporting files via the Moolticute "Quick File Access" file should be exported.
2. When entering the "Files Management Mode" via Moolticute list of files should be displayed.

### Actual behavior
Scenarios:
1. The miniBLE will reboot and the Moolticute will get stuck waiting for miniBLE to export the file.
2. After approving on the miniBLE the Moolticute will start loading the files and get stuck on the file causing the issue.

### Step by step guide to reproduce the problem
I start with a clean restart of the OS(Windows/Linux)

**Scenarios 1**
1. miniBLE is connected via USB(no Bluetooth is active).
2. Using the Moolticute "FIles" tab I access the "Quick File Access" and press the export icon next to the file I wan't to export to my machine,
3. The Moolticute will get stuck on the "waiting for approval on the device" while the miniBLE will reboot itself.

**Scenarios 2**
1. miniBLE is connected via USB(no Bluetooth is active).
2. Using the Moolticute "FIles" tab I press the "Files Management Mode"
3. The Moolticute will start loading the files on the device and then get stuck indefinitely on the file that caused the miniBLE to crash and reboot in scenario 1. In This case, miniBLE **won't** crash and reboot.

The worst thing with this situation is that I can't even delete the file causing the issue because this is done via the "Files Management Mode" which I am unable to access anymore.

### More background
- I don't have this issue with all of the files.
- The file I am having an issue with is smaller than the files that I do not.
- When importing the database from the mini(that had files) to the miniBLE,  files weren't exported with the reset of the database and I had to add them once more

### Moolticute Version
v0.45.2 and v0.50.0(on linux) and v0.50.0(on windows)

### Operating System
Was able to reproduce on Windows 10 and Ubuntu 20.04

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
please re-open a new issue with the "Step by step guide to reproduce the problem" completed
There are critical elements we need to know to debug this issue:
- is it connected through bluetooth or USB?
- when will it reboot?

**Comment by p3t33** [comment]
Hi, limpkin,
I have updated the issue with the "Step by step guide to reproduce the problem"

Update

I tried to overwrite the file that was causing all the issues(by saving another file with the same name) and now
- I no longer have any files at the Moolticute "Quick File Access"
- I am no longer able to add new files using Moolticute(Files Tab - "save" button"
- I have no access to the "Files Management Mode"

**Comment by limpkin** [comment]
Hi,

It seems your database has been corrupted somehow :/. Do you have a database backup somewhere?
FYI we're currently working on re-adding the "fix database" feature on moolticute

**Comment by p3t33** [comment]
I do Have a backup(a few of them) , the question is when did it happen, and is it related to transferring a database from mini to the miniBLE because as I already mentioned when doing the transfer there were no files on the miniBLE.which looked strange to me at the time.

**Comment by limpkin** [comment]
Hmmm file transfer from mini to mini ble requires an updated moolticute (v0.50.0)

**Comment by p3t33** [comment]
limpkin,  I am not sure that I had the latest version of moolticute , when doing the transfer from mini to mini ble but I will check it out later today.

**Update**
I was able to solve it by restoring from a backup. Not sure what caused the database corruption in the first place.

**Comment by p3t33** [comment]
update 2:
I did try to import my mini backup using moolticute (v0.50.0) and this time I did get the files that were stored on the mini to show up on the miniBLE .

*I did get a few messages(**during the import**) saying my device database is older than the backup file. And even got the miniBLE to reboot once.
This did not happen when working with a database file that was created using the miniBLE and importing it to another miniBLE

**Comment by limpkin** [comment]
could you let me know how it restarted? this is fairly worrying....

**Comment by p3t33** [comment]
> could you let me know how it restarted? this is fairly worrying....
It would be hard to reproduce. The miniBLE just froze for a few seconds while the GUI was showing progress and the miniBLE screen gone dark and then the device rebooted.

After the reboot, the GUI was stuck on the "importing" while the device had the database(I wasn't able to determine if all the database was imported and if it was usable).
