### ISSUE TITLE
Feature request: Saving an displaying entries for non computer secrets (f.e. door access or credit card PINs)

### ISSUE THREAD

**Issue by bmueller77** [mooltipass/moolticute#894]
### Missing feature
Save PINs for etc. door-/safe-access or even to write down credit/debit card PINS or software license data and allow displaying them on the device

### Justification
This feature would make the Mooltipass to the only hardware password/secret-manager you'll ever need.

### Workarounds
No workarounds

**Comment by limpkin** [comment]
I'm confused... why not not make a "fake" credential with that data? :)

**Comment by Hypoon** [comment]
I'm confused too, I already do that on my mooltipass.

Perhaps the user wants to be able to create new credentials on the device. Is there a way to do that yet?

It might also be useful to have an option for certain credentials to skip the usb/bluetooth prompts and directly display it on the screen.

**Comment by limpkin** [comment]
we don't, mostly because the user experience wouldn't be optimal...
