### ISSUE TITLE
Firmware bundle update 0 to 4 upload finished with an error

### ISSUE THREAD

**Issue by 0xa000** [mooltipass/moolticute#933]
### Expected behavior
Bundle update completes without an error.

### Actual behavior
Bundle update fails with an error.

### Step by step guide to reproduce the problem

* Download bundle via: https://www.themooltipass.com/updates/index.php?sn=XXX&bundlev=0
* Follow instructions in https://mooltipass.github.io/minible/updating_your_device
* Observe error message dialog.

### Moolticute Version
0.52.0-1 (Arch Linux AUR package https://aur.archlinux.org/moolticute.git)

### Operating System
Arch Linux

### Mooltipass Extension
Version 1.10.0 on Firefox.

### Mooltipass Device
Mooltipass Mini BLE

**Comment by limpkin** [comment]
Hello!
Did you correctly insert the card the wrong way around?
Thanks!

**Comment by 0xa000** [comment]
Yes, I think so. I took out the card, flipped it over so the chip pointed up (towards the ceiling), and re-inserted it. The mooltipass first displays "Invalid Card Inserted", then "Please Remove The Card".

**Comment by 0xa000** [comment]
The error about the upload shows almost instantaneously. So I think the update has not actually begun, it seems to fail before that. 

For the password, I copied pasted the hex string at the end of the filename. This is a 32 character lower-case hexadecimal string. The update guide mentions an example filename "update_xxxx_from_bundle_a_to_b_yyyyyyyyyyy.img", where the suffix is only 11 characters long. I assume that should not be taken literally?

**Comment by limpkin** [comment]
That's correct.
Can you send me a private message at support at themooltipass dot com so i can double check the password that you used?
