### ISSUE TITLE
Option to export credentials in plain-text (CSV or XML)

### ISSUE THREAD

**Issue by Jan-NiklasB** [mooltipass/moolticute#938]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
An Option to export the saved credentials in plain text (CSV or XML)
### Justification
I'm missing a way to export the plain safed data for reimport in other software or storing it as printed version in a safe place (safe / vault or safe desposit box).

### Workarounds
Only creating a file and manually copy/paste all credentials or let the MP print the, but that doesn't include FIDO2 or TOTP data.

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
Hello!
This effectively would break our security model and would render the Mini BLE fairly "useless" as your overall security level would be the same as your computer's. Hence, the Mini BLE firmware was coded to prevent an unencrypted export of its database. 
Therefore, the only way to export all your credentials would be to approve prompts on the device for each credential export... which would be come fairly annoying very quickly.
That being said we do have coded a python script, which together with your smartcard and encrypted database export allows decryption of the latter.

**Comment by Jan-NiklasB** [comment]
Hey, thanks for the quick response.
That is in fact what I wanted, the way (if direct export or a way to decrypt the exported file) doesn't matter for me.
Maybe you should include this in the manual or somewhere else where it's simple to find.

BTW where can I find the script? :D

**Comment by limpkin** [comment]
sorry for the delayed answer.
Script can be found here: https://github.com/mooltipass/minible/tree/master/scripts/smc_decode
