### ISSUE TITLE
Installation on Debian Unstable fails

### ISSUE THREAD

**Issue by new-gen23** [mooltipass/moolticute#941]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

### Expected behavior
add-apt-repository ppa:mooltipass/moolticute 
-> should add  the pgp key to allow importing the repo

### Actual behavior
Something is wrong with the GPG key and the apt-get update cannot download the file.

### Step by step guide to reproduce the problem

add-apt-repository ppa:mooltipass/moolticute

 Packages for Moolticute.
This project aims to be an easy companion to your Mooltipass device and extend the power of the device to more platform/tools. With it you can manage your Mooltipass with a cross platform app, as well as provide a daemon service that handle all USB communication with the device.

For questions and bugs please contact https://github.com/mooltipass/moolticute/issues/new
 More info: https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: Die "Keybox" `/tmp/tmp4eqc_fvt/pubring.gpg' wurde erstellt
gpg: /tmp/tmp4eqc_fvt/trustdb.gpg: trust-db erzeugt
gpg: Schlüssel D30397520E0A5FDD: Öffentlicher Schlüssel "Launchpad PPA for Mooltipass Team" importiert
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 1
gpg:                              importiert: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: Keine gültigen OpenPGP-Daten gefunden.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.9/shutil.py", line 727, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 684, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 682, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'S.gpg-agent.extra'
root@home:/home/dmarner# apt-get update
                                                                                     
Fehl:10 http://ppa.launchpad.net/ansible/ansible/ubuntu jammy Release                                                                       
  404  Not Found [IP: 91.189.95.85 80]
Fehl:11 http://ppa.launchpad.net/mooltipass/moolticute/ubuntu jammy Release                                  
  404  Not Found [IP: 91.189.95.85 80]

### Operating System
Mention if you are using either:
- Debian unstable
  

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini

**Comment by limpkin** [comment]
@raoulh please correct me but this doesn't look like on our end, right?

**Comment by raoulh** [comment]
Nope does not seem so.

This should do the trick:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 05452CC8203FE171D20B4F91D30397520E0A5FDD
sudo apt update
```

**Comment by new-gen23** [comment]
Well, helps partially, now I get:  
Das Depot »http://ppa.launchpad.net/mooltipass/moolticute/ubuntu jammy Release« enthält keine Release-Datei.
Which translates to :
The Repo http://ppa.launchpad.net/mooltipass/moolticute/ubuntu jammy Release has no Release-File.

I think I spelled the wrong system os. Ubuntu Jammy seems not supported (yet).

**Comment by limpkin** [comment]
oh, let me take care of that :)

**Comment by limpkin** [comment]
jammy just built for :)
