### ISSUE TITLE
Notes order is not consistent

### ISSUE THREAD

**Issue by gmarcusm** [mooltipass/moolticute#947]
### Expected behavior

The order of the notes Tab seems to be alphabetic. So the notes should be always in alphabetic order. When adding a new note, the notes should be resorted.

### Actual behavior

When a new note is created, it is added at the end. 

### Step by step guide to reproduce the problem

1. Ensure you have a few notes already.
2. Disconnect and connect the device again.
3. Create a new note, with a title that should be sorted somewhere in the middle of the alphabetic listing.
4. Watch the note being added at the end.

### Moolticute Version

0.53.7

### Operating System
- MacOS  

### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
implemented :)
