### ISSUE TITLE
Lowest Priority:  Both of Moolticute's "About" Tab Hyperlinks are the same URL

### ISSUE THREAD

**Issue by CubeCentral** [mooltipass/moolticute#951]
8<------------------------ BUG REPORT -----------------------------------------

![Drawing1 - Copy](https://user-images.githubusercontent.com/37314108/146425748-368af680-b1cc-49e4-8f98-486dc53b757c.png)

### Expected behavior
Expected that the two hyperlinks on the Moolticute "About" page to go to different resources, such as bringing up the User Manual.

### Actual behavior
The two hyperlinks on the Moolticute "About" page have the same destination.

### Step by step guide to reproduce the problem
1. Open Moolticute
2. Select the "About" tab
3. Click on the first hyperlink that shows a website address, "[https://github.com/mooltipass/moolticute](https://github.com/mooltipass/moolticute)", which opens the same.
4. Return to the "About" tab in the Moolticute App.
5. Click on the second hyperlink that is titled "User Manual"
6. Notice that you are directed to the same location as above.

### Moolticute Version
v0.53.7

### Operating System
Windows 10

### Mooltipass Device
The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
that's odd.. both links work for me and lead to the right place

**Comment by CubeCentral** [comment]
**sigh**  REALLY?  It is working for me now, but for sure was not bringing up a PDF.

Honestly, really, I am not a novice and have been filling out bag reports before a large percentage of you all were born!
I will redouble my efforts to be SURE that there is an issue.  I'm not old enough to be senile ... I don't think.  
Anyways, my apologies for the report and hope it didn't cause anyone (Mathieu) any trouble.

**Comment by limpkin** [comment]
;) no worries
