### ISSUE TITLE
Moolticute and moolticuted terminate after exporting database

### ISSUE THREAD

**Issue by talmage** [mooltipass/moolticute#955]
### Expected behavior

When the "Export Database to File" action is finished, moolticute and moolticuted continue to run.

### Actual behavior

When the "Export Database to File" action is finished, moolticute and moolticuted terminate.

The two programs exit whether you click OK or Cancel in the file selection dialog box.

### Step by step guide to reproduce the problem

1. Select the Synchronization tab in moolticute
2. Select Export to File
3. Approve the Database Management request
4. Enter your PIN
5. Select or type a file name in the file selection dialog box
6. Click "OK" or "Cancel"

### Moolticute Version

Built from source from the git repository.  Commit b5683ba85525b81f10b5b6f98bffe89851b61292

### Operating System
Mention if you are using either:
- Pop! OS 21.04

  
Other operating systems are not supported.

### Mooltipass Device
Mooltipass Mini BLE

**Comment by limpkin** [comment]
If I remember correctly, can you launch the daemon through the command line to get the logs and the reason of the crash? thanks :)

**Comment by talmage** [comment]
Here is the log file.  I started moolticuted from the command line and it stayed up after moolticute closed.

[moolticuted.log](https://github.com/mooltipass/moolticute/files/7777555/moolticuted.log)

**Comment by limpkin** [comment]
@0x0ptr : looks like the GUI gave up on life without leaving any trace :/, how can we debug this?

**Comment by talmage** [comment]
On 28.12.2021 13:51, Mathieu wrote:
> @0x0ptr : looks like the GUI gave up on life without leaving any trace
> :/, how can we debug this?

I can run the non-stripped GUI under gdb.
I'll rebuild it with debugging symbols if necessary.

**Comment by limpkin** [comment]
oh that would be great! thanks

**Comment by limpkin** [comment]
hello @talmage ! did you manage to debug this issue? :)

**Comment by talmage** [comment]
I ran the gui under gdb.  It crashed as expected but the stack dump wasn't helpful.  I built it from the master branch, commit b5683ba85525b81f10b5b6f98bffe89851b61292.  The gui still closes after I type the name of the export file and press "OK".

**Comment by talmage** [comment]
I don't have a lot of time to debug this.  I'm sorry.

**Comment by limpkin** [comment]
can you try using qt6 to build the repo instead?

**Comment by talmage** [comment]
I can do that.  I think I can find time to do it this week.

**Comment by talmage** [comment]
It took a while, but I found time to build moolticute again.  This time, I used QtCreator instead of the instructions in README.md:

`mkdir build
cd build
qmake ../Moolticute.pro
make
`

I used Qt5 instead of Qt6 as @limpkin suggested because I couldn't figure out how to specify C++17, which Qt6 requires.

I haven't been able to reproduce the problem with moolticute I built with QtCreator.

I can still reproduce the problem with moolticute I build using qmake and cmake.

Among the differences is the version of Qt.  When I build on the command line, I get Qt 5.15.2.  When I build with QtCreator, I get Qt 5.12.6.

**Comment by talmage** [comment]
I was able to build moolticute with QtCreator and Qt 5.15.2.  I can reproduce the bug with this build.  There must be something wrong with Qt 5.15.2.

**Comment by limpkin** [comment]
@talmage is this still happening with the latest build?

**Comment by talmage** [comment]
No, it's not happening any more
