### ISSUE TITLE
Missing Ubuntu Impish Release File

### ISSUE THREAD

**Issue by chellinsky** [mooltipass/moolticute#956]
When trying to install Moolticute using both the release and beta PPAs, the following error occurs during apt-get update:

> Err:6 http://ppa.launchpad.net/mooltipass/moolticute-beta/ubuntu impish Release
>   404  Not Found [IP: 91.189.95.85 80]
> ...
> E: The repository 'http://ppa.launchpad.net/mooltipass/moolticute-beta/ubuntu impish Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

I am running Ubuntu 21.10.  Let me know if you need additional information.

**Comment by limpkin** [comment]
Wow, somehow we hadn't updated our release list....
I therefore just released a "testing" version on https://launchpad.net/~mooltipass/+archive/ubuntu/moolticute-beta , will publish a release version soon :)
