### ISSUE TITLE
Error Updating Credentials on Mooltipass via Moolticute

### ISSUE THREAD

**Issue by stonemirror** [mooltipass/moolticute#957]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Added some credentials via Moolticute, and attempted to update the database.

### Actual behavior
Moolticute reported a failure and advised me to send you a copy of the daemon log.

### Moolticute Version
v0.5.3.7

### Operating System
- MacOS  v10.15.7
  
### Mooltipass Device
Mention if you are using either:
- The Mooltipass Mini BLE

Here's the daemon log:

INFO: (2021-12-28T08:20:09.346) :0 - ------------------------------------
INFO: (2021-12-28T08:20:09.348) :0 - Moolticute Gui version:  v0.53.7
INFO: (2021-12-28T08:20:09.348) :0 - (c) The Mooltipass Team
INFO: (2021-12-28T08:20:09.348) :0 - https://github.com/mooltipass/moolticute
INFO: (2021-12-28T08:20:09.348) :0 - ------------------------------------
INFO: (2021-12-28T08:20:09.351) :0 - Trying to set language:  ":/lang/mc_en.qm"
WARNING: (2021-12-28T08:20:09.763) :0 - Error receiving trust for a CA certificate
WARNING: (2021-12-28T08:20:11.077) :0 - QLayout: Attempting to add QLayout "" to TutorialWidget "", which already has a layout
WARNING: (2021-12-28T08:20:11.379) :0 - Failed to hide dock icon: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list"
INFO: (2021-12-28T08:20:11.379) :0 - Running  "/Applications/Moolticute.app/Contents/MacOS/moolticuted"   ()
INFO: (2021-12-28T08:20:12.475) :0 - Daemon started
INFO: (2021-12-28T08:20:11.662) :0 - ------------------------------------
INFO: (2021-12-28T08:20:11.662) :0 - Moolticute Daemon version:  v0.53.7
INFO: (2021-12-28T08:20:11.662) :0 - (c) The Mooltipass Team
INFO: (2021-12-28T08:20:11.662) :0 - https://github.com/mooltipass/moolticute
INFO: (2021-12-28T08:20:11.662) :0 - ------------------------------------
DEBUG: (2021-12-28T08:20:11.672) :0 - Moolticute daemon websocket server listening on port  30035
INFO: (2021-12-28T08:20:12.174) :0 - Starting MPManager
DEBUG: (2021-12-28T08:20:12.207) :0 - BT connection
DEBUG: (2021-12-28T08:20:12.532) :0 - QWebSocket origin header:  ""
DEBUG: (2021-12-28T08:20:12.532) :0 - QWebSocket origin header: Accepted
WARNING: (2021-12-28T08:20:12.617) :0 - Error receiving trust for a CA certificate
DEBUG: (2021-12-28T08:20:13.041) :0 - New connection
DEBUG: (2021-12-28T08:20:13.046) :0 - Mooltipass Mini BLE is connected
INFO: (2021-12-28T08:20:13.047) :0 - "Waiting job"
DEBUG: (2021-12-28T08:20:13.054) :0 - Mooltipass connected
DEBUG: (2021-12-28T08:20:13.055) :0 - Device added:  "140375282066768"
DEBUG: (2021-12-28T08:20:13.057) :0 - JSON API recv: {
    "msg": "get_random_numbers"
}

DEBUG: (2021-12-28T08:20:13.057) :0 - JSON API recv: {
    "msg": "list_files_cache"
}

DEBUG: (2021-12-28T08:20:13.058) :0 - It's an unknown smartcard or it's locked, no need to search for files cache
DEBUG: (2021-12-28T08:20:13.234) :0 - JSON API recv: {
    "data": {
        "only_check": false
    },
    "msg": "request_keyboard_layout"
}

DEBUG: (2021-12-28T08:20:13.236) :0 - JSON API recv: {
    "msg": "inform_unlocked"
}

DEBUG: (2021-12-28T08:20:13.236) :0 - JSON API recv: {
    "msg": "get_user_settings"
}

DEBUG: (2021-12-28T08:20:13.238) :0 - JSON API recv: {
    "msg": "get_battery"
}

DEBUG: (2021-12-28T08:20:13.239) :0 - JSON API recv: {
    "msg": "fetch_notes"
}

DEBUG: (2021-12-28T08:20:13.239) :0 - JSON API recv: {
    "data": {
        "only_check": true
    },
    "msg": "request_keyboard_layout"
}

INFO: (2021-12-28T08:20:14.013) :0 - "Inform device about computer unlocked"
INFO: (2021-12-28T08:20:14.539) :0 - "Getting initial status"
DEBUG: (2021-12-28T08:20:14.604) :0 - Battery percent:  70
DEBUG: (2021-12-28T08:20:14.604) :0 - received MPCmd::MOOLTIPASS_STATUS:  1
DEBUG: (2021-12-28T08:20:14.604) :0 - Update client status changed:  WSServerCon(0x7fabaaa47810)
INFO: (2021-12-28T08:20:14.605) :0 - "Get PlatInfo"
INFO: (2021-12-28T08:20:14.661) :0 - "Exiting MMM"
CRITICAL: (2021-12-28T08:20:14.717) :0 - Failed to exit MMM
INFO: (2021-12-28T08:20:14.718) :0 - "Get random numbers from device"
INFO: (2021-12-28T08:20:14.795) :0 - Random numbers generated ok
INFO: (2021-12-28T08:20:14.795) :0 - "Read languages"
DEBUG: (2021-12-28T08:20:14.874) :0 - Language number:  12
DEBUG: (2021-12-28T08:20:14.930) :0 - Keyboard layout number:  53
WARNING: (2021-12-28T08:20:17.606) :0 - Failed to hide dock icon: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list"
DEBUG: (2021-12-28T08:20:17.696) :0 - QWebSocket origin header:  "chrome-extension://ffemldjbbfhimggdkkckolidemlllklk"
DEBUG: (2021-12-28T08:20:17.696) :0 - QWebSocket origin header:  Accepted
DEBUG: (2021-12-28T08:20:17.697) :0 - Send card db metadata
DEBUG: (2021-12-28T08:20:17.697) :0 - There is no card data to be send.
DEBUG: (2021-12-28T08:20:17.698) :0 - New connection
DEBUG: (2021-12-28T08:20:17.712) :0 - JSON API recv: {"msg":"get_application_id"}
INFO: (2021-12-28T08:20:19.790) :0 - "Read languages"
DEBUG: (2021-12-28T08:20:19.870) :0 - Language number:  12
DEBUG: (2021-12-28T08:20:19.870) :0 - No need to fetch languages, it is already up-to-date.
DEBUG: (2021-12-28T08:20:19.915) :0 - Keyboard layout number:  53
DEBUG: (2021-12-28T08:20:19.915) :0 - No need to fetch layouts, it is already up-to-date.
INFO: (2021-12-28T08:20:19.915) :0 - "Loading device parameters"
DEBUG: (2021-12-28T08:20:19.971) :0 - Full device settings payload:  "00000f0100090a0f0190010900000000000000000000001e00000100000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:20:20.016) :0 - User language:  0
DEBUG: (2021-12-28T08:20:20.071) :0 - Device language:  0
DEBUG: (2021-12-28T08:20:20.206) :0 - Keyboard USB layout:  0
DEBUG: (2021-12-28T08:20:20.328) :0 - Keyboard Bluetooth layout:  0
INFO: (2021-12-28T08:20:20.330) :0 - "Send date to device"
DEBUG: (2021-12-28T08:20:20.330) :0 - Sending current date:  "e5070c001c00100014001400"
INFO: (2021-12-28T08:20:20.465) :0 - Date set success
INFO: (2021-12-28T08:20:25.669) :0 - Checking software updates from  "https://api.github.com/repos/mooltipass/moolticute/releases"
WARNING: (2021-12-28T08:20:26.251) :0 - Failed to hide dock icon: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list"
DEBUG: (2021-12-28T08:20:58.691) :0 - Received status:  "0900110005000546ffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:20:58.692) :0 - Battery percent:  70
DEBUG: (2021-12-28T08:20:58.692) :0 - received MPCmd::MOOLTIPASS_STATUS:  5
DEBUG: (2021-12-28T08:20:58.692) :0 - Update client status changed:  WSServerCon(0x7fabaaa47810)
DEBUG: (2021-12-28T08:20:58.692) :0 - Update client status changed:  WSServerCon(0x7fabaa868110)
INFO: (2021-12-28T08:20:58.692) :0 - "Fetch data files"
DEBUG: (2021-12-28T08:20:58.707) :0 - JSON API recv: {
    "msg": "get_user_categories"
}

DEBUG: (2021-12-28T08:20:58.708) :0 - JSON API recv: {
    "msg": "load_params"
}

DEBUG: (2021-12-28T08:20:58.724) :0 - Sending files cache
DEBUG: (2021-12-28T08:20:58.725) :0 - Sending files cache
INFO: (2021-12-28T08:20:58.725) :0 - "Fetch notes"
INFO: (2021-12-28T08:20:58.743) :0 - Requesting change numbers
DEBUG: (2021-12-28T08:20:58.758) :0 - Sending notes
DEBUG: (2021-12-28T08:20:58.758) :0 - Sending notes
INFO: (2021-12-28T08:20:58.758) :0 - "Get User Categories"
DEBUG: (2021-12-28T08:20:58.835) :0 - User categories got successfully
INFO: (2021-12-28T08:20:58.835) :0 - "Loading device parameters"
DEBUG: (2021-12-28T08:20:58.882) :0 - Full device settings payload:  "00000f0100090a0f0190010900000000000000000000001e00000100000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:20:58.916) :0 - User language:  0
DEBUG: (2021-12-28T08:20:58.961) :0 - Device language:  0
DEBUG: (2021-12-28T08:20:58.994) :0 - Keyboard USB layout:  25
DEBUG: (2021-12-28T08:20:59.028) :0 - Keyboard Bluetooth layout:  25
INFO: (2021-12-28T08:20:59.028) :0 - "Loading device card CPZ"
DEBUG: (2021-12-28T08:20:59.062) :0 - Card CPZ:  "eafcd5fe00334733"
INFO: (2021-12-28T08:20:59.063) :0 - Finished loading card CPZ
INFO: (2021-12-28T08:20:59.063) :0 - "Loading device db change numbers"
DEBUG: (2021-12-28T08:20:59.096) :0 - dbChangeNumber set to file cache, emitting file cache changed
DEBUG: (2021-12-28T08:20:59.096) :0 - Send card db metadata
DEBUG: (2021-12-28T08:20:59.096) :0 - Sended card db metadata
DEBUG: (2021-12-28T08:20:59.096) :0 - Send card db metadata
DEBUG: (2021-12-28T08:20:59.096) :0 - Sended card db metadata
DEBUG: (2021-12-28T08:20:59.096) :0 - Credentials change number: 0
DEBUG: (2021-12-28T08:20:59.096) :0 - Data change number: 0
INFO: (2021-12-28T08:20:59.097) :0 - Finished loading change numbers
INFO: (2021-12-28T08:20:59.097) :0 - "Fetch data files"
DEBUG: (2021-12-28T08:20:59.129) :0 - Sending files cache
DEBUG: (2021-12-28T08:20:59.129) :0 - Sending files cache
DEBUG: (2021-12-28T08:21:06.996) :0 - JSON API recv: {
    "data": {
        "want_data": false,
        "want_fido": false
    },
    "msg": "start_memorymgmt"
}

INFO: (2021-12-28T08:21:06.997) :0 - "Starting MMM mode"
DEBUG: (2021-12-28T08:21:07.151) :0 - "PLEASE_RETRY (0x0002)"  received, resending command  "START_MEMORYMGMT (0x0009)"
DEBUG: (2021-12-28T08:21:25.329) :0 - Received status:  "0900110005001546ffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:21:25.329) :0 - Battery percent:  70
DEBUG: (2021-12-28T08:21:25.329) :0 - received MPCmd::MOOLTIPASS_STATUS:  21
DEBUG: (2021-12-28T08:21:25.329) :0 - Update client status changed:  WSServerCon(0x7fabaaa47810)
DEBUG: (2021-12-28T08:21:25.329) :0 - Update client status changed:  WSServerCon(0x7fabaa868110)
DEBUG: (2021-12-28T08:21:25.331) :0 - "PLEASE_RETRY (0x0002)"  received, resending command  "GET_CTRVALUE (0x0109)"
DEBUG: (2021-12-28T08:21:25.689) :0 - CTR value: "000000"
DEBUG: (2021-12-28T08:21:25.755) :0 - All CPZ CTR packets received
DEBUG: (2021-12-28T08:21:25.915) :0 - Received starting node size:  17
DEBUG: (2021-12-28T08:21:25.915) :0 - Start node addr: "0000"
INFO: (2021-12-28T08:21:25.915) :0 - No parent nodes to load.
INFO: (2021-12-28T08:21:25.917) :0 - Checking database...
DEBUG: (2021-12-28T08:21:25.917) :0 - Number of parent orphans: 0
DEBUG: (2021-12-28T08:21:25.917) :0 - Number of children orphans: 0
DEBUG: (2021-12-28T08:21:25.917) :0 - Number of data parent orphans: 0
DEBUG: (2021-12-28T08:21:25.917) :0 - Number of data children orphans: 0
INFO: (2021-12-28T08:21:25.918) :0 - Database check OK
INFO: (2021-12-28T08:21:25.918) :0 - Mem management mode enabled, DB checked
DEBUG: (2021-12-28T08:24:17.372) :0 - JSON API recv: {
    "data": [
        {
            "address": [
            ],
            "category": 0,
            "description": "",
            "favorite": -1,
            "key_after_login": 65535,
            "key_after_pwd": 65535,
            "login": "XXXXXX",
            "password":"<masked>",
            "service": "manager.XXXXXX.com"
        },
        {
            "address": [
            ],
            "category": 0,
            "description": "",
            "favorite": -1,
            "key_after_login": 65535,
            "key_after_pwd": 65535,
            "login": "XXXXXX",
            "password":"<masked>",
            "service": "XXXXXX.XXXXXX.com"
        }
    ],
    "msg": "set_credentials"
}

DEBUG: (2021-12-28T08:24:17.375) :0 - MMM Save: tackling  "XXXXXX"  for service  "manager.XXXXXX.com"  at address  ""
DEBUG: (2021-12-28T08:24:17.376) :0 - New login "XXXXXX"  for service  "manager.XXXXXX.com"  at address  ""
DEBUG: (2021-12-28T08:24:17.376) :0 - Creating new service "manager.XXXXXX.com" in DB
INFO: (2021-12-28T08:24:17.376) :0 - Adding parent node "manager.XXXXXX.com"
INFO: (2021-12-28T08:24:17.377) :0 - Adding child  "mcfate"  with parent  "manager.XXXXXX.com"  to DB
DEBUG: (2021-12-28T08:24:17.377) :0 - Queing password change as well
DEBUG: (2021-12-28T08:24:17.377) :0 - MMM Save: tackling  "XXXXXX"  for service  "XXXXXX.XXXXXX.com"  at address  ""
DEBUG: (2021-12-28T08:24:17.377) :0 - New login "XXXXXX"  for service  "XXXXXX.XXXXXX.com"  at address  ""
DEBUG: (2021-12-28T08:24:17.377) :0 - Creating new service "XXXXXX.XXXXXX.com" in DB
INFO: (2021-12-28T08:24:17.377) :0 - Adding parent node "XXXXXX.XXXXXX.com"
DEBUG: (2021-12-28T08:24:17.377) :0 - Adding parent node before "manager.XXXXXX.com"
DEBUG: (2021-12-28T08:24:17.377) :0 - Parent node is the new start node
INFO: (2021-12-28T08:24:17.377) :0 - Adding child  "XXXXXX"  with parent  "XXXXXX.XXXXXXcom"  to DB
DEBUG: (2021-12-28T08:24:17.377) :0 - Queing password change as well
INFO: (2021-12-28T08:24:17.377) :0 - Checking database...
DEBUG: (2021-12-28T08:24:17.377) :0 - Number of parent orphans: 0
DEBUG: (2021-12-28T08:24:17.377) :0 - Number of children orphans: 0
DEBUG: (2021-12-28T08:24:17.377) :0 - Number of data parent orphans: 0
DEBUG: (2021-12-28T08:24:17.377) :0 - Number of data children orphans: 0
INFO: (2021-12-28T08:24:17.378) :0 - Database check OK
DEBUG: (2021-12-28T08:24:17.378) :0 - Send card db metadata
DEBUG: (2021-12-28T08:24:17.378) :0 - Sended card db metadata
DEBUG: (2021-12-28T08:24:17.378) :0 - Send card db metadata
DEBUG: (2021-12-28T08:24:17.378) :0 - Sended card db metadata
DEBUG: (2021-12-28T08:24:17.378) :0 - Loading free addresses from address: "0000"
INFO: (2021-12-28T08:24:17.378) :0 - "Merging credentials changes"
DEBUG: (2021-12-28T08:24:17.458) :0 - "0002020204020802"
INFO: (2021-12-28T08:24:17.458) :0 - Received enough free addresses
DEBUG: (2021-12-28T08:24:17.459) :0 - Setting start node to  "0202"
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for login nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for child nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for data nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for data child nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for webauthn login nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for webauthn child nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for note nodes...
DEBUG: (2021-12-28T08:24:17.459) :0 - Replacing virtual addresses for note child nodes...
INFO: (2021-12-28T08:24:17.459) :0 - Generating Save Packets...
DEBUG: (2021-12-28T08:24:17.459) :0 - Generating save packet for new service "manager.XXXXXX.com"
DEBUG: (2021-12-28T08:24:17.459) :0 - Generating save packet for new service "XXXXXX.XXXXXX.com"
DEBUG: (2021-12-28T08:24:17.459) :0 - Generating save packet for new login "XXXXXX"
DEBUG: (2021-12-28T08:24:17.459) :0 - Generating save packet for new login "XXXXXX"
DEBUG: (2021-12-28T08:24:17.460) :0 - Updating start node
INFO: (2021-12-28T08:24:17.460) :0 - Update packets were generated
INFO: (2021-12-28T08:24:17.460) :0 - "Starting merge operations..."
INFO: (2021-12-28T08:24:18.259) :0 - Merge operations succeeded!
INFO: (2021-12-28T08:24:18.259) :0 - "Check and Store Credential"
WARNING: (2021-12-28T08:24:35.041) :0 - Credential store failed
INFO: (2021-12-28T08:24:35.041) :0 - "Check and Store Credential"
WARNING: (2021-12-28T08:24:51.992) :0 - Credential store failed
INFO: (2021-12-28T08:24:51.993) :0 - "Exiting MMM"
INFO: (2021-12-28T08:24:52.174) :0 - MMM exit ok
INFO: (2021-12-28T08:24:52.175) :0 - "Changing passwords..."
INFO: (2021-12-28T08:24:52.175) :0 - Passwords changed!
DEBUG: (2021-12-28T08:24:52.218) :0 - Received status:  "0900110005000546ffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:24:52.218) :0 - Battery percent:  70
DEBUG: (2021-12-28T08:24:52.218) :0 - received MPCmd::MOOLTIPASS_STATUS:  5
DEBUG: (2021-12-28T08:24:52.219) :0 - Update client status changed:  WSServerCon(0x7fabaaa47810)
DEBUG: (2021-12-28T08:24:52.219) :0 - Update client status changed:  WSServerCon(0x7fabaa868110)
INFO: (2021-12-28T08:24:52.220) :0 - "Fetch data files"
DEBUG: (2021-12-28T08:24:52.222) :0 - JSON API recv: {
    "msg": "load_params"
}

DEBUG: (2021-12-28T08:24:52.297) :0 - Sending files cache
DEBUG: (2021-12-28T08:24:52.297) :0 - Sending files cache
INFO: (2021-12-28T08:24:52.297) :0 - "Fetch notes"
DEBUG: (2021-12-28T08:24:52.332) :0 - Sending notes
DEBUG: (2021-12-28T08:24:52.332) :0 - Sending notes
INFO: (2021-12-28T08:24:52.332) :0 - "Loading device parameters"
DEBUG: (2021-12-28T08:24:52.504) :0 - Full device settings payload:  "00000f0100090a0f0190010900000000000000000000001e00000100000000000000000000000000000000000000000000000000000000000000000000000000"
DEBUG: (2021-12-28T08:24:52.673) :0 - User language:  0
DEBUG: (2021-12-28T08:24:52.734) :0 - Device language:  0
DEBUG: (2021-12-28T08:24:52.792) :0 - Keyboard USB layout:  25
DEBUG: (2021-12-28T08:24:52.827) :0 - Keyboard Bluetooth layout:  25
INFO: (2021-12-28T08:24:52.828) :0 - "Loading device card CPZ"
DEBUG: (2021-12-28T08:24:52.883) :0 - Card CPZ:  "eafcd5fe00334733"
INFO: (2021-12-28T08:24:52.883) :0 - Finished loading card CPZ
8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
hello! the log looks perfectly fine... that's odd. 
Could you give us a step by step guide to reproduce the issue?

**Comment by stonemirror** [comment]
1. I unlocked my Mooltipass, 
2. started up Moolticute, 
3. put the Mooltipass into "Maintenance Mode", 
4. opened up my LastPass vault, 
5. copied and pasted two sets of credentials into Moolticute,
6. pressed the save (or update) button

Moolticute threw up a dialog saying that an error had occurred and I should provide you with the log. The lines that concerned me are toward the end:

INFO: (2021-12-28T08:24:17.460) :0 - Update packets were generated
INFO: (2021-12-28T08:24:17.460) :0 - "Starting merge operations..."
INFO: (2021-12-28T08:24:18.259) :0 - Merge operations succeeded!
INFO: (2021-12-28T08:24:18.259) :0 - "Check and Store Credential"
WARNING: (2021-12-28T08:24:35.041) :0 - Credential store failed
INFO: (2021-12-28T08:24:35.041) :0 - "Check and Store Credential"
WARNING: (2021-12-28T08:24:51.992) :0 - Credential store failed

They're just warnings, but I'm wondering what's going on with that and why Moolticute is telling me about it (and to tell you about it)...

**Comment by stonemirror** [comment]
This is the dialog that comes up
![Screen Shot 2021-12-28 at 1 26 59 PM](https://user-images.githubusercontent.com/412480/147608304-d94e9fc2-de77-49c4-95ce-7b249ce9fbb4.png)
:

**Comment by stonemirror** [comment]
I played around a bit more, and it seems as though the passwords on the Mooltipass aren't getting updated by Moolticute, or that's what's failing or something. This is the Moolticute entry for a credential whose password I put in two times, and updated to the device (getting the above error dialog each time).

![Screen Shot 2021-12-28 at 1 33 42 PM](https://user-images.githubusercontent.com/412480/147608932-4f2f6514-33a0-4ab9-bd68-5752f130660a.png)

Something's not working right here.

**Comment by stonemirror** [comment]
Another thing: I logged into github to open this issue and had the Mooltipass (supposedly) create a credential for me to use, but it doesn't appear in Moolticute.

**Comment by stonemirror** [comment]
More information: this problem only seems to happen when the Mooltipass is in "Expert" mode. I put it back into "Simple" mode this morning, and Moolticute appears to be updating the passwords on the Mooltipass now. No dialog comes up, and the entries show "Password Locked". (How do you edit a locked password...?)

**Comment by limpkin** [comment]
Hello @stonemirror and sorry for my delayed answer.
So the difference between expert and simple mode regarding your issue is a prompt that should appear on your device screen. When you saved your credentials in management mode, did you see a prompt appear on your device?

**Comment by limpkin** [comment]
guessing it is fixed by aaeda8b809e379fecf9ad53182a4579e6c660200
