### ISSUE TITLE
Improve Clarity of Low Battery Notification by Saying "Mooltipass" Instead of "Device"

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/moolticute#959]
### Missing feature
Moolticute currently reports low (sub-30 per cent) battery life with a system message identified as "your device"; this would be better written as "your Mooltipass".

### Justification
I don't think I've ever let the battery run down on my MBLE before, so when an unknown application started warning me that "your device" was low on battery in the GNOME Shell notification area I wasn't sure what it was. I charged my wireless mouse, but that didn't help.

Turns out it was Moolticute. Simply having it identify "your Mooltipass" rather than "your device" would have prevented my simple mind from getting confused!

### Workarounds
Now I actually know what Moolticute's low battery message looks like, I'll recognise it as and when it pops up again - but for newcomers, rewriting the notification to include the word "Mooltipass" would improve clarity.

### Version
Moolticute v0.53.8-testing on Ubuntu 20.04 64-bit.

**Comment by limpkin** [comment]
I may be mistaken, but the low battery notification is generated by OS, right @deXol ?

**Comment by ghalfacree** [comment]
I'm not sure it is, at least on Linux: the MBLE doesn't show up in GNOME's Power settings panel: only my UPS and my mouse show in there.

**Comment by ghalfacree** [comment]
Ah, no, my mistake - it *is* there, in `MainWindow.cpp`:

```
            if (battery < BATTERY_WARNING_LIMIT && !ui->label_charging->isVisible())
                {   
                    SystemNotification::instance().createNotification(tr("Low Battery"), tr("Battery is below %1%, please charge your device.").arg(BATTERY_WARNING_LIMIT));
                }
```
