### ISSUE TITLE
Charging issue?

### ISSUE THREAD

**Issue by stonemirror** [mooltipass/moolticute#962]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
My Mooltipass was down to 10% battery, so I plugged it into a (power only) USB port to recharge.  I expected it to recharge.

### Actual behavior
The Mooltipass didn't seem to charge and after a while started periodically showing the message "#002 Contact Support".

The Mooltipass seems to have shut down once or twice, Moolticute reported it couldn't communicate with the device and it didn't respond to the clickwheel.

I unplugged it from the power-only port and plugged into my Mac Mini's USB port. The charge animation is going on the screen, but Moolticute has it showing only 10% charge for some time now, and it continues to display the "#002 Contact Support" message.

### Step by step guide to reproduce the problem

Got me. But this is not being a terrific experience for me, especially at the price I paid. :(

### Moolticute Version

0.53.7

Apparently my device is on "Bundle 0", and I'd try upgrading if I could get it fully charged.

### Operating System

- MacOS  v10.15.7
  
Other operating systems are not supported.

### Mooltipass Device

- The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by stonemirror** [comment]
Sigh. Unplugging it and plugging it in again seems to have rectified things, maybe. Moolticute is showing 40% battery now, I'm not seeing the "Contact Support" message at the moment.

Moolticute says I'm on "Bundle 5" and shows no link to get an update, as it did earler. What's the latest bundle version?

**Comment by stonemirror** [comment]
The reported battery level is all over the map. I've seen it go from from 10% to 40% to 10% to 30% to 20% and back to 10%. I get regular notifications from Moolticute that the battery level is below 30% and I should charge the device.

Any suggestions would be appreciated. I'm just going to leave it connected to the USB port overnight and see what happens, I guess.

**Comment by stonemirror** [comment]
An update: after letting the Mooltipass sit for a couple of hours, it charged to 100%. I've successfully updated the device to Bundle 7, I'll let you know if anything is different.

**Comment by Arffeh** [comment]
Hello there. 

Thank you for taking the steps to update to the latest bundle. The latest bundles offer significant stability improvements.

As far as the battery is concerned, a reconditioning might be required to re-calibrate things.

When you can set aside at least 5 hours, please invoke the Advanced tab by pressing CTRL+SHIFT+F2 (or Shift+Fn+Cmd+F2 on macOS), plug your device in via USB and select the "Start NiMH Reconditioning" button. This will trigger a 5 hour long process to perform a battery maintenance operation, which may sort out the odd battery readings.

**Comment by Arffeh** [comment]
Hello @stonemirror , just following up to see if you've had time to recondition your battery.

**Comment by stonemirror** [comment]
I only just saw these messages this morning. I've just finished reconditioning the battery.

And there's a CSV import? Handy, I've been bringing things over from LastPass one-by-one...

**Comment by stonemirror** [comment]
Okay, I've reconditioned the battery as I mentioned, and I've gone through multiple charging cycles.

Things are more reasonable now, a couple of points I've noticed:

- A charge last four to five days, at least the way I'm currently using the device
- I don't get the "Below 30%" notification, even when the device is at that level, until I wake up the Mooltipass
- Moolticute seems unaware when the device is charging: it gives me a "Below 30%" notification as soon as I plug the Mooltipass into USB to recharge

Other than that, this seems to be working a lot better now, between reconditioning the battery and upgrading the bundle, thanks.
