### ISSUE TITLE
Feature request: start minimized in systray

### ISSUE THREAD

**Issue by Nautigsam** [mooltipass/moolticute#975]
### Missing feature

Configure moolticute to start minimized in system tray.

I configured moolticute (linux) to start at log in my session. But it annoys me to get the moolticute window shown while all I need from it is to run. Having it starting already minimized would be perfect.

### Workarounds

None that I can think of.

**Comment by limpkin** [comment]
Hello!
Could you share with us with Linux we're using, and which build?
I'm guessing you're not using our app image (https://github.com/mooltipass/moolticute/pull/950)
thanks!

**Comment by Nautigsam** [comment]
I use package [moolticute](https://aur.archlinux.org/packages/moolticute/) on AUR. Version 0.53.7-1.

**Comment by limpkin** [comment]
@bobsaintcool how are you doing? would you be able to assist?

**Comment by bobsaintcool** [comment]
> @bobsaintcool how are you doing? 
Good and you? I've been missing out and will jump into IRC soon.

@Nautigsam nice you play with Moolticute, could you elaborate on 
> I configured moolticute (linux) to start at log in my session.

- What did you want to achieve exactly? 
- How did you start moolticute at session log in?

From my memory  moolticute come with two part a daemon (moolticuted) and a GUI. The daemon run generally in background and talk to the devices while the GUI pop into your display and interact with the daemon.
It should be not needed to have the GUI running all the time but only when you want to play with the device. However the daemon can be started when the computer boot and killed upon its shutdown, I believe you want to achieve this.

The AUR package comes with a system wide systemd unit that can be used to enable and start the daemon. To enable (make it start every boot) and start it now:
```
# systemctl enable --now moolticuted.service
```
At this point the daemon should have been started, you can now execute the GUI, the way you do that really depend on your environment but the package also comes with a `moolticute.desktop` so you classical application launcher should recognize it when you type "moolticute" in it

**Comment by limpkin** [comment]
@bobsaintcool nice! we're on irc.liberachat now :)

**Comment by Nautigsam** [comment]
@bobsaintcool thank you for your response
> What did you want to achieve exactly?
I want to be able to use my mooltipass with the browser extension (e.g. automatic login) as soon as I log in into my session.
> How did you start moolticute at session log in?
I enabled the setting "Start Moolticute with the computer".
