### ISSUE TITLE
Built-in Text Editor - FEATURE REQUEST

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/moolticute#978]
Currently I use file storage to store text files that have passwords for things that don't work automatically (VPN, WiFi, etc). However, to view or edit these passwords, I first have to save the file to the computer. Not only is this an extra step, but if I'm using my Mooltipass on an untrusted computer, it leaves the file behind. Even deleting the file can leave it recoverable. It would be really great if there was a built in text editor to Moolicute that would allow viewing and editing files in storage within memory without ever saving them to the hard drive.

**Comment by limpkin** [comment]
You're exactly describing our notes feature... have you tried it? :)

**Comment by RChadwick7** [comment]
No, but it sounds perfect! Where is it? I couldn't find it in Moolticute.

**Comment by limpkin** [comment]
update your device to the latest bundle using https://www.themooltipass.com/updates/ then it should be displayed to you :)

**Comment by rastagraffix** [comment]
The shift+fn+cmd+f3 dance is not unlocking the developer tab for me ...

This is moolticute 0.53.7 on MacOS 12.2.

**Comment by limpkin** [comment]
to make sure: all keys are pressed at the end of the shortcut?

**Comment by RChadwick7** [comment]
Ahh, that's why I don't see it. I'm still mainly using my old Mooltipass Minis until the Mini and BLE can share a database bidirectionally.

**Comment by rastagraffix** [comment]
> to make sure: all keys are pressed at the end of the shortcut?

Yes, I pretzeled my fingers into a most unnatural state to accomplish it.  Took damn near 10 minutes to untangle them afterwards.

**Comment by rastagraffix** [comment]
Does the key sequence **really** need to be that complicated. Seems to me cmd-shift-D would do just fine.

**Comment by limpkin** [comment]
xD. 
Would you have access to a windows or linux computer to perform the update?

**Comment by limpkin** [comment]
I'm closing this issue as this feature is basically already there.
Let's continue the discussion to update your device though :)
