### ISSUE TITLE
Crash when changing service/website in MMM using "filter" to locate it

### ISSUE THREAD

**Issue by kbembedded** [mooltipass/moolticute#984]
### Actual behavior
In attempting to change some URLs of logins, if you use MMM, search for these credentials using filter, if the change to service/website no longer would show it in the filter, Moolticute crashes.

### Step by step guide to reproduce the problem
1) Create credential `testfoo.com` with arbitrary login/password
2) Enter MMM
3) Using filter/search, search for `foo`
4) Change service/website name to `testbar.com`
5) Observe crash after hitting `Confirm Changes`

This applies to subdomains as well (which is how I originally found it) e.g. `foo.domain.com` to `bar.domain.com` crashes in the same way as above. So this is likely an issue with the new name not being matched by the filter and moolticute not knowing what to do with it.

### Workaround
Don't use the filter/search bar. This is a pain when you have hundreds of credentials, and are looking to replace a handful of them after a domain change. But it does not cause the crash.

### Moolticute Version
v0.53.7

### Operating System
- Windows 10

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment]
ohhhh that's a nice catch!

**Comment by limpkin** [comment]
thanks a lot @kbembedded for reporting this! :)
