### ISSUE TITLE
Mooltipass has completely locked up on me.

### ISSUE THREAD

**Issue by stonemirror** [mooltipass/moolticute#988]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior

Mooltipass will hold a charge for more than a single day, and will recharge when it's plugged into power.

### Actual behavior

Had to recharge my device last night, a little sooner than I'd expected. Despite being connected to power, the Moolticute app never showed charge getting about 90%.

This morning, my Mooltipass is completely dead, and does not respond to being plugged into power.

I assume this device must still be covered by a warranty, it's not even three months old.

### Step by step guide to reproduce the problem

Got me.

### Moolticute Version

Bundle 7. I can't give you more information because the Mooltipass is DEAD.

### Operating System
- MacOS

**Comment by limpkin** [comment]
Hello!
I'm fairly certain the device "just" froze. Could you do the following:
- remove from USB power
- press the wheel for 30 seconds
- connect the USB power
Could you perform a battery reconditioning procedure and let us know the "score" at its end?

**Comment by stonemirror** [comment]
Ah, okay. That worked, and it's showing 100% charge. I'll get started reconditioning the battery next (second time for that).

**Comment by stonemirror** [comment]
I've started the reconditioning, I'll report back when it's completed.

**Comment by limpkin** [comment]
awesome :)

**Comment by stonemirror** [comment]
Okay, reconditioning just finished, but the dialog box doesn't report a "score", just an elapsed time. I see nothing about a score in the daemon log, either. Where would I find this?

**Comment by limpkin** [comment]
sorry, i indeed meant elapsed time, what did you get?

**Comment by stonemirror** [comment]
Oof. I thought it might have said 308-point-something, but that doesn't seem to make a ton of sense since it's only been three hours.

I was looking for a "score". :/

**Comment by limpkin** [comment]
my apologies.
so it seems your device is affected by a bug that bundle v8 will fix :).
In the meantime, could you perform a few battery reconditioning procedure until you get more than 3600 seconds?

**Comment by stonemirror** [comment]
Looking through the log, I find this entry, which seems to be the start of reconditioning:

DEBUG: (2022-02-14T10:52:54.051) :0 - JSON API recv: {
    "msg": "nimh_reconditioning"
}

INFO: (2022-02-14T10:52:54.051) :0 - "NiMH Reconditioning"

followed (eventually) by

DEBUG: (2022-02-14T14:16:18.987) :0 - NiMH Reconditioning finished

**Comment by stonemirror** [comment]
Um, okay. Six hours, huh? Oof.

**Comment by limpkin** [comment]
it will be much less in the first time given your low duration time.

**Comment by stonemirror** [comment]
Okay, I'm trying again, I'll pay better attention this time.

**Comment by stonemirror** [comment]
That cycle was 3561 seconds. Starting another now.

**Comment by limpkin** [comment]
that's already quite nice :). You should already now have standard battery life :)

**Comment by stonemirror** [comment]
Okay, that last one got me 3714 seconds, so hopefully I'm good to go. How soon is Bundle 8 going to be released?

**Comment by limpkin** [comment]
awesome! we're aiming for 2 weeks :)

**Comment by limpkin** [comment]
Perhaps we could send you another device so you could compare performances? :)

**Comment by stonemirror** [comment]
I fear it may come to that, if this keeps up.

**Comment by limpkin** [comment]
Please let me know :)

**Comment by stonemirror** [comment]
Well, if you're asking whether I'm willing to have you send me one to compare, sure, I'm willing. For reference, my serial number is BLE-2797.

The unit is now charged to 100%, and I've taken it off USB, I'll let you know how it goes.
![IMG_1511](https://user-images.githubusercontent.com/412480/154369399-da11d287-2441-4e52-9160-37481f0de01c.jpg)
,

**Comment by stonemirror** [comment]
So, I'm going to be calling it a night before long, but I've checked the battery level in Moolticute several times, and it's been consistently showing 90%, as recently as moments ago. We'll see how it looks in the morning.

**Comment by stonemirror** [comment]
As of a moment ago, battery level is at 80%.

**Comment by stonemirror** [comment]
Okay, so, it's morning now, my Mooltipass was showing 70% battery when I went to bed about nine hours ago. This morning, the Mooltipass was shut down; when I plugged it into USB power, it restarted but Moolticute immediately showed NINETY percent battery. So weird.

**Comment by stonemirror** [comment]
Okay, I'm still getting sudden, random, complete discharges of the battery. Yesterday, the device had gone two days and change without reporting the battery being low. I recharged it to 100%, and just noticed that the Mooltipass had stopped. I restarted it by clicking the clickwheel, and it reported "Battery empty". I'm recharging it (again) now.

**Comment by stonemirror** [comment]
Now, I'm getting regular "#002 Contact Support" notifications. I've tried restarting the unit (which seems to have sort of corrected — maybe — the voltage sensing. It was stuck at 60% before the reboot, now it's stuck at 90%. It's been plugged into power for about two hours.

**Comment by stonemirror** [comment]
I've unplugged it from power (showing 90% in Moolticute and four bars on the Mooltipass), and it immediately died on me.

Held down the clickwheel for thirty seconds, connected it to USB. Mooltipass restarts, and Moolticute again shows 90% battery. It didn't die when I unplugged the USB cable this time, it's still showing 90% battery in Moolticute.

**Comment by limpkin** [comment]
I'm interested about the #2 contact support message... when did that first happen? was bluetooth enabled?
Regarding the device switching off after unplug, this is what bundle v8 will fix... could you perform a reconditioning? :)

**Comment by stonemirror** [comment]
Bluetooth is not enabled. The 002 errors have been happening for about a day now, but the frequency is increasing.

Seems to have stopped since the last restart.

Sure, I'll do yet another reconditioning and report the time back whenever it finishes.

**Comment by stonemirror** [comment]
Okay, reconditioning just completed, 3819.89 seconds.

**Comment by limpkin** [comment]
That's perfect! Now the device shouldn't turn off when unplugged :)

**Comment by stonemirror** [comment]
Oh, and I was wrong, I AM using Bluetooth, duh. I use it to connect the Mooltipass to my Mac Mini desktop, sorry about that!

**Comment by stonemirror** [comment]
All right, this is odd: Moolticute reports 100% battery level, Mooltipass still shows a blinking fourth bar. Disconnect from power, it shows four full bars. Reconnect, four full bars now. Disconnecting again.

**Comment by stonemirror** [comment]
The Mooltipass was at 70% battery capacity when I went to bed last night, this morning, the battery's empty again. Charging.

**Comment by limpkin** [comment]
could you do the same tests with bluetooth off? I'm wondering if your behavior is due to it.

**Comment by stonemirror** [comment]
Okay.

Note that this won't represent a "solution" for me: I won't be able to use the Mooltipass anywhere but other than my desktop, and only when it's plugged into USB, but for the sake of science, I'll go ahead.

**Comment by limpkin** [comment]
of course, i just want to better understand what could be causing this.

**Comment by stonemirror** [comment]
Okay, it's at 100% charge, I've taken it off USB to see how the battery holds up.

**Comment by stonemirror** [comment]
Okay, so in two days with Bluetooth off, the battery's gone from 100% to 90% and I haven't caught any 002 errors happening. I'll keep checking. Are there Bluetooth fixes in Bundle 8?

**Comment by limpkin** [comment]
yes, but none that address the issues you're having.
I think it's time we send you another device so you can compare how it performs compared to yours... can you reach us at support[at]themooltipass(dot)com?

**Comment by stonemirror** [comment]
Yes, I will.

**Comment by stonemirror** [comment]
Okay, email has been sent.

**Comment by stonemirror** [comment]
I wanted to pass along a data point for you that might be interesting: I've had the Mooltipass off USB, with Bluetooth disabled, two weeks ago. I fully charged the device before taking off USB, and I've only connected it to check the battery level or to actually use it.

The battery has consistently been dropping by very small amounts, it was down to 70% today. I used it to log into a site — possibly for the first time in two weeks, most sites I use regularly keep me logged in — and the battery level immediately dropped down to 10%! I'm charging it up again now.

The actual password vault functionality seems to work very well.

**Comment by stonemirror** [comment]
Aaand charged back up to full. Seems quick, but I don't know, I never timed it.

**Comment by limpkin** [comment]
could you upgrade to bundle v8 using https://beta-updates.themooltipass.com/?

**Comment by stonemirror** [comment]
Yes, I'll do that, thanks.

**Comment by stonemirror** [comment]
I've upgraded to bundle v8 successfully (and I've turned Bluetooth back on).

**Comment by stonemirror** [comment]
The new Mooltipass unit arrived just now, thank you! Battery was empty, so I'm charging it, without a card in it, and without having done anything else. Moolticute reports the bundle version as v5.

Let me know how you'd like me to proceed in setting this up. I backed up the original Mooltipass before upgrading to the v8 beta bundle.

**Comment by limpkin** [comment]
you may put bundle v8 on the new device and use it the same way as you used the old one :)

**Comment by stonemirror** [comment]
Okay. Upgrade the bundle, restore the backup from the old device to the new, and use the same access card in both devices, then?

**Comment by stonemirror** [comment]
Small problem: serial # 2732 is not associated with my email address — the one from which I emailed you — and the download site doesn't "recognize the combination". I think this is something that needs to be updated from your end?

In the meantime, I've gotten the database transferred to the new device without any problem.

**Comment by stonemirror** [comment]
So, I've been using the second unit for three days now, and my impression is that the battery behavior is less wonky than the first unit. As mentioned, I charged it to 100% from empty, it's currently at 40%. There hasn't been any noticeable jumps in reported battery level either up or down. No 002 errors.

This is all despite still being on Bundle v5....

**Comment by limpkin** [comment]
if that's ok, I think i'll ask you to return me the old unit then :)

**Comment by stonemirror** [comment]
Sure. Email me where you want it sent to, and I'll get it taken care of this coming week — it involves a trip to the Post Office, I have no idea where it's going or what the postage would be.

One other note: The new Mooltipass was down to 30% battery this morning; when I connected it to USB to recharge, the reported voltage did not drop to zero, as it seems to always have done with the old unit, it still reports 30% as it's charging.

I suspect some issues with the voltage-sensing on the other device at this point.

**Comment by stonemirror** [comment]
Maybe I spoke to soon: after an hour on charge, the "Please connect Mooltipass to power" alert popped up, the reported voltage is now 20%, down from 30%.

Is there some way to simply inhibit that notification when the device is attached to power? It seems unnecessary, and it'll pop up every increment of 10% until it exceeds 30...

**Comment by limpkin** [comment]
this small discrepancies are to be expected during charging. I'm afraid there's currently no way to disable that notification :(

**Comment by stonemirror** [comment]
The original, and subsequent issues with the device I've now sent back seem to have been resolved by the replacement device, so I'm closing this issue at this point.

**Comment by limpkin** [comment]
awesome! :)
