### ISSUE TITLE
Credentials Management bulk accept

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/moolticute#990]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
I just input a whole lot of passwords at once while in Credentials Management mode and at the end found out you have to manually confirm ALL of them (took a while). So I've been thinking that it would be useful to not require that manual accepting thing in management mode, or at least to have an accept all setting.

### Justification
If you input a whole lot of passwords it's gonna take a while (it's not really user friendly).

### Workarounds
Accept them one by one

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
there's a device setting for that actually: section "Storage Confirmation in Management Mode" in our user manual :)
