### ISSUE TITLE
Moolticute windows 11 scaling issue

### ISSUE THREAD

**Issue by chucktastic** [mooltipass/moolticute#991]
I just installed Moolticute on my new windows 11 laptop with the resolution of 2560x1440.  At the recommended display scaling of 150% the Moolticute app and the the browser plugin are scaled so big/tall that they do not fit on the screen.  The bottom of the window is off the display so the initial tutorial cannot be completed.  

If I grab the top of the window border to resize it, the whole window drops down and outside of the viewable desktop space as soon as I move the mouse.

At 125% scaling the app fits the screen and the resizing seems to work like normal.  However, setting the scaling back to 150% resizes the window to be too tall and the app cannot be properly resized as described above.

To reproduce:
Windows 11 Pro 22000.527
Mooltipass v0.53.7
Resolution 2560x1440 with 150% scaling

**Comment by limpkin** [comment]
hello!
could you upload a picture of your screen here? thanks :)

**Comment by chucktastic** [comment]
Here you go
![mooltipasstoobig](https://user-images.githubusercontent.com/5589545/154496993-055c8549-5d89-4d9d-a4c3-3ac86a06ead3.jpg)

**Comment by limpkin** [comment]
thanks! we're about to switch to qt6 so hopefully things should get better by then :)

**Comment by limpkin** [comment]
@chucktastic how's your issue now that we've migrated to qt6? :)

**Comment by chucktastic** [comment]
Is there a pre-built 0.55.1 to try?  I'm not set up to build from source.

**Comment by limpkin** [comment]
here :)
https://betas.themooltipass.com/v0.55.1-testing/

**Comment by chucktastic** [comment]
Definitely much better.

![mooltipassbetter](https://user-images.githubusercontent.com/5589545/167306810-2d07d5ea-2c86-4e51-bbb9-76a6f6d56d57.jpg)

**Comment by limpkin** [comment]
awesome! should we close the issue? :)

**Comment by chucktastic** [comment]
My issue with scaling is resolved.  The app is fully usable for me again.  No problem with closing it.
