### ISSUE TITLE
(macOS) Application window is too large for the display during Tutorial

### ISSUE THREAD

**Issue by MaplesThroughWindows** [mooltipass/moolticute#997]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
The Moolticute application window should not automatically resize itself during the tutorial so that the application window expands off the bottom edge of the display, obscuring tutorial text and making it difficult to resize the window.

### Actual behavior
The Moolticute application window automatically resizes itself at one point in the tutorial so that the application window expands off the bottom edge of the display, obscuring tutorial text and making it difficult to resize the window.

### Step by step guide to reproduce the problem
1) Run the Moolticute app on a display with a resolution of 1440 x 900.
2) Follow the Moolticute tutorial until it reaches the Settings tab.
3) The application window will resize itself to fit the Tutorial footer underneath the main application window.  This will push the Tutorial footer off the bottom of the screen, causing navigation difficulties and hiding the tutorial text.
### Moolticute Version
0.53.7

### Operating System
MacOS  10.13.6
  
Other operating systems are not supported.

### Mooltipass Extension
N/A

### Mooltipass Device
The Mooltipass Mini BLE

8<------------------------ END BUG REPORT -------------------------------------

**Comment by MaplesThroughWindows** [comment]
I've just noticed that this exact problem also occurs on the Credentials tab.  After entering a new credential in the "Add or update a credential" section (not in Credentials Management Mode), the pop-up at the bottom of the window ("Do you want to export your database?") is obscured in the same way as the Tutorial text:

**Comment by limpkin** [comment]
Hello there!
We've just released our latest moolticute beta for macOS, compiled with the QT6 framework (it took us a while...). Would you be able to download and install it at https://betas.themooltipass.com/v0.55.10-testing/Moolticute-v0.55.10-testing.dmg and let us know if you still experience this issue?
